### PR TITLE
File system create directory tests check directories are created

### LINKED ISSUE #101: Filesystem test issues
I noticed (due to running tests in parallel) that Unit.Utilities.FileSystem.create_and_rm_empty_directory checks for existence of the wrong file.  I was going to just fix that, but then I saw that the create_directory tests don't actually check that the directories have been created in many cases.  As this is getting non-trivial I'm just filing a bug instead of trying to provide a fix right now.

### PR DESCRIPTION
**Pull request by nilsdeppe**
Fix #101

### CODE REVIEW

File: tests/Unit/Utilities/Test_FileSystem.cpp [hunk 1]
```diff
@@ -123,12 +125,14 @@ TEST_CASE("Unit.Utilities.FileSystem.create_and_rm_directory",
...
+  CHECK(file_system::check_if_dir_exists(dir_name));
+  file_system::rm(dir_name, false);
   const auto files = file_system::ls("./");
   const bool dir_deleted = std::none_of(
-      files.begin(), files.end(), [](const std::string& file_name) {
-        return "create_and_rm_directory"s == file_name;
+      files.begin(), files.end(), [&dir_name](const std::string& file_name) {
+        return dir_name == file_name;
       });
   CHECK(dir_deleted);
```
Comment (wthrowe) [inline tests/Unit/Utilities/Test_FileSystem.cpp]: Some reason not to just use check_if_dir_exists here?

Comment (nilsdeppe) [reply tests/Unit/Utilities/Test_FileSystem.cpp]: None, pushed fixup

**Review by kidder — DISMISSED** [review]

**Review by kidder — APPROVED** [review]
