### PR TITLE
Fix a CMake 4.1 warning, relax a test tolerance

### LINKED ISSUE #6716: Random failure in Unit.Elliptic.DG.SubdomainOperator
From #6715
```
2025-06-26T17:59:48.1685460Z  446/1699 Test  #441: Unit.Elliptic.DG.SubdomainOperator .........................................................***Failed    1.57 sec
2025-06-26T17:59:48.1687040Z SpECTRE Build Information:
2025-06-26T17:59:48.1687990Z Version:                      2025.04.21
2025-06-26T17:59:48.1688390Z Compiled on host:             Mac-1750955474818.local
2025-06-26T17:59:48.1688830Z Compiled in directory:        /Users/runner/work/spectre/spectre/build
2025-06-26T17:59:48.1689350Z Source directory is:          /Users/runner/work/spectre/spectre
2025-06-26T17:59:48.1689750Z Compiled on git branch:       HEAD
2025-06-26T17:59:48.1690480Z Compiled on git revision:     8c1d2d0
2025-06-26T17:59:48.1690870Z Linked on:                    2025-06-26T16:56:05+00:00
2025-06-26T17:59:48.1691900Z Build type:                   Debug
2025-06-26T17:59:48.1692320Z Filters: ""Unit.Elliptic.DG.SubdomainOperator""
2025-06-26T17:59:48.1692670Z Randomness seeded to: 3367613816
2025-06-26T17:59:48.1693090Z Increasing order of element [B0,(L1I0)]: (3) -> (4)
2025-06-26T17:59:48.1693470Z Increasing order of element [B0,(L1I1)]: (3) -> (4)

<snip>

2025-06-26T17:59:48.6148440Z Increasing order of element [B0,(L1I0,L1I1)]: (3,3) -> (4,3)
2025-06-26T17:59:48.6148820Z Increasing order of element [B0,(L1I1,L1I0)]: (3,3) -> (3,4)
2025-06-26T17:59:48.6149180Z Increasing order of element [B0,(L1I1,L1I1)]: (3,3) -> (4,3)
2025-06-26T17:59:48.6149450Z 
2025-06-26T17:59:48.6149640Z ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2025-06-26T17:59:48.6150080Z "Debug.Unit.Elliptic.DG.SubdomainOperator" is a Catch2 v3.8.1 host application.
2025-06-26T17:59:48.6150460Z Run with -? for options
2025-06-26T17:59:48.6150650Z 
2025-06-26T17:59:48.6150860Z -------------------------------------------------------------------------------
2025-06-26T17:59:48.6152070Z Unit.Elliptic.DG.SubdomainOperator
2025-06-26T17:59:48.6152410Z -------------------------------------------------------------------------------
2025-06-26T17:59:48.6153100Z /Users/runner/work/spectre/spectre/tests/Unit/Elliptic/DiscontinuousGalerkin/SubdomainOperator/Test_SubdomainOperator.cpp:884
2025-06-26T17:59:48.6153690Z ...............................................................................
2025-06-26T17:59:48.6153950Z 
2025-06-26T17:59:48.6154250Z /Users/runner/work/spectre/spectre/tests/Unit/Framework/TestingFramework.hpp:115: FAILED:
2025-06-26T17:59:48.6155030Z   CHECK( a == appx(b) )
2025-06-26T17:59:48.6155730Z with expansion:
2025-06-26T17:59:48.6155990Z   -515.83418706804513931
2025-06-26T17:59:48.6156230Z   ==
2025-06-26T17:59:48.6159470Z   Approx( -515.83418708366571082 )
2025-06-26T17:59:48.6159790Z with messages:
2025-06-26T17:59:48.6160020Z   Complex-valued system
2025-06-26T17:59:48.6160900Z   Dim := 2
2025-06-26T17:59:48.6161140Z   penalty_parameter := 1.19999999999999996
2025-06-26T17:59:48.6161430Z   use_massive_dg_operator := true
2025-06-26T17:59:48.6161940Z   Seed is: 3925387701 from /Users/runner/work/spectre/spectre/tests/Unit/
2025-06-26T17:59:48.6162420Z   Elliptic/DiscontinuousGalerkin/SubdomainOperator/Test_SubdomainOperator.cpp:
2025-06-26T17:59:48.6162790Z   591
2025-06-26T17:59:48.6163470Z   overlap := 2
2025-06-26T17:59:48.6163700Z   element_ids.size() := 4
2025-06-26T17:59:48.6163940Z   Run AMR!
2025-06-26T17:59:48.6164160Z   subdomain_center := [B0,(L1I0,L1I1)]
2025-06-26T17:59:48.6164570Z   /Users/runner/work/spectre/spectre/tests/Unit/Elliptic/DiscontinuousGalerkin/
2025-06-26T17:59:48.6165050Z   SubdomainOperator/Test_SubdomainOperator.cpp:396: result_buffer ==
2025-06-26T17:59:48.6165420Z   expected_operator_applied_to_data
2025-06-26T17:59:48.6165680Z   a := Element data:
2025-06-26T17:59:48.6165930Z   DgOperatorAppliedTo(Operand(MMode)):
2025-06-26T17:59:48.6166290Z   T()=((1.04423e+06,-1.2179e+06),(-6534.77,-18996.6),(1.1995e+07,-1.55085e+07),
2025-06-26T17:59:48.6166730Z   (2.00926e+07,5.36995e+07),(1.62693e+06,383004),(-15833,-1205.25),(5.74426e+
2025-06-26T17:59:48.6167160Z   06,8.38969e+06),(-1.22106e+07,-1.34211e+07),(-242166,1.41975e+06),(4439.47,
2025-06-26T17:59:48.6167620Z   12414.1),(-9.19379e+06,1.99482e+07),(-2.6309e+07,-6.05681e+07))
2025-06-26T17:59:48.6168380Z   Overlap data:
2025-06-26T17:59:48.6168680Z   ([(+0, [B0,(L1I1,L1I1)]),DgOperatorAppliedTo(Operand(MMode)):
2025-06-26T17:59:48.6169060Z   T()=((-3.05205e+07,-2.9402e+06),(-5.6192e+08,-2.04695e+08),(-1.94759e+07,-
2025-06-26T17:59:48.6169750Z   515.834),(3.22818e+08,9.45706e+07),(2.09499e+07,2.96124e+06),(7.24734e+08,2.
2025-06-26T17:59:48.6170220Z   52227e+08))],[(-1, [B0,(L1I0,L1I0)]),DgOperatorAppliedTo(Operand(MMode)):
2025-06-26T17:59:48.6170630Z   T()=((-911445,2.5283e+06),(7.15679e+06,8.49808e+06),(1.99465e+07,-7.36627e+
2025-06-26T17:59:48.6171020Z   07),(465004,-338057),(1.3011e+07,242488),(7.03343e+07,-4.48032e+07))])
2025-06-26T17:59:48.6172370Z   b := Element data:
2025-06-26T17:59:48.6172630Z   DgOperatorAppliedTo(Operand(MMode)):
2025-06-26T17:59:48.6172970Z   T()=((1.04423e+06,-1.2179e+06),(-6534.77,-18996.6),(1.1995e+07,-1.55085e+07),
2025-06-26T17:59:48.6173490Z   (2.00926e+07,5.36995e+07),(1.62693e+06,383004),(-15833,-1205.25),(5.74426e+
2025-06-26T17:59:48.6184120Z   06,8.38969e+06),(-1.22106e+07,-1.34211e+07),(-242166,1.41975e+06),(4439.47,
2025-06-26T17:59:48.6194470Z   12414.1),(-9.19379e+06,1.99482e+07),(-2.6309e+07,-6.05681e+07))
2025-06-26T17:59:48.6295210Z   Overlap data:
2025-06-26T17:59:48.6396060Z   ([(+0, [B0,(L1I1,L1I1)]),DgOperatorAppliedTo(Operand(MMode)):
2025-06-26T17:59:48.6497340Z   T()=((-3.05205e+07,-2.9402e+06),(-5.6192e+08,-2.04695e+08),(-1.94759e+07,-
2025-06-26T17:59:48.6596140Z   515.834),(3.22818e+08,9.45706e+07),(2.09499e+07,2.96124e+06),(7.24734e+08,2.
2025-06-26T17:59:48.6660320Z   52227e+08))],[(-1, [B0,(L1I0,L1I0)]),DgOperatorAppliedTo(Operand(MMode)):
2025-06-26T17:59:48.6661510Z   T()=((-911445,2.5283e+06),(7.15679e+06,8.49808e+06),(1.99465e+07,-7.36627e+
2025-06-26T17:59:48.6663220Z   07),(465004,-338057),(1.3011e+07,242488),(7.03343e+07,-4.48032e+07))])
2025-06-26T17:59:48.6663530Z 
2025-06-26T17:59:48.6663760Z Increasing order of element [B0,(L1I0,L1I0)]: (3,3) -> (3,4)
2025-06-26T17:59:48.6664400Z Increasing order of element [B0,(L1I1,L1I0)]: (3,3) -> (4,3)
2025-06-26T17:59:48.6664810Z Increasing order of element [B0,(L1I1,L1I1)]: (3,3) -> (4,3)
2025-06-26T17:59:48.6665180Z 1.351 s: Unit.Elliptic.DG.SubdomainOperator
2025-06-26T17:59:48.6665520Z ===============================================================================
2025-06-26T17:59:48.6665850Z test cases:     1 |     0 passed | 1 failed
2025-06-26T17:59:48.6666150Z assertions: 95995 | 95994 passed | 1 failed
```

### PR DESCRIPTION
**Pull request by nilsvu**
### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by wthrowe — DISMISSED** [review]

File: tests/Unit/Elliptic/DiscontinuousGalerkin/SubdomainOperator/Test_SubdomainOperator.cpp [hunk 1]
```diff
@@ -388,7 +388,7 @@ struct TestSubdomainOperatorMatrix {
               result_buffer.begin());
     const auto& expected_operator_applied_to_data =
         db::get<SubdomainOperatorAppliedToDataTag<Dim, Fields>>(box);
-    Approx custom_approx = Approx::custom().epsilon(1.e-12).scale(1.0);
+    Approx custom_approx = Approx::custom().epsilon(1.e-8).scale(1.0);
```
Comment (nilsdeppe) [inline tests/Unit/Elliptic/DiscontinuousGalerkin/SubdomainOperator/Test_SubdomainOperator.cpp]: want to make this `const` while you're touching this line?

**Review by wthrowe — APPROVED** [review]
Does this mean we can close #6716?

**Comment by nilsvu** [comment]
I think so, unless more test failures come up
