### PR TITLE
Print more information when an exception is caught by DistributedObject

### LINKED ISSUE #5101: Add ElementId (and more?) to error messages
It would be helpful to supplement error messages with things like the element ID. I think this would be possible by catching exceptions somewhere in `DistributedObject` and then re-throwing them.

### PR DESCRIPTION
**Pull request by kidder**
## Proposed changes

Print the component, array index, phase, and algorithm step in addition to the exception message and type.

Fix #5101 

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — DISMISSED** [review]

File: src/Parallel/DistributedObject.hpp [hunk 1]
```diff
@@ -1185,9 +1185,14 @@ void DistributedObject<ParallelComponent,
         "an issue.");
     sys::abort("");
   }
-  const std::string message = MakeString{}
-                              << "Message: " << exception.what() << "\nType: "
-                              << pretty_type::get_runtime_type_name(exception);
+  const std::string message =
+      MakeString{} << "Component: "
+                   << pretty_type::get_name<parallel_component>() << "\n"
```
Comment (knelli2) [inline src/Parallel/DistributedObject.hpp]: `pretty_type::name<parallel_component>()` or else all control system (or interpolation target) singletons will have the same name.

**Review by knelli2 — CHANGES_REQUESTED** [review]

File: src/Parallel/DistributedObject.hpp (hunk 1 above)
Comment (kidder) [reply src/Parallel/DistributedObject.hpp]: that's not true.  this prints out the full type name including all template arguments...
but `name` is less verbose so I'll make the change since one of the template arguments for DgElementArray is the PDAL

**Review by knelli2 — APPROVED** [review]
