### PR TITLE
Fix slow vector tests gcc10

### LINKED ISSUE #2717: Test_ComplexDataVectorBinaryOperations.cpp takes 10 minutes to build
# Bug reports:

I'm using GCC-10 in release mode with debug symbols on Ubuntu 20.10:
```
cmake -GNinja -D CHARM_ROOT=/home/nils/SpECTRE/charm/netlrts-linux-x86_64-smp-gcc \
  -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 \
  -D DEBUG_SYMBOLS=ON -D BUILD_SHARED_LIBS=ON -D CMAKE_BUILD_TYPE=Release \
  -D BUILD_PYTHON_BINDINGS=ON /home/nils/SpECTRE/spectre
```
and `LibraryVersions.txt`:
```
CMake Version: 3.18.2
SpECTRE Version: 2020.12.7
Git description: 
Git branch: container_updates
Git hash: 759a5d50fc39638aa04441c5db7ac6c44b790d50
Hostname: nilser
Host system: Linux-5.8.0-31-generic
Host system version: 5.8.0-31-generic
Host system processor: x86_64
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS:  -L/home/nils/SpECTRE/charm/netlrts-linux-x86_64-smp-gcc/lib -fuse-ld=gold
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Release
CMAKE_CXX_COMPILER: /usr/bin/g++-10
CMAKE_CXX_COMPILER_VERSION: 10.2.0
CMAKE_C_COMPILER: /usr/bin/gcc-10
CMAKE_C_COMPILER_VERSION: 10.2.0
CMAKE_Fortran_COMPILER: /usr/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 10.2.0
Python Version: 3.8.6
```
I'm curious if this can be reproduced on other systems. I would say this is an unacceptably long build time for a single file. I don't think it takes this long with debug symbols off (I haven't tried, but it built in CI, which is a good sign). This is almost the exact same setup that the container has.

I'm not sure that splitting the file up is really the right solution here, since it's likely the proliferation of intermediate types created by the test that is the problem. One way of reducing that is to have a `BinOp` class that replaces the:
```cpp
std::make_tuple(funcl::Divides<>{}, std::make_tuple(generic, positive))
```
taking in its constructor this information (i.e. runtime info as to what operator to use). Another thing that could help is changing the `TestKind` information to runtime. Looking through the test, I think the issue likely just boils down to many nested `tmpl::for_each`-type operations that creates likely thousands of functions and types. I'm not sure how long the `std::tuple`s end up getting, but `std::tuple` (in the libstdc++ implementation) scales impressively poorly (but ABI compatibility means we are likely 10+ years away from a rewrite). I'm hoping this isn't a Blaze compilation time explosion issue.

I think the action items are:
- [ ] verify this isn't something weird with my system by testing on different machine
- [ ] test with newest Blaze (@moxcodes's PR should be useful for this)
- [ ]  assuming issue persists in newest Blaze, reduce number of `std::tuple`s generated by using more runtime info

### PR DESCRIPTION
**Pull request by moxcodes**
## Proposed changes

fixes #2717 

On my system, this change took the compile time down from 9:30 for the single test in question to 1:10. 

Because GCC-10 is not yet in the CI, I'll have to ask @nilsdeppe to verify that this addresses the compilation time problem he identified.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

File: tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp [hunk 1]
```diff
@@ -5,6 +5,8 @@
 
 #include <algorithm>
 #include <array>
+#include <boost/variant/multivisitors.hpp>
+#include <boost/variant/variant.hpp>
```
Comment (nilsdeppe) [inline tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp]: why not use `std::variant`? I think it supports all the features that boost does, but slightly different names

File: tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp [hunk 2]
```diff
@@ -500,22 +496,79 @@ struct VectorOrArrayAt {
...
 auto wrap_tuple(std::tuple<Operands...>& operand_values,
+                const WrapTuple& wraps,
                 std::index_sequence<Is...> /*meta*/) noexcept {
-  return std::make_tuple(wrap(Wraps{}, get<Is>(operand_values))...);
+  return std::make_tuple(wrap(get<Is>(wraps), get<Is>(operand_values))...);
 }
 
+// CHECK forwarding for parameter pack expansion. Return value also required for
+// easy parameter pack use.
+template <typename Approx>
```
Comment (nilsdeppe) [inline tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp]: Since `Approx` is an actual type in Catch, I'm a but surprised that it is a template parameter.  You already include Catch. You will need to mark the function `inline`. If you prefer `FORCE_INLINE` add the include for that

File: tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp [hunk 3]
```diff
@@ -500,22 +496,79 @@ struct VectorOrArrayAt {
...
+SPECTRE_ALWAYS_INLINE int call_check_approx(double a, double b,
```
Comment (nilsdeppe) [inline tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp]: `const` on at least the `double`s. Probably `const &` on the approx

File: tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp [hunk 4]
```diff
@@ -500,22 +496,79 @@ struct VectorOrArrayAt {
...
+                                            Approx custom_approx) noexcept {
+  CHECK(custom_approx(real(a)) == real(b));
+  CHECK(custom_approx(imag(a)) == imag(b));
+  return 0;
+}
+
+template <typename Function, size_t... Is>
+class CheckWrappedOperandsVisitor {
+ public:
+  CheckWrappedOperandsVisitor(const Function function) : function_{function} {}
```
Comment (nilsdeppe) [inline tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp]: explicit

File: tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp [hunk 5]
```diff
@@ -500,22 +496,79 @@ struct VectorOrArrayAt {
 // given an explicit template parameter pack `Wraps`, wrap the elements of
 // `operand`, passed by pointer, element-by-element, and return the
 // resulting tuple of wrapped elements.
-template <typename... Wraps, typename... Operands, size_t... Is>
+template <typename WrapTuple, typename... Operands, size_t... Is>
 auto wrap_tuple(std::tuple<Operands...>& operand_values,
+                const WrapTuple& wraps,
```
Comment (nilsdeppe) [inline tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp]: can `wraps` be a `std::array<UseRefWrap, sizeof...(Is)>` or a `std::vector`? I wouldn't worry about memory allocations and use whichever is easier.  I think that make the code easier to read (fewer template parameters :) )

**Review by nilsdeppe — COMMENTED** [review]
That's a pretty big gain! Thanks for doing this :)

File: tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp (hunk 3 above)
Comment (moxcodes) [reply tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp]: can't `const &` the approx because the approx call operator isn't const (not sure why...).

Comment (nilsdeppe) [reply tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp]: :+1:

**Review by nilsdeppe — COMMENTED** [review]
LGTM! Please go ahead and squash. Thanks for doing this!

**Comment by moxcodes** [comment]
squashed.
Cheers!

**Review by nilsdeppe — DISMISSED** [review]

File: tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp [hunk 6]
```diff
@@ -529,12 +598,16 @@ void test_function_on_vector_operands(
...
               std::get<Is>(bounds)},
           size)...};
-  // wrap the tuple of random values according to the passed in `Wraps`
-  auto wrapped_operands = wrap_tuple<Wraps...>(
-      operand_values, std::make_index_sequence<sizeof...(Bounds)>{});
-  CHECK_CUSTOM_ELEMENT_WISE_FUNCTION_APPROX(
-      function, make_not_null(&wrapped_operands), VectorOrArrayAt{},
-      VectorOrArraySize{});
+  // wrap the tuple of random values according to the passed in `wraps` -- these
+  // will end up being a tuple of boost::variant, that we need to choose between
```
Comment (kidder) [inline tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp]: std::variant?

**Review by kidder — CHANGES_REQUESTED** [review]

**Comment by moxcodes** [comment]
squashed in the comment change.
Cheers!

**Review by kidder — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]
