### PR TITLE
Fix clang-tidy warnings and false positives

### LINKED ISSUE #132: reduce clang-tidy noise
See https://travis-ci.org/sxs-collaboration/spectre/jobs/257403233

### PR DESCRIPTION
**Pull request by nilsdeppe**
Fix #132

### CODE REVIEW

File: tests/Unit/TestHelpers.hpp [hunk 1]
```diff
@@ -29,8 +31,9 @@
  * \details
  * In order to properly handle aborting with Catch versions newer than 1.6.1
  * we must install a signal handler after Catch does, which means inside the
- * TEST_CASE itself. The ERROR_TEST() macro should be the first line in the
- * TEST_CASE.
+ * SPECTRE_TEST_CASE itself. The ERROR_TEST() macro should be the first line in
+ * the
+ * SPECTRE_TEST_CASE.
```
Comment (wthrowe) [inline tests/Unit/TestHelpers.hpp]: formatting

File: docs/DevGuide/WritingTests.md [hunk 2]
```diff
@@ -7,16 +7,16 @@ See LICENSE.txt for details.
...
+When testing `ASSERT`s you must mark the `SPECTRE_TEST_CASE` as `[[noreturn]]`,
 add the macro `ASSERTION_TEST();` to the beginning of the test, and also have
 the test call `ERROR("Bad test end");` at the end of the test body.
 For example,
 
 ```cpp
 // [[OutputRegex, Must copy into same size]]
-[[noreturn]] TEST_CASE("Unit.DataStructures.DataVector.ref_diff_size",
+[[noreturn]] SPECTRE_TEST_CASE("Unit.DataStructures.DataVector.ref_diff_size",
                        "[DataStructures][Unit]") {
```
Comment (wthrowe) [inline docs/DevGuide/WritingTests.md]: formatting

File: cmake/SetupClangTidy.cmake [hunk 3]
```diff
@@ -18,13 +18,17 @@ endif()
 # Remove the checks because:
 # -llvm-header-guard: We use pragma once instead of include guards
 # -google-runtime-int: specifying int32_t and int64_t instead of just int
+# -google-runtime-references: we use return by reference for performance reasons
```
Comment (wthrowe) [inline cmake/SetupClangTidy.cmake]: I'm not advocating we change our policy, but I'd like to point out that the Google style is not that all functions must return everything in their return value, but that any "return arguments" must be pointers (so it is clear at the call site whether an argument can be modified).  So "performance reasons" is not really a valid rationale for disabling this: it's just a style choice.

File: src/DataStructures/IndexIterator.hpp [hunk 4]
```diff
@@ -35,7 +35,7 @@ class IndexIterator {
   /// \endcond
 
   /// Returns false if the end of the Index iteration is reached
-  operator bool() const noexcept { return valid_; }
+  operator bool() const noexcept { return valid_; }  // NOLINT
```
Comment (wthrowe) [inline src/DataStructures/IndexIterator.hpp]: I'm guessing that this was complaining that the operator isn't explicit.  (I don't see anything else interesting here.)  Rather than silencing the warning, I think we want these to be explicit.

Comment (wthrowe) [reply src/DataStructures/IndexIterator.hpp]: In general comments about what is being silenced would be nice as well.

**Review by kidder — DISMISSED** [review]

**Comment by nilsdeppe** [comment]
@wthrowe once you're happy I will squash the fixups :)

**Comment by wthrowe** [comment]
The new changes look good to me, but apparently something went wrong in there since Travis says it doesn't compile anymore with gcc.

**Comment by nilsdeppe** [comment]
:( Alright, all fixed up! I'll file an issue once we merge this with the link to the the travis build so people can fix their things.

**Review by kidder — APPROVED** [review]
