### PR TITLE
Move YlmSpherepack to NumericalAlgorithms/SphericalHarmonics.

### LINKED ISSUE #3573: Cyclic dependency between ApparentHorizons and CoordinateMaps
# Bug reports:

While attempting to fix a missing link dependency to get a shared-libs build on my machine working, I ran into this issue:

```
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):  "ApparentHorizons" of type SHARED_LIBRARY
    depends on "Domain" (weak)
    depends on "CoordinateMaps" (weak)
    depends on "DomainCreators" (weak)
    depends on "DomainTimeDependence" (weak)
  "Domain" of type SHARED_LIBRARY
    depends on "CoordinateMaps" (weak)
    depends on "ApparentHorizons" (weak)
  "CoordinateMaps" of type SHARED_LIBRARY
    depends on "ApparentHorizons" (weak)
  "DomainCreators" of type SHARED_LIBRARY
    depends on "CoordinateMaps" (weak)
    depends on "ApparentHorizons" (weak)
    depends on "DomainTimeDependence" (weak)
    depends on "Domain" (weak)
  "DomainTimeDependence" of type SHARED_LIBRARY
    depends on "CoordinateMaps" (weak)
    depends on "ApparentHorizons" (weak)
```

The problem is that `ApparentHorizons` depends on `Domain` in `StrahlkorperInDifferentFrame.cpp`, and the shape map depends on `ApparentHorizons` by including `YlmSpherepack`. We really need to disentangle these Ylm/AH/Domain/CoordMaps libs...

I think this issue can be fixed by #3381 (or a variant thereof). I think the AH finder will need to depend on `Domain`, but we have to eliminate the reverse dependency.

### PR DESCRIPTION
**Pull request by markscheel**
This should fix #3573, and it does some of #3381

Just moves code around, changing nothing else except for where needed in CMakeLists and includes.

More code can be moved in the future, not sure if in this PR or subsequent PRs. (For example, maybe Strahlkorper can be moved too)

### Upgrade instructions

YlmSpherepack is now in the library NumericalAlgorithms/SphericalHarmonics.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

File: src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepack.hpp [hunk 1]
```diff
@@ -9,7 +9,7 @@
 #include <utility>
 #include <vector>
 
-#include "ApparentHorizons/YlmSpherepackHelper.hpp"
+#include "NumericalAlgorithms/SphericalHarmonics/YlmSpherepackHelper.hpp"
```
Comment (wthrowe) [inline src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepack.hpp]: Alphabetize.

File: src/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+  YlmSpherepackHelper.hpp
+  )
+
+target_link_libraries(
+  ${LIBRARY}
+  PUBLIC
+  Blas
+  DataStructures
+  ErrorHandling
+  SPHEREPACK
```
Comment (wthrowe) [inline src/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt:31]: And `Utilities`, I think.

**Review by wthrowe — CHANGES_REQUESTED** [review]

File: src/Domain/CoordinateMaps/TimeDependent/Shape.cpp [hunk 3]
```diff
@@ -12,12 +12,12 @@
 #include <pup_stl.h>
 #include <string>
 
-#include "ApparentHorizons/SpherepackIterator.hpp"
 #include "ApparentHorizons/TagsTypeAliases.hpp"
```
Comment (nilsvu) [inline src/Domain/CoordinateMaps/TimeDependent/Shape.cpp:16]: Can this include be deleted? Same in the hpp. Then the lib is independent of ApparentHorizons.

**Review by nilsvu — CHANGES_REQUESTED** [review]
Thanks for organizing these files 👍

File: src/Domain/CoordinateMaps/TimeDependent/Shape.cpp (hunk 3 above)
Comment (markscheel) [reply src/Domain/CoordinateMaps/TimeDependent/Shape.cpp:16]: Why yes it can be deleted; seems to not be used (not sure why it was there in the first place).

**Review by nilsvu — DISMISSED** [review]
Squash

**Comment by markscheel** [comment]
Squashed.  I also added (and squashed) one more commit that simply added SphericalHarmonics to Domain/CoordinateMaps/CMakeLists.txt

**Review by nilsvu — APPROVED** [review]

File: src/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt (hunk 2 above)
Comment (markscheel) [reply src/NumericalAlgorithms/SphericalHarmonics/CMakeLists.txt:31]: added Utilities

**Comment by kidder** [comment]
@wthrowe this has been squashed

**Review by wthrowe — APPROVED** [review]
