### PR TITLE
Fix bug in damped harmonic gauge

### LINKED ISSUE #4594: Evolve a BBH in damped harmonic gauge
Currently, BBHs require harmonic gauge, because starting in damped harmonic gauge at t=0 requires characteristic speed control. Once characteristic speed control is working, the BinaryBlackHole executable should start in damped harmonic gauge instead of harmonic gauge.

Depends on #4593, #4592, and #4591.

### PR DESCRIPTION
**Pull request by geoffrey4444**
## Proposed changes

Fixes a bug in the time derivative of the damped harmonic gauge source function. One term in the calculation was missing a factor of 1/lapse.

The python unit test didn't catch this because the term in question numerically was never much bigger than 1e-12, the default epsilon for `check_with_random_values`. I increased the maximum magnitude of the random inputs by a factor of 10 to catch such bugs in the future, and I verified that after this change, the unit test would fail if the missing factor of 1/lapse were removed once again.

Fixes #4594.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

File: src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.cpp [hunk 1]
```diff
@@ -390,7 +390,7 @@ void damped_harmonic_impl(
   //  0.5 * n^a n^b Pi_{ab}
   //  0.5 * n^a n^b Phi_{iab}
   // so we reuse that work by taking them as arguments.
-  get<0>(d4_muS_over_lapse) *= -get(mu_S);
+  get<0>(d4_muS_over_lapse) *= -get(mu_S) * get(one_over_lapse);
```
Comment (knelli2) [inline src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.cpp:393]: Don't multiply by one over lapse here. I think you can just remove the multiplication of lapse on line 367 above.

**Review by knelli2 — CHANGES_REQUESTED** [review]

**Review by nilsdeppe — COMMENTED** [review]
I have no additional comments. Nice catch! :D

File: src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.cpp (hunk 1 above)
Comment (nilsvu) [reply src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.cpp:393]: That would be consistent with the comment in line 361. But the value is used in line 372, so that needs a factor of the lapse then.

**Review by nilsvu — DISMISSED** [review]

File: src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.cpp (hunk 1 above)
Comment (knelli2) [reply src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.cpp:393]: Oops missed that. @geoffrey4444 could you fix the comment on line 361 then?

Comment (geoffrey4444) [reply src/Evolution/Systems/GeneralizedHarmonic/GaugeSourceFunctions/DampedHarmonic.cpp:393]: The equation in that comment was correct but not what was actually being computed, so I updated it to reflect that here we're computing d_t lapse, not dt_lapse / lapse. Squashed

**Review by nilsvu — APPROVED** [review]

**Review by knelli2 — APPROVED** [review]
