### PR TITLE
Subcell TCI improvements, step 1

### LINKED ISSUE #3587: Incorrect check on subcell tilde-D in ValenciaDivClean TCI
`src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.cpp`:
```c++
  // require: tilde_d/sqrt{gamma} >= 0.0 (or some positive user-specified value)
  if (min(get(tilde_d) / get(sqrt_det_spatial_metric)) <
          tci_options.minimum_rest_mass_density_times_lorentz_factor or
      min(get(subcell_tilde_d)) <
          tci_options.minimum_rest_mass_density_times_lorentz_factor) {
    return true;
  }
```
Note the lack of a metric factor in the second check.

It is not immediately obvious how to fix this, and I don't think it is causing the prpoblem I am currently debugging, so I'm just filing an issue.

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

Change the RDMP TCI to be part of the system-specific TCI. This allows removing the `inactive` variables, reducing memory usage, and also reduces the number of project operations necessary for the TCI. While only about a 15% reduction in runtime, the memory usage reduction will be important for GH+GRMHD, and since there are a lot more variables to project in that case, I suspect also in the runtime. Having said that, GH+GRMHD also has a more expensive RHS, so I'm not sure how big the runtime difference will be.

Only the "fixup" commits are new. I've split what ultimately needs to be one giant commit into several to make review easier.

Fixes #3587 

Depends on:
- [x] #4000 Actually needed
- [x] #4002 only in the sense of that it's included. Could be dropped.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

File: src/Evolution/DgSubcell/Actions/Initialize.hpp [hunk 1]
```diff
@@ -136,46 +132,41 @@ struct Initialize {
...
-    db::mutate_apply<tmpl::list<subcell::Tags::Mesh<Dim>, Tags::ActiveGrid,
-                                Tags::DidRollback,
-                                Tags::Inactive<typename System::variables_tag>,
-                                typename System::variables_tag>,
-                     typename TciMutator::argument_tags>(
+    db::mutate_apply<
+        tmpl::list<subcell::Tags::Mesh<Dim>, Tags::ActiveGrid,
+                   Tags::DidRollback, typename System::variables_tag,
+                   subcell::Tags::DataForRdmpTci>,
+        typename TciMutator::argument_tags>(
```
Comment (yoonso0-0) [inline src/Evolution/DgSubcell/Actions/Initialize.hpp:139]: Can we rename the template parameter `TciMutator` to something like `InitialDataTciMutator`? Just to make a nonzero difference from TCI codes for DG or FD grid.

File: src/Evolution/DgSubcell/Actions/TciAndRollback.hpp [hunk 2]
```diff
@@ -108,159 +105,132 @@ struct TciAndRollback {
...
+              tmpl::index_of<
+                  ActionList,
+                  ::Actions::Label<evolution::dg::subcell::Actions::Labels::
+                                       BeginSubcellAfterDgRollback>>::value +
+                  1};
+    }  // (cell_is_not_on_external_boundary or
+       // subcell_enabled_at_external_boundary) and cell_is_troubled
+
     // The unlimited DG solver has passed, so we can remove the current neighbor
     // data.
```
Comment (yoonso0-0) [inline src/Evolution/DgSubcell/Actions/TciAndRollback.hpp]: Would you mention about updating RDMP data here as well as removing neighbor data?

File: src/Evolution/Systems/Burgers/Subcell/TciOnDgGrid.cpp [hunk 3]
```diff
@@ -3,11 +3,39 @@
...
+  // Don't use buffer since we have only one memory allocation right now (until
+  // persson_tci can use a buffer)
+  const Scalar<DataVector> subcell_u{::evolution::dg::subcell::fd::project(
+      get(dg_u), dg_mesh, subcell_mesh.extents())};
+
+  using std::max;
+  using std::min;
+  evolution::dg::subcell::RdmpTciData rdmp_tci_data{
+      {max(max(get(dg_u)), max(get(subcell_u)))},
+      {min(min(get(dg_u)), min(get(subcell_u)))}};
```
Comment (yoonso0-0) [inline src/Evolution/Systems/Burgers/Subcell/TciOnDgGrid.cpp:30]: include "Tensor.hpp"?

File: src/Evolution/Systems/Burgers/Subcell/TciOnDgGrid.hpp [hunk 4]
```diff
@@ -26,9 +31,17 @@ namespace Burgers::subcell {
 struct TciOnDgGrid {
```
Comment (yoonso0-0) [inline src/Evolution/Systems/Burgers/Subcell/TciOnDgGrid.hpp:31]: Mention applying RDMP TCI (and which variables it's applied to) in documentation, here and other `TciOnDgGrid.cpp`s.

File: src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.hpp [hunk 5]
```diff
@@ -23,22 +27,20 @@ namespace Burgers::subcell {
  * solution to check if the corresponding DG solution is admissible.
  *
  * Applies the Persson TCI to \f$U\f$ on the DG grid.
```
Comment (yoonso0-0) [inline src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.hpp]: Mention RDMP TCI in doc (same, here and other `TciOnFdGrid.hpp`s)

File: src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp [hunk 6]
```diff
@@ -3,11 +3,38 @@
...
+    const evolution::dg::subcell::SubcellOptions& subcell_options,
+    const double persson_exponent) {
+  const Scalar<DataVector> dg_u{evolution::dg::subcell::fd::reconstruct(
+      get(subcell_u), dg_mesh, subcell_mesh.extents(),
+      evolution::dg::subcell::fd::ReconstructionMethod::DimByDim)};
+
+  using std::max;
+  using std::min;
+  const evolution::dg::subcell::RdmpTciData rdmp_data_for_tci{
+      {max(max(get(dg_u)), max(get(subcell_u)))},
```
Comment (yoonso0-0) [inline src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp:29]: include Tensor.hpp

File: src/Evolution/DgSubcell/Actions/TciAndSwitchToDg.hpp [hunk 7]
```diff
@@ -172,40 +170,14 @@ struct TciAndSwitchToDg {
...
-    // If the RDMP TCI marked the candidate as acceptable, check with the
-    // user-specified TCI, since that could be stricter. We pass in the Persson
-    // exponent with one added in order to avoid flip-flopping between DG and
-    // subcell. That is, `persson_exponent+1.0` is stricter than
-    // `persson_exponent`.
-    if (not cell_is_troubled) {
-      cell_is_troubled = db::mutate_apply<TciMutator>(
-          make_not_null(&box), subcell_options.persson_exponent() + 1.0);
-    }
+    std::tuple<bool, evolution::dg::subcell::RdmpTciData> result =
```
Comment (yoonso0-0) [inline src/Evolution/DgSubcell/Actions/TciAndSwitchToDg.hpp]: [nitpick] use `result` -> `tci_result` for clarity?

File: src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp [hunk 8]
```diff
@@ -3,11 +3,38 @@
...
+  const bool cell_is_troubled = evolution::dg::subcell::rdmp_tci(
+      rdmp_data_for_tci.max_variables_values,
+      rdmp_data_for_tci.min_variables_values,
+      past_rdmp_tci_data.max_variables_values,
+      past_rdmp_tci_data.min_variables_values, subcell_options.rdmp_delta0(),
+      subcell_options.rdmp_epsilon());
+
+  return {cell_is_troubled or ::evolution::dg::subcell::persson_tci(
+                                  dg_u, dg_mesh, persson_exponent),
+          {{max(get(subcell_u))}, {min(get(subcell_u))}}};
```
Comment (yoonso0-0) [inline src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp:41]: Q. Why do we not return with `std::move()` here, as `TciOnDgGrid.cpp`?

File: src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp [hunk 9]
```diff
@@ -3,11 +3,38 @@
...
-                        const double persson_exponent) {
-  return ::evolution::dg::subcell::persson_tci(dg_u, dg_mesh, persson_exponent);
+std::tuple<bool, evolution::dg::subcell::RdmpTciData> TciOnFdGrid::apply(
+    const Scalar<DataVector>& subcell_u, const Mesh<1>& dg_mesh,
+    const Mesh<1>& subcell_mesh,
+    const evolution::dg::subcell::RdmpTciData& past_rdmp_tci_data,
+    const evolution::dg::subcell::SubcellOptions& subcell_options,
+    const double persson_exponent) {
+  const Scalar<DataVector> dg_u{evolution::dg::subcell::fd::reconstruct(
+      get(subcell_u), dg_mesh, subcell_mesh.extents(),
```
Comment (yoonso0-0) [inline src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp:23]: include "Evolution/DgSubcell/Mesh.hpp"?

File: src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp [hunk 10]
```diff
@@ -3,11 +3,38 @@
...
+      evolution::dg::subcell::fd::ReconstructionMethod::DimByDim)};
```
Comment (yoonso0-0) [inline src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp:24]: Are we hard coding this option to be `DimByDim`, not using `subcell_options.reconstruction_method()`? (applies to all the other `TciOnFdGrid.cpp` in this PR)

File: src/Evolution/Systems/Burgers/FiniteDifference/ReconstructWork.tpp [hunk 11]
```diff
@@ -66,6 +66,11 @@ void reconstruct_work(
            "got "
                << neighbors_in_direction.size() << " in direction "
                << direction);
+    ASSERT(not neighbor_data
```
Comment (yoonso0-0) [inline src/Evolution/Systems/Burgers/FiniteDifference/ReconstructWork.tpp]: I don't see this ASSERT from `ReconstructWork.tpp` of other evolution systems, but seems like a good thing to check. Can you add this to also GrMhd, NE, and ScalarAdvection? :)

File: tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_TciOnFdGrid.cpp [hunk 12]
```diff
@@ -3,48 +3,86 @@
...
-enum class TestThis { AllGood, PerssonU };
+enum class TestThis { AllGood, PerssonU, RdmpU };
 
 template <size_t Dim>
 void test(const TestThis& test_this) {
   // create DG mesh
   const Mesh<Dim> dg_mesh{5, Spectral::Basis::Legendre,
                           Spectral::Quadrature::GaussLobatto};
+  const Mesh<Dim> subcell_mesh = evolution::dg::subcell::fd::mesh(dg_mesh);
   // create scalar field U on the DG mesh
```
Comment (yoonso0-0) [inline tests/Unit/Evolution/Systems/ScalarAdvection/Subcell/Test_TciOnFdGrid.cpp]: `DG mesh` -> `Subcell mesh`.

Seems like this is my fault months ago..

File: src/Evolution/Systems/NewtonianEuler/Subcell/TciOnDgGrid.hpp [hunk 13]
```diff
@@ -63,18 +67,24 @@ class TciOnDgGrid {
   using return_tags = tmpl::list<::Tags::Variables<
```
Comment (yoonso0-0) [inline src/Evolution/Systems/NewtonianEuler/Subcell/TciOnDgGrid.hpp:68]: Update documentation with
- mention RDMP TCI for mass density and energy density
- runs the Persson TCI on the mass density and energy density

File: src/Evolution/Systems/Burgers/Subcell/InitialDataTci.hpp [hunk 14]
```diff
@@ -26,17 +32,26 @@ namespace Burgers::subcell {
...
-  static bool apply(
+  static std::tuple<bool, evolution::dg::subcell::RdmpTciData> apply(
       const Variables<tmpl::list<Burgers::Tags::U>>& dg_vars,
-      const Variables<tmpl::list<Inactive<Burgers::Tags::U>>>& subcell_vars,
       double rdmp_delta0, double rdmp_epsilon, double persson_exponent,
-      const Mesh<1>& dg_mesh);
+      const Mesh<1>& dg_mesh, const Mesh<1>& subcell_mesh);
+};
+
+/// \brief Sets the RDMP data.
```
Comment (yoonso0-0) [inline src/Evolution/Systems/Burgers/Subcell/InitialDataTci.hpp]: "Sets the initial RDMP data", or "RDMP data at t=0"?
(here and other `InitialDataTci.hpp`s)

File: src/Evolution/Systems/Burgers/Subcell/InitialDataTci.cpp [hunk 15]
```diff
@@ -3,20 +3,43 @@
...
+      {min(min(get(dg_u)), min(get(subcell_u)))}};
+
+  return {evolution::dg::subcell::two_mesh_rdmp_tci(
+              dg_vars, subcell_vars, rdmp_delta0, rdmp_epsilon) or
+              evolution::dg::subcell::persson_tci(
+                  get<Burgers::Tags::U>(dg_vars), dg_mesh, persson_exponent),
+          std::move(rdmp_tci_data)};
+}
+
+void SetInitialRdmpData::apply(
```
Comment (yoonso0-0) [inline src/Evolution/Systems/Burgers/Subcell/InitialDataTci.cpp:38]: include "Utilities/GSL.hpp"

File: src/Evolution/Systems/Burgers/Subcell/InitialDataTci.hpp [hunk 16]
```diff
@@ -26,17 +32,26 @@ namespace Burgers::subcell {
...
+///
+/// Used on the subcells after the TCI marked the DG solution as inadmissible.
+struct SetInitialRdmpData {
```
Comment (yoonso0-0) [inline src/Evolution/Systems/Burgers/Subcell/InitialDataTci.hpp:47]: Q. Is the effective action of this struct is replacing the RDMP TCI data set by `DgInitialDataTci` to another one only on subcell grid? What I see from here is that `DgInitialDataTci` puts the RDMP TCI data

```
{max(max(get(dg_u)), max(get(subcell_u)))},
      {min(min(get(dg_u)), min(get(subcell_u)))}
```
in the initialization phase, and if the cell is troubled, `SetInitialRdmpData` changes it to 
```
{max(get(subcell_u))}, {min(get(subcell_u))}
```
in databox.

File: tests/Unit/Evolution/Systems/Burgers/Subcell/Test_InitialDataTci.cpp [hunk 17]
```diff
@@ -38,33 +31,71 @@ SPECTRE_TEST_CASE("Unit.Evolution.Systems.Burgers.Subcell.InitialDataTci",
...
     INFO("Two mesh RDMP fails");
-    // set subcell_vars to be smooth but quite different from dg_vars
-    const InactiveVars subcell_vars{number_of_subcell_grid_points, 2.0};
-    CHECK(Burgers::subcell::DgInitialDataTci::apply(dg_vars, subcell_vars,
-                                                    rdmp_delta0, rdmp_epsilon,
-                                                    persson_exponent, dg_mesh));
+    // Test that the 2-mesh RDMP fails be setting an absurdly small epsilon
+    // and delta_0 tolerance.
+    get(get<Burgers::Tags::U>(dg_vars))[dg_mesh.number_of_grid_points() / 2] *=
+        1.0 + std::numeric_limits<double>::epsilon() * 2.0;
```
Comment (yoonso0-0) [inline tests/Unit/Evolution/Systems/Burgers/Subcell/Test_InitialDataTci.cpp:62]: Q. Is there any special reason for using epsilon limit for this line?

File: src/Evolution/Systems/NewtonianEuler/Subcell/InitialDataTci.hpp [hunk 18]
```diff
@@ -33,20 +36,39 @@ struct DgInitialDataTci {
...
-  template <typename Tag>
-  using Inactive = evolution::dg::subcell::Tags::Inactive<Tag>;
 
  public:
-  using argument_tags = tmpl::list<domain::Tags::Mesh<Dim>, Pressure>;
+  using argument_tags = tmpl::list<domain::Tags::Mesh<Dim>,
+                                   evolution::dg::subcell::Tags::Mesh<Dim>>;
 
-  static bool apply(
+  static std::tuple<bool, evolution::dg::subcell::RdmpTciData> apply(
```
Comment (yoonso0-0) [inline src/Evolution/Systems/NewtonianEuler/Subcell/InitialDataTci.hpp:44]: Update doc `mass density and pressure` -> `mass density and energy density`

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.cpp [hunk 19]
```diff
@@ -37,29 +41,80 @@ bool TciOnDgGrid<RecoveryScheme>::apply(
...
+      std::vector{min(min(get(subcell_tilde_d)), min(get(tilde_d))),
+                  min(min(get(subcell_tilde_tau)), min(get(tilde_tau))),
+                  min(min(get(subcell_mag_tilde_b)), min(get(mag_tilde_b)))};
+
+  const double average_sqrt_det_spatial_metric =
+      l1Norm(get(sqrt_det_spatial_metric));
+
+  // require: tilde_d/sqrt{gamma} >= 0.0 (or some positive user-specified
+  // value)
+  if (min(get(tilde_d)) / average_sqrt_det_spatial_metric <
```
Comment (yoonso0-0) [inline src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.cpp:100]: [nitpick] Please add `average` of sqrt gamma to the comment above, and [\nitpick] mention average operation in the documentation of TCI steps.

Q. Why we changed this check from pointwise division by `sqrt_det_spatial_metric` to by the average of it?

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp [hunk 20]
```diff
@@ -9,29 +9,111 @@
...
+  const size_t num_dg_pts = dg_mesh.number_of_grid_points();
+  const size_t num_subcell_pts = subcell_mesh.number_of_grid_points();
+  DataVector temp_buffer{num_subcell_pts + 3 * num_dg_pts};
+  size_t offset_into_temp_buffer = 0;
+  const auto assign_data =
+      [&temp_buffer, &offset_into_temp_buffer](
+          const gsl::not_null<Scalar<DataVector>*> to_assign,
+          const size_t size) {
+        get(*to_assign)
+            .set_data_ref(temp_buffer.data() + offset_into_temp_buffer, size);
```
Comment (yoonso0-0) [inline src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp:37]: Q. What is this syntax? Is it a method in `DataVector`?

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp [hunk 21]
```diff
@@ -9,29 +9,111 @@
...
+      rdmp_tci_data_for_check.max_variables_values,
+      rdmp_tci_data_for_check.min_variables_values,
+      past_rdmp_tci_data.max_variables_values,
+      past_rdmp_tci_data.min_variables_values, subcell_options.rdmp_delta0(),
+      subcell_options.rdmp_epsilon());
+
   if (tci_options.magnetic_field_cutoff.has_value() and not cell_is_troubled) {
-    const Scalar<DataVector> tilde_b_magnitude = magnitude(tilde_b);
-    cell_is_troubled = (max(get(tilde_b_magnitude)) >
+    cell_is_troubled = (max(get(dg_mag_tilde_b)) >
```
Comment (yoonso0-0) [inline src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp:111]: Q. Why cell is marked troubled if magnetic field is stronger than some threshold?

File: tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnFdGrid.cpp [hunk 22]
```diff
@@ -22,22 +22,20 @@
...
-
 enum class TestThis {
   AllGood,
-  SmallDensityDg,
   SmallDensitySubcell,
-  SmallPressureDg,
   SmallPressureSubcell,
   PerssonDensity,
-  PerssonPressure
+  PerssonPressure,
```
Comment (yoonso0-0) [inline tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnFdGrid.cpp]: -> `PerssonEnergyDensity`, and please change pressure-related codes in this file to energy density

File: tests/Unit/Evolution/DgSubcell/Actions/Test_TciAndSwitchToDg.cpp [hunk 23]
```diff
@@ -276,7 +273,7 @@ void test_impl(
   CHECK_FALSE(ActionTesting::get_databox_tag<
               comp, evolution::dg::subcell::Tags::DidRollback>(runner, 0));
 
-  if (rdmp_fails or avoid_tci) {
+  if (avoid_tci) {
     // If the RDMP decided the cell is troubled, we shouldn't be checking the
```
Comment (yoonso0-0) [inline tests/Unit/Evolution/DgSubcell/Actions/Test_TciAndSwitchToDg.cpp]: Remove this comment?

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.cpp [hunk 24]
```diff
@@ -10,63 +10,95 @@
...
+          std::move(std::get<1>(result))};
+}
+
+void SetInitialRdmpData::apply(
+    const gsl::not_null<evolution::dg::subcell::RdmpTciData*> rdmp_tci_data,
+    const Scalar<DataVector>& subcell_tilde_d,
+    const Scalar<DataVector>& subcell_tilde_tau,
+    const tnsr::I<DataVector, 3, Frame::Inertial>& subcell_tilde_b,
+    const evolution::dg::subcell::ActiveGrid active_grid) {
+  if (active_grid == evolution::dg::subcell::ActiveGrid::Subcell) {
```
Comment (yoonso0-0) [inline src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.cpp:93]: include "Evolution/DgSubcell/ActiveGrid.hpp"

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.hpp [hunk 25]
```diff
@@ -49,25 +54,35 @@ bool initial_data_tci_work(
  *   on the DG grid is greater than `tci_options.magnetic_field_cutoff`.
  */
```
Comment (yoonso0-0) [inline src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.hpp:55]: For the documentation describing checks starting with dash(-):
* first one  : LGTM
* second one : move this one to the last step? (checking two mesh rdmp happens after `initial_data_tci_work()` called)
* third one  : mention "on DG grid" for tildeD and tildeTau
* fourth one : same. "~ to the magnitude of \tildeB on DG grid"

File: src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/InitialDataTci.hpp [hunk 26]
```diff
@@ -40,33 +42,20 @@ namespace grmhd::GhValenciaDivClean::subcell {
  *   on the DG grid is greater than `tci_options.magnetic_field_cutoff`.
```
Comment (yoonso0-0) [inline src/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/InitialDataTci.hpp:41]: If you fix the doc of `DgInitialDataTci` of ValenciaDivClean, please update this doc as well! :)

File: tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnDgGrid.cpp [hunk 27]
```diff
@@ -178,16 +195,14 @@ void test(const TestThis test_this) {
           }
         });
   } else if (test_this == TestThis::NegativeTildeDSubcell) {
-    db::mutate<evolution::dg::subcell::Tags::Inactive<
-        grmhd::ValenciaDivClean::Tags::TildeD>>(
+    db::mutate<grmhd::ValenciaDivClean::Tags::TildeD>(
         make_not_null(&box), [point_to_change](const auto tilde_d_ptr) {
-          get(*tilde_d_ptr)[point_to_change] = -1.0e-20;
+          get(*tilde_d_ptr)[point_to_change] = 1.0e-200;
```
Comment (yoonso0-0) [inline tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnDgGrid.cpp:200]: Q. Why do we set tildeD to be a very small positive value here, not a negative value?

File: tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_InitialDataTci.cpp [hunk 28]
```diff
@@ -89,56 +134,52 @@ SPECTRE_TEST_CASE(
...
-    const InactiveConsVars subcell_vars{subcell_mesh.number_of_grid_points(),
-                                        1.0};
     get(get<grmhd::ValenciaDivClean::Tags::TildeTau>(
         dg_vars))[dg_mesh.number_of_grid_points() / 2] += 2.0e10;
-    CHECK(grmhd::GhValenciaDivClean::subcell::DgInitialDataTci::apply(
-        dg_vars, subcell_vars, 1.0e100, epsilon, exponent, dg_mesh,
-        tci_options));
+    const auto result =
+        grmhd::GhValenciaDivClean::subcell::DgInitialDataTci::apply(
+            dg_vars, 1.0e100, epsilon, 1.0, dg_mesh, subcell_mesh, tci_options);
```
Comment (yoonso0-0) [inline tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_InitialDataTci.cpp]: use `exponent` in the slot of `1.0` (not sure why it changed)

**Review by yoonso0-0 — COMMENTED** [review]
Mostly updating docs in sync with modified functionality and small fixes on tests.

File: src/Evolution/DgSubcell/Actions/Initialize.hpp (hunk 1 above)
Comment (nilsdeppe) [reply src/Evolution/DgSubcell/Actions/Initialize.hpp:139]: Sure, please remind me to add a commit once everything else has been approved. Renames can make rebasing and squashing fairly annoying experience, so I'd like to defer that until the end

File: src/Evolution/Systems/Burgers/Subcell/InitialDataTci.hpp (hunk 16 above)
Comment (nilsdeppe) [reply src/Evolution/Systems/Burgers/Subcell/InitialDataTci.hpp:47]: Yes, that's right. Once we switch to starting on the FD grid and then switching to DG this won't be an issue, but right now we can't use the projected FD solution for the RDMP

File: src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp (hunk 10 above)
Comment (nilsdeppe) [reply src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp:24]: That's the reconstruction method for the conservative solution transfer. I want the TCIs to be as fast as possible

File: src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp (hunk 8 above)
Comment (nilsdeppe) [reply src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp:41]: because here we're only returning the subcell extrema, not the DG and subcell extrema. If we returned the DG extrema too then we'd be using the oscillatory max/min if there's a shock in the domain

File: tests/Unit/Evolution/Systems/Burgers/Subcell/Test_InitialDataTci.cpp (hunk 17 above)
Comment (nilsdeppe) [reply tests/Unit/Evolution/Systems/Burgers/Subcell/Test_InitialDataTci.cpp:62]: I can't add a smaller number to 1 in floating point. I don't really understand your question, sorry. The goal is to test that RDMP fails if we set ridiculously tight tolerances

File: src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp (hunk 9 above)
Comment (nilsdeppe) [reply src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp:23]: Sorry, why? That header is used for computing the subcell mesh from the DG mesh only

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.hpp (hunk 25 above)
Comment (nilsdeppe) [reply src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.hpp:55]: The Persson TCI is only defined on the DG grid, you can't apply it on the FD grid, so it seems to me it would be more confusing to specify it. What do you think?

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp (hunk 20 above)
Comment (nilsdeppe) [reply src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp:37]: `set_data_ref` is a member function of `DataVector` that sets the pointer of the internal data to somewhere else

File: tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnFdGrid.cpp (hunk 22 above)
Comment (nilsdeppe) [reply tests/Unit/Evolution/Systems/NewtonianEuler/Subcell/Test_TciOnFdGrid.cpp]: I'll update the enum. The rest of the code is fine since setting the prims gives better control of minimum pressure, etc.

**Review by nilsdeppe — COMMENTED** [review]
Rebased and pushed fixups (to the fixups). Hopefully I got all the docs changes, but please double check!

File: src/Evolution/DgSubcell/Actions/Initialize.hpp (hunk 1 above)
Comment (yoonso0-0) [reply src/Evolution/DgSubcell/Actions/Initialize.hpp:139]: Yup, will try my best to not forget :)

File: src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp (hunk 9 above)
Comment (yoonso0-0) [reply src/Evolution/Systems/Burgers/Subcell/TciOnFdGrid.cpp:23]: Never mind about DgSubcell/Mesh :joy: 
"NumericalAlgorithms/Spectral/Mesh.hpp" was what I tried to say for `subcell_mesh.extents()` (please squash if you agree and make this change)

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.hpp (hunk 25 above)
Comment (yoonso0-0) [reply src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.hpp:55]: Yep, agree

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp [hunk 29]
```diff
@@ -42,6 +42,9 @@ namespace grmhd::ValenciaDivClean::subcell {
  *   `min(tilde_tau)` is less than `tci_options.minimum_tilde_tau` then the we
  *   remain on FD.
  * - apply the Persson TCI to \f$\tilde{D}\f$ and \f$\tilde{\tau}\f$
+ * - apply the RDMP TCI to `TildeD`, `TildeTau` and `TildeB`.
```
Comment (yoonso0-0) [inline src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.hpp]: magnitude of `TildeB`

File: tests/Unit/Evolution/Systems/Burgers/Subcell/Test_InitialDataTci.cpp (hunk 17 above)
Comment (yoonso0-0) [reply tests/Unit/Evolution/Systems/Burgers/Subcell/Test_InitialDataTci.cpp:62]: Oh I meant wondering if we could've used some ordinary value like `1.0`. It's really casual question

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.cpp (hunk 24 above)
Comment (yoonso0-0) [reply src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/InitialDataTci.cpp:93]: Ping this

File: tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnDgGrid.cpp (hunk 27 above)
Comment (yoonso0-0) [reply tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnDgGrid.cpp:200]: Ping this?

File: tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_InitialDataTci.cpp (hunk 28 above)
Comment (yoonso0-0) [reply tests/Unit/Evolution/Systems/GrMhd/GhValenciaDivClean/Subcell/Test_InitialDataTci.cpp]: aaand ping this as well

**Comment by yoonso0-0** [comment]
Checked all the fixup-fixups. Please squash the fixup-fixups or any other minor changes into each fixups! :+1: 


* Reminder) rename the template parameter `TciMutator` in `Evolution/DgSubcell/Actions/Initialize.hpp` after review is done.

File: tests/Unit/Evolution/Systems/Burgers/Subcell/Test_InitialDataTci.cpp (hunk 17 above)
Comment (nilsdeppe) [reply tests/Unit/Evolution/Systems/Burgers/Subcell/Test_InitialDataTci.cpp:62]: Oh, probably not? It'll depend on whether the checks are `<` or `<=` and some IEEE floating point rules...

File: tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnDgGrid.cpp (hunk 27 above)
Comment (nilsdeppe) [reply tests/Unit/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/Test_TciOnDgGrid.cpp:200]: Because we project from the DG grid to the subcell grid and want to keep the DG grid positive but have the projected subcell grid have a negative value

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.cpp (hunk 19 above)
Comment (nilsdeppe) [reply src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnDgGrid.cpp:100]: Sorry, forgot to answer your question. Using the average means we can divide out the spatial metric on both the subcells and the DG grid. This fixes #3587

File: src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp (hunk 21 above)
Comment (nilsdeppe) [reply src/Evolution/Systems/GrMhd/ValenciaDivClean/Subcell/TciOnFdGrid.cpp:111]: It's only checking the Persson TCI if the magnetic field is large. This is because you lose spectral convergence as a solution goes to zero and so then you end up refining everywhere

**Review by yoonso0-0 — DISMISSED** [review]

**Review by kidder — DISMISSED** [review]

**Review by kidder — APPROVED** [review]
