### PR TITLE
Fix NumPy API working for multiple cpp files, also refactor Christoffel to use Pypp. 

### LINKED ISSUE #606: Pypp doesn't work when used in more than one file
# Bug reports:

When adding the Pypp functionality to some of the PointwiseFunction tests I started getting SEGFAULTS from the NumPy-API. Whatever way NumPy works internally means that it doesn't work across multiple cpp files,  we've to do a bit more work to get it working. This is documented in their API so I'm working on implementing the fix now.

### PR DESCRIPTION
**Pull request by osheamonn**
## Proposed changes

The NumPy API didn't work when used in several cpp files. The solution was to refactor where the `import_numpy` call was happening into a cpp file and add some macros which are used by the python internals. To make sure it now works with multiple cpp files I refactored the Christoffel tests. 

Fixes #606 

### Types of changes:

- [x] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- Code has documentation and unit tests
- Private member variables have a trailing underscore
- Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- File lists in CMake are alphabetical
- Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- Mark objects `const` whenever possible
- Almost always `auto`, except with expression templates, i.e. `DataVector`
- All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- Prefix commits addressing PR requests with `fixup`. These commits are flagged
  by Travis so we do not accidentally merge them.
- Include what you use, prefer forward declarations in hpp files.
- Explicitly make numbers floating point, e.g. `2.` or `2.0` over `2`
- Use `Tensor`'s non-member get if the indices are constant expressions, e.g.
  `get<1>(tensor)`

### CODE REVIEW

**Review by kidder — DISMISSED** [review]

**Review by nilsdeppe — APPROVED** [review]

File: tests/Unit/Pypp/SetupLocalPythonEnvironment.cpp [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+
+#include <codecvt>
+#include <string>
+
+#ifndef PY_ARRAY_UNIQUE_SYMBOL
+#define PY_ARRAY_UNIQUE_SYMBOL SPECTRE_PY_API
+#endif
+
+#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
+#include <numpy/arrayobject.h>
```
Comment (nilsdeppe) [inline tests/Unit/Pypp/SetupLocalPythonEnvironment.cpp]: My guess is you need `#include <Python.h>` to get it to build on macOS.

**Review by nilsdeppe — CHANGES_REQUESTED** [review]
Just `// NOLINT` the clang-tidy warning, it's safe because the function name is generated for the file and library name.

Please squash the fixup right away :)

**Review by nilsdeppe — APPROVED** [review]

**Comment by nilsdeppe** [comment]
@kidder can you re-approve?

**Review by kidder — APPROVED** [review]
