### PR TITLE
Reinterpolate to all elements for new target points (fix BBH deadlocks)

### LINKED ISSUE #5487: Fix BBH evolution deadlocks
BBH evolutions sometimes deadlock. Why? How to fix?

### PR DESCRIPTION
**Pull request by knelli2**
## Proposed changes

This is believed to be what was causing a lot of deadlocks in BBH simulations. Between horizon find iterations, a target point of the new horizon surface would move from one element on one core, to a different element on a second core. Because of some implicit assumption made about message ordering (which wasn't consciously made, but just overlooked), this target point never got interpolated to. Thus the target was waiting for the interpolated data from this point while the interpolator was waiting for its next set of points and a deadlock happened.

Fixes #5487.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

File: src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp [hunk 1]
```diff
@@ -80,12 +80,32 @@ struct ReceivePoints {
...
-                  std::move(block_logical_coords)}));
+          // Add the new target interpolation points at this temporal_id. If we
+          // already have some target points at this temporal_id, we overwrite
+          // them with the new target points. This is because the interpolation
+          // has already finished for the previous set of target points if we
+          // are receiving new target points. This core must not have had any
+          // elements that contained any of the previous target points. However,
+          // these elements may now contain some new target points.
+          if (vars_infos.count(temporal_id) == 0) {
+            vars_infos.emplace(std::make_pair(
```
Comment (wthrowe) [inline src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp]: `vars_infos.insert_or_assign`?  (Haven't checked exactly what type this is, but most similar classes have it.)

File: src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp [hunk 2]
```diff
@@ -80,12 +80,32 @@ struct ReceivePoints {
...
-              intrp::Vars::Info<VolumeDim, typename InterpolationTargetTag::
-                                               vars_to_interpolate_to_target>{
-                  std::move(block_logical_coords)}));
+          // Add the new target interpolation points at this temporal_id. If we
+          // already have some target points at this temporal_id, we overwrite
+          // them with the new target points. This is because the interpolation
+          // has already finished for the previous set of target points if we
+          // are receiving new target points. This core must not have had any
+          // elements that contained any of the previous target points. However,
+          // these elements may now contain some new target points.
```
Comment (wthrowe) [inline src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp]: Could this happen in the opposite order?  We receive the second set of points (which need interpolation) first, and then overwrite them with the first set (which didn't)?

**Review by wthrowe — CHANGES_REQUESTED** [review]

File: src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp (hunk 1 above)
Comment (knelli2) [reply src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp]: Hmm let me think if we need to keep around the other members of the `Info` class when we receive a new set of points. I'm thinking no.

File: src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp (hunk 2 above)
Comment (knelli2) [reply src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp]: Yes, I believe that could technically happen in the opposite order. I wonder if we should somehow send along the horizon find iteration so we know which set of points is the correct one (always the higher iteration)

**Comment by knelli2** [comment]
@wthrowe Pushed a fixup that covers the scenario of receiving points in the wrong order.

**Comment by wthrowe** [comment]
That should do it.  Go ahead and squash.

File: src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp [hunk 3]
```diff
@@ -80,12 +89,34 @@ struct ReceivePoints {
...
+          // and we definitely didn't have any of the new target points in our
+          // element by the fact that we have already received the next
+          // iteration of points.
+          //
+          // Whenever we overwrite the target points, we also empty the
+          // `interpolation_is_done_for_these_elements` (by virtue of a default
+          // constructed `intrp::Vars::Info`) so that we always check every
+          // element for this new set of target points.
+          if (vars_infos.count(temporal_id) == 0 or
+              vars_infos.at(temporal_id).iteration < iteration) {
```
Comment (knelli2) [inline src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp:117]: Make it error if the new iteration is the same as the old iteration. This is a bug.

Comment (knelli2) [reply src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp:117]: @wthrowe Pushed a fixup for this

Comment (wthrowe) [reply src/ParallelAlgorithms/Interpolation/Actions/InterpolatorReceivePoints.hpp:117]: Looks good.

**Comment by knelli2** [comment]
@wthrowe Squashed

**Comment by AlexCarpenter46** [comment]
I've been testing this branch for a few different head on BBH's (different resolutions, enabling checkpoints and quiet/debug output) and they've all successfully reached a common horizon :). So I would say this has fixed the current deadlocks we've been encountering. These runs are on Ocean at `/home/alexcarpenter/BBH_Headon/BBH_develop_with_fix`

**Comment by nilsvu** [comment]
Hoorayyy 🙌

**Comment by nilsdeppe** [comment]
@wthrowe can you please take a look at this again?

**Comment by wthrowe** [comment]
It's waiting on @markscheel?

**Comment by nilsdeppe** [comment]
> @wthrowe Squashed

?

**Comment by knelli2** [comment]
I removed Mark because this is a pretty important bug fix that I think we should get in quickly.

**Comment by wthrowe** [comment]
If the PR author requests a review, I'm going to respect that.

**Review by wthrowe — APPROVED** [review]

**Comment by nilsdeppe** [comment]
> If the PR author requests a review, I'm going to respect that.

That doesn't mean you can't give feedback post-squash, though.
