### PR TITLE
Write volume data as rank1 dataset

### LINKED ISSUE #1141: H5 volume data storage order is wrong
HDF5 uses arrays with the last dimension varying fastest, but we vary the first dimension of points within elements fastest, so when we write data to an array it ends up shaped wrong.

For example, the z component of a non-rotated 5x5x2-point brick is (from h5py)
```
[array([[ 0.,  0.], [ 0.,  0.], [ 0.,  0.], [ 0.,  0.], [ 0.,  0.]]),
 array([[ 0.,  0.], [ 0.,  0.], [ 0.,  0.], [ 0.,  0.], [ 0.,  0.]]),
 array([[ 0.,  0.], [ 0.,  0.], [ 0.,  1.], [ 1.,  1.], [ 1.,  1.]]),
 array([[ 1.,  1.], [ 1.,  1.], [ 1.,  1.], [ 1.,  1.], [ 1.,  1.]]),
 array([[ 1.,  1.], [ 1.,  1.], [ 1.,  1.], [ 1.,  1.], [ 1.,  1.]])]
```

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

Since our data is x-varying fastest and HDF5 uses z-varying fastest there's no
benefit to using the rank-3 representations since it ends up being in the wrong
order anyway. See issue #1141.

I'll be building on this to improve IO time in a future PR. I figure getting this in as a small PR would be easiest for now.

closes #1141 

### Types of changes:

- [x] Bugfix

### Component:

- [x] Code

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by nilsvu** [comment]
Will this require changes to `GenerateXdmf.py` or other places that interpret the H5 files?

**Comment by nilsdeppe** [comment]
Not that I'm aware of. GenerateXdmf.py works fine, and I think yt cares even less than paraview :)

File: tests/Unit/IO/Test_H5.cpp [hunk 1]
```diff
@@ -469,13 +468,19 @@ SPECTRE_TEST_CASE("Unit.IO.H5.ReadData", "[Unit][IO][H5]") {
                                  h5::AccessType::ReadWrite);
   const hid_t group_id = my_group.id();
 
+  // Test writing and reading a DataVector as a rank-1 dataset
+  const DataVector rank1_data{1.0, 2.0, 3.0};
```
Comment (kidder) [inline tests/Unit/IO/Test_H5.cpp]: you shadowed two variable names below with `rank1_data` and `rank1_data_from_file`

**Review by kidder — CHANGES_REQUESTED** [review]

File: tests/Unit/IO/Test_H5.cpp (hunk 1 above)
Comment (nilsdeppe) [reply tests/Unit/IO/Test_H5.cpp]: Done :)

**Review by kidder — APPROVED** [review]

**Comment by kidder** [comment]
@wthrowe please look at

**Review by wthrowe — APPROVED** [review]

**Comment by nilsvu** [comment]
@geoffrey4444 before you end up debugging this, too: To read data into `yt` after the change in this PR you'll need to `np.reshape` the dataset to make it three-dimensional again. If you leave the array flat, `yt` will interpret it as a particle field instead.
