### PR TITLE
Fix load balancing test

### LINKED ISSUE #2754: Test_AlgorithmParallel with load-balancing outputs migration errors
The unit test `Unit.Parallel.AlgorithmParallelWithBalancing` passes, but outputs errors related to object migrations when running the testing executable like this (in the Docker container):

```
./bin/Test_AlgorithmParallel +p2 +balancer RotateLB +LBPeriod 4.0e-5 +LBDebug 3
```

The error messages look like this:

```
Function: Parallel::AlgorithmImpl<ArrayParallelComponent<TestMetavariables>, brigand::list<Parallel::PhaseActions<TestMetavariables::Phase, TestMetavariables::Phase::Initialization, brigand::list<ArrayActions::Initialize> >, Parallel::PhaseActions<TestMetavariables::Phase, TestMetavariables::Phase::PerformArrayAlgorithm, brigand::list<ArrayActions::AddIntValue10, ArrayActions::IncrementInt0, ArrayActions::RemoveInt0, ArrayActions::SendToSingleton> >, Parallel::PhaseActions<TestMetavariables::Phase, TestMetavariables::Phase::FinalizeArray, brigand::list<ArrayActions::CheckWasUnpacked> > > >::AlgorithmImpl(CkMigrateMessage *) [ParallelComponent = ArrayParallelComponent<TestMetavariables>, PhaseDepActionList = brigand::list<Parallel::PhaseActions<TestMetavariables::Phase, TestMetavariables::Phase::Initialization, brigand::list<ArrayActions::Initialize> >, Parallel::PhaseActions<TestMetavariables::Phase, TestMetavariables::Phase::PerformArrayAlgorithm, brigand::list<ArrayActions::AddIntValue10, ArrayActions::IncrementInt0, ArrayActions::RemoveInt0, ArrayActions::SendToSingleton> >, Parallel::PhaseActions<TestMetavariables::Phase, TestMetavariables::Phase::FinalizeArray, brigand::list<ArrayActions::CheckWasUnpacked> > >]
The AlgorithmImpl has been constructed with a nullptr as a CkMigrateMessage* -- most likely this indicates that a constructor is being used incorrectly, as the CkMigrateMessage* constructor should only be used by the charm framework when migrating. Constructing with a nullptr CkMigrateMessage* is dangerous and can cause segfaults.
```

Environment:
- clang-10 in the container
- occurs for both static and shared libs builds

### PR DESCRIPTION
**Pull request by moxcodes**
## Proposed changes

Resolves #2754

Also implements some changes to the test to get it to pass more consistently on CI.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

File: tests/Unit/Parallel/Test_AlgorithmParallel.cpp [hunk 1]
```diff
@@ -319,11 +332,14 @@ struct RemoveInt0 {
         [](const gsl::not_null<int*> count_actions_called) {
           ++*count_actions_called;
         });
-    const bool terminate_algorithm =
-        db::get<Tags::CountActionsCalled>(box) >= 15;
+    if (db::get<Tags::CountActionsCalled>(box) < 150) {
+      Parallel::simple_action<SingletonActions::RestartMe<ParallelComponent>>(
```
Comment (nilsvu) [inline tests/Unit/Parallel/Test_AlgorithmParallel.cpp:352]: Is it clear that this action is queued and runs _after_ the algorithm terminates from the return value below? Not sure how this interacts with inlining simple action calls.

Also, could you add a comment here to explain a bit what's going on, in particular how the `150` is chosen?

**Review by nilsvu — CHANGES_REQUESTED** [review]

File: tests/Unit/Parallel/Test_AlgorithmParallel.cpp [hunk 2]
```diff
@@ -111,6 +111,20 @@ template <class Metavariables>
 struct NodegroupParallelComponent;
 
 namespace SingletonActions {
+template <typename ComponentToRestart>
+struct RestartMe {
```
Comment (nilsvu) [inline tests/Unit/Parallel/Test_AlgorithmParallel.cpp:122]: Could you add a comment to explain the purpose of this action?

File: tests/Unit/Parallel/Test_AlgorithmParallel.cpp (hunk 1 above)
Comment (moxcodes) [reply tests/Unit/Parallel/Test_AlgorithmParallel.cpp:352]: I'm pretty sure it's guaranteed from how our simple and iterable actions work, but I confess it's not terribly obvious. My main understanding of the points we can trust are:
- two actions cannot run simultaneously
- Charm will not preempt an entry method to run another entry method.
- Charm will wait until there are no waiting entry methods to trigger QD and we proceed to the next phase (so performing this termination-restart won't accidentally cause the program to stop early)

So I think this technique is certain to work.

But, yes, I admit the choices for these changes are non-obvious, so I'll add comments.

**Comment by moxcodes** [comment]
Squashed in some extra comments.
Cheers!

**Review by kidder — APPROVED** [review]

File: tests/Unit/Parallel/Test_AlgorithmParallel.cpp (hunk 1 above)
Comment (nilsvu) [reply tests/Unit/Parallel/Test_AlgorithmParallel.cpp:352]: Ok, thanks for explaining. What I'm not entirely clear on is, what happens when the simple action call is inlined before it makes its way to Charm. I suppose at least the algorithm restart won't be inlined, so it might be safe, but @nilsdeppe could you confirm?

Comment (nilsdeppe) [reply tests/Unit/Parallel/Test_AlgorithmParallel.cpp:352]: @moxcodes points:
- correct
- my understanding of this statement is "Charm will not pause an existing entry method to run another". This is correct, there is no support for coroutines and business like that
- correct

We currently do not do any inlining of simple actions, only receive data. Beyond that, I don't know what you mean. QD does not trigger until there are no more messages or entry methods being run. That means that, even if the last action running calls an entry method, QD will not happen until that entry method is completed.

**Review by nilsvu — APPROVED** [review]

**Review by kidder — APPROVED** [review]
