### PR TITLE
Fix domain constructor

### LINKED ISSUE #269: Domain Constructor Taking identifications should be vector<pairs>
The constructor of `Domain` would be clearer if it took a `vector<pairs>` or `vector<array<vector, 2>>` to make sure the pairing between corners is more obvious and enforced at compile time.

### PR DESCRIPTION
**Pull request by mar-celine**
closes #269

### CODE REVIEW

**Comment by osheamonn** [comment]
Would it better for the used datastructure to be a std::pair? Since the size of the array for each identification will only ever be 2.

**Comment by nilsdeppe** [comment]
The only difference would be that pair would allow heterogeneous types, since that's not necessary an array is actually the better answer. If we applied your principle, every homogeneous container should be a tuple of a bunch of things of the same type.

**Comment by wthrowe** [comment]
The other difference is that an array would allow indexing at runtime, and since that's not necessary a pair is actually the better answer.

**Comment by nilsdeppe** [comment]
With the additional overhead of heterogeneous types, so no, I don't agree with you that pair is the better answer.

**Comment by nilsdeppe** [comment]
If you want compile time indexing only, then a POD would be better than a pair. A pair has a huge amount of metaprogramming associated with it, which we have absolutely no need for. Additionally, it would be possible to name the members something more useful than `first` and `second`, though I'm not sure that matters in this context.

File: src/Domain/DomainHelpers.hpp [hunk 1]
```diff
@@ -13,6 +13,8 @@
 #include "Domain/BlockNeighbor.hpp"
 #include "Utilities/ConstantExpressions.hpp"
 
+struct pair_of_sets;
```
Comment (fmahebert) [inline src/Domain/DomainHelpers.hpp]: * To me this name is strongly suggestive of a type based on `std::pair<std::set<A>, std::set<B>>`, which this is not. True, the data placed in the struct _should_ be set-like... but it is not the job of the struct's _name_ to enforce this. If we do want to enforce it, the type should be changed. Otherwise, could this be called something like `VectorPair` (if we prefer to describe what the struct _is_) or`PairOfIndentifiedPoints` / `PairOfConformingPoints` (if we prefer to describe what the struct _is for_)?
* Types are CamelCase

File: src/Domain/DomainHelpers.hpp [hunk 2]
```diff
@@ -29,9 +31,16 @@ void set_internal_boundaries(
...
-    const std::vector<std::vector<size_t>>& identifications,
+    const std::vector<pair_of_sets>& identifications,
     const std::vector<std::array<size_t, two_to_the(VolumeDim)>>&
         corners_of_all_blocks,
     gsl::not_null<std::vector<
         std::unordered_map<Direction<VolumeDim>, BlockNeighbor<VolumeDim>>>*>
         neighbors_of_all_blocks);
+
+/// struct for storing pairs of sets of corners in the global corner
+/// numbering scheme.
```
Comment (fmahebert) [inline src/Domain/DomainHelpers.hpp]: I suggest this comment either point towards `Domain.hpp` where the purpose of the struct is described, or that the comment include a brief description of what is going on (e.g. what even is a "set of corners", why might I want to pair up two of them).

File: src/Domain/DomainHelpers.hpp [hunk 3]
```diff
@@ -13,6 +13,15 @@
 #include "Domain/BlockNeighbor.hpp"
 #include "Utilities/ConstantExpressions.hpp"
 
+/// Each member in `PairOfFaces` holds the global corner ids of a block face.
+/// `PairOfFaces` is used in setting up periodic boundary conditions by
+/// identifying the two faces with each other.
+/// \requires The pair of faces must belong to a single block.
+struct PairOfFaces {
+  const std::vector<size_t> first_;
```
Comment (kidder) [inline src/Domain/DomainHelpers.hpp]: remove _s

File: src/Domain/DomainHelpers.hpp [hunk 4]
```diff
@@ -13,6 +13,15 @@
 #include "Domain/BlockNeighbor.hpp"
 #include "Utilities/ConstantExpressions.hpp"
 
+/// Each member in `PairOfFaces` holds the global corner ids of a block face.
```
Comment (kidder) [inline src/Domain/DomainHelpers.hpp]: Add this and other functions to an existing doxygen group

**Review by kidder — CHANGES_REQUESTED** [review]

**Review by kidder — APPROVED** [review]
