### PR TITLE
Fix vector comparison

### LINKED ISSUE #2978: Comparison of vectorized types is broken
This fails:
```c++
const DataVector a{1.0};
const DataVector b{1.0 + 1e-8};
CHECK(a != b);
```
I have verified that the two DataVectors are actually different (so the comparison is the problem, not the construction).  A similar problem affects Variables.  The above passes with 1e-7, so possibly the comparisons are being performed at single precision.

I first noticed this on CI and can reproduce it locally, so it doesn't seem particularly tied to one setup.

### PR DESCRIPTION
**Pull request by moxcodes**
## Proposed changes

Fixes #2978.

It turns out, there were a number of places where we mistakenly used the == in tests. I have changed all such instances to `CHECK...APPROX` as appropriate.

### Upgrade instructions

Be sure to use `==` on `Variables` and vectors only where you actually mean strict (bitwise) equality. Otherwise, use `CHECK...APPROX` in tests.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

File: src/DataStructures/VectorImpl.hpp [hunk 1]
```diff
@@ -639,15 +641,101 @@ template <typename T>
...
+                 std::is_same_v<Lhs, typename Rhs::ElementType>)> = nullptr>
+bool operator==(const Lhs& lhs, const Rhs& rhs) noexcept {
+  return blaze::equal<blaze::strict>(lhs, rhs);
+}
+
+template <
+    typename Lhs, typename Rhs,
+    Requires<(is_derived_of_vector_impl_v<Lhs> or
+              is_derived_of_vector_impl_v<
+                  Rhs>)and not(std::is_base_of_v<blaze::Computation, Lhs> or
```
Comment (moxcodes) [inline src/DataStructures/VectorImpl.hpp:664]: this terrible formatting decision is clang-format, not me. :/

File: src/DataStructures/VectorImpl.hpp [hunk 2]
```diff
@@ -26,6 +26,8 @@
 #include "Utilities/ForceInline.hpp"
 #include "Utilities/Gsl.hpp"
 #include "Utilities/MakeString.hpp"
+#include "Utilities/TypeTraits/CreateHasTypeAlias.hpp"
+#include "Utilities/TypeTraits/CreateGetTypeAliasOrDefault.hpp"
 #include "Utilities/MakeWithValue.hpp"  // IWYU pragma: keep
```
Comment (wthrowe) [inline src/DataStructures/VectorImpl.hpp]: Alphabetize.

File: src/DataStructures/VectorImpl.hpp [hunk 3]
```diff
@@ -639,15 +641,101 @@ template <typename T>
 constexpr bool is_derived_of_vector_impl_v =
     is_derived_of_vector_impl<T>::value;
 
+// impose strict equality for derived classes of VectorImpl; note that this
+// overrides intended behavior in blaze for comparison operators to use
+// approximate equality in favor of equality between containers being
+// appropriately recursive. This form primarily works by using templates to
+// ensure that our comparison operator is resolved with higher priority that the
```
Comment (wthrowe) [inline src/DataStructures/VectorImpl.hpp]: "that the" -> "than the"

File: src/DataStructures/VectorImpl.hpp [hunk 4]
```diff
@@ -639,15 +641,101 @@ template <typename T>
...
+bool operator!=(const Lhs& lhs, const Rhs& rhs) noexcept {
+  return not(lhs == rhs);
+}
+
+// Impose strict equality for any expression templates; note that
+// this overrides intended behavior in blaze for comparison
+// operators to use approximate equality in favor of equality
+// between containers being appropriately recursive. This form
+// primarily works by using templates to ensure that our
+// comparison operator is resolved with higher priority that the
```
Comment (wthrowe) [inline src/DataStructures/VectorImpl.hpp]: "that the" -> "than the"

File: src/DataStructures/VectorImpl.hpp [hunk 5]
```diff
@@ -639,15 +641,101 @@ template <typename T>
...
+template <typename Lhs, Requires<is_derived_of_vector_impl_v<Lhs>> = nullptr>
+bool operator!=(const Lhs& lhs,
+                const typename Lhs::ElementType& rhs) noexcept {
+  return not(lhs == rhs);
+}
+
+template <typename Rhs, Requires<is_derived_of_vector_impl_v<Rhs>> = nullptr>
+bool operator==(const typename Rhs::ElementType& lhs,
+                const Rhs& rhs) noexcept {
+  for (const auto& element : lhs) {
```
Comment (wthrowe) [inline src/DataStructures/VectorImpl.hpp]: This function and the one with the elements swapped both loop over `lhs`.  I don't understand this enough to know if that is correct.

Maybe just implement this as `rhs == lhs` in any case.

File: tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp [hunk 6]
```diff
@@ -77,6 +77,31 @@ void vector_test_construct_and_assign(
...
+  CHECK_FALSE(initializer_list_constructed == close);
+
+  CHECK(
+      initializer_list_constructed !=
+      (initializer_list_constructed + 1.0e-11 * initializer_list_constructed));
+  CHECK_FALSE(
+      initializer_list_constructed ==
+      (initializer_list_constructed + 1.0e-11 * initializer_list_constructed));
+  CHECK_FALSE(
+      (initializer_list_constructed - 1.0e-11 * initializer_list_constructed) ==
```
Comment (wthrowe) [inline tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp:115]: Check != for this case.

**Review by wthrowe — CHANGES_REQUESTED** [review]

**Comment by moxcodes** [comment]
fixup posted. Also added tests for the comparison operator with the single value.
Cheers!

**Comment by wthrowe** [comment]
Looks good.  Squash.

**Comment by moxcodes** [comment]
squashed.
Cheers!

**Review by wthrowe — DISMISSED** [review]

File: tests/Unit/DataStructures/Test_Variables.cpp [hunk 7]
```diff
@@ -318,6 +318,14 @@ void test_variables_math() noexcept {
 
   // Test math +, -, *, /
   const TestVariablesType vars{num_points, value_in_variables};
+  const TestVariablesType close{num_points,
+                                value_in_variables * (1.0 + 1.0e-11)};
+  CHECK(close != vars);
+  CHECK_FALSE(close == vars);
```
Comment (nilsvu) [inline tests/Unit/DataStructures/Test_Variables.cpp:324]: Add `CHECK_VARIABLES_APPROX(close, vars)` here, or just a comment that the test makes sure that `==` is exact? Else this test is pretty easy to pass (by mistake) by making `close` pretty much anything :D

File: src/DataStructures/VectorImpl.hpp [hunk 8]
```diff
@@ -30,6 +30,8 @@
 #include "Utilities/PrintHelpers.hpp"
 #include "Utilities/Requires.hpp"
 #include "Utilities/StdArrayHelpers.hpp"
+#include "Utilities/TypeTraits/CreateGetTypeAliasOrDefault.hpp"
+#include "Utilities/TypeTraits/CreateHasTypeAlias.hpp"
```
Comment (nilsvu) [inline src/DataStructures/VectorImpl.hpp]: I don't think you're actually using these

File: src/DataStructures/VectorImpl.hpp [hunk 9]
```diff
@@ -639,15 +641,96 @@ template <typename T>
...
-/// taken by const pointer is to try to insist that the object to be a `const`
-/// view is actually const. Of course, there are ways of subverting this
-/// intended functionality and editing the data pointed into by `view` after
-/// this function is called; doing so is highly discouraged and results in
+/// \warning This DOES modify the (const) input `view`. The reason
+/// `view` is taken by const pointer is to try to insist that the
+/// object to be a `const` view is actually const. Of course,
+/// there are ways of subverting this intended functionality and
+/// editing the data pointed into by `view` after this function is
+/// called; doing so is highly discouraged and results in
```
Comment (nilsvu) [inline src/DataStructures/VectorImpl.hpp]: This is just formatting AFAICT, so just drop this hunk

File: tests/Unit/DataStructures/Test_SpinWeighted.cpp [hunk 10]
```diff
@@ -183,7 +183,6 @@ void test_spinweights() {
 
 using SpinWeightedTypePairs =
     tmpl::list<tmpl::list<std::complex<double>, double>,
-               tmpl::list<ComplexDataVector, double>,
```
Comment (nilsvu) [inline tests/Unit/DataStructures/Test_SpinWeighted.cpp:186]: why this change?

File: tests/Unit/Evolution/Systems/CurvedScalarWave/Test_UpwindPenaltyCorrection.cpp [hunk 11]
```diff
@@ -169,7 +169,7 @@ void test_upwind_flux_random() noexcept {
       CurvedScalarWave::CurvedScalarWave_detail::weight_char_fields<Dim>(
           char_fields_int, char_speeds_minus_one, char_fields_ext,
           char_speeds_minus_one);
-  CHECK(weighted_char_fields_minus_one == -1. * char_fields_ext);
+  CHECK_VARIABLES_APPROX(-1. * char_fields_ext, weighted_char_fields_minus_one);
```
Comment (nilsvu) [inline tests/Unit/Evolution/Systems/CurvedScalarWave/Test_UpwindPenaltyCorrection.cpp:172]: The changes in this file should probably be in the other commit, but I think it's fine to leave as-is, doesn't really matter

File: tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp [hunk 12]
```diff
@@ -77,6 +77,43 @@ void vector_test_construct_and_assign(
...
+          {static_cast<typename VectorType::value_type>(generated_value2),
+           static_cast<typename VectorType::value_type>(generated_value3)}}));
+  CHECK_FALSE(SINGLE_ARG(
+      initializer_list_constructed !=
+      VectorType{
+          {static_cast<typename VectorType::value_type>(generated_value2),
+           static_cast<typename VectorType::value_type>(generated_value3)}}));
+  const VectorType close = (1.0 + 1.0e-11) * initializer_list_constructed;
+  CHECK(initializer_list_constructed != close);
+  CHECK_FALSE(initializer_list_constructed == close);
```
Comment (nilsvu) [inline tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp:93]: Also here a `CHECK_ITERABLE_APPROX` could be useful to make the test more tight

File: src/DataStructures/VectorImpl.hpp [hunk 13]
```diff
@@ -639,15 +641,96 @@ template <typename T>
...
+// operators to use approximate equality in favor of equality
+// between containers being appropriately recursive. This form
+// primarily works by using templates to ensure that our
+// comparison operator is resolved with higher priority than the
+// blaze form as of blaze 3.8
+template <typename Lhs, typename Rhs,
+          Requires<std::is_base_of_v<blaze::Computation, Lhs> or
+                   std::is_base_of_v<blaze::Computation, Rhs>> = nullptr>
+bool operator==(const Lhs& lhs, const Rhs& rhs) noexcept {
+  return blaze::equal<blaze::strict>(lhs, rhs);
```
Comment (nilsvu) [inline src/DataStructures/VectorImpl.hpp:683]: since this implementation is the same as the one above, can you remove the `blaze::Computation` check? Or does that move the priority further down somehow?

**Review by nilsvu — CHANGES_REQUESTED** [review]

File: tests/Unit/DataStructures/Test_SpinWeighted.cpp (hunk 10 above)
Comment (moxcodes) [reply tests/Unit/DataStructures/Test_SpinWeighted.cpp:186]: This comparison no longer succeeds at the overload resolution (it generates a compile-time error). However, this was the only location in the codebase that it was used, so I don't think it's enough of a loss to make the comparison overloads more complicated to address this case.

File: src/DataStructures/VectorImpl.hpp (hunk 13 above)
Comment (moxcodes) [reply src/DataStructures/VectorImpl.hpp:683]: This is necessary for the overload priority to use this instead of the blaze ones -- `blaze::Computation` is a direct base of all of the expression templates, so uses this operator with higher priority than the conversions to `DenseVector`. However, `DenseVector` happens with the same priority as the other overload (to `VectorImpl`), so without this version with `blaze::Computation`, expression templates in comparison operators fail to compile with ambiguous overload.

**Comment by moxcodes** [comment]
Changes squashed in -- the only alterations aside from dropping the parts that shouldn't be there are:
```
--- a/tests/Unit/DataStructures/Test_Variables.cpp
+++ b/tests/Unit/DataStructures/Test_Variables.cpp
@@ -319,9 +319,10 @@ void test_variables_math() noexcept {
   // Test math +, -, *, /
   const TestVariablesType vars{num_points, value_in_variables};
   const TestVariablesType close{num_points,
-                                value_in_variables * (1.0 + 1.0e-11)};
+                                value_in_variables * (1.0 + 1.0e-14)};
   CHECK(close != vars);
   CHECK_FALSE(close == vars);
+  CHECK_VARIABLES_APPROX(close, vars);
   const TestVariablesType equivalent{num_points, value_in_variables};
   CHECK(equivalent == vars);
   CHECK_FALSE(equivalent != vars);
diff --git a/tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp b/tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp
index f19c0ea8e..ba42b81b9 100644
--- a/tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp
+++ b/tests/Unit/Helpers/DataStructures/VectorImplTestHelper.hpp
@@ -88,9 +88,10 @@ void vector_test_construct_and_assign(
       VectorType{
           {static_cast<typename VectorType::value_type>(generated_value2),
            static_cast<typename VectorType::value_type>(generated_value3)}}));
-  const VectorType close = (1.0 + 1.0e-11) * initializer_list_constructed;
+  const VectorType close = (1.0 + 1.0e-14) * initializer_list_constructed;
   CHECK(initializer_list_constructed != close);
   CHECK_FALSE(initializer_list_constructed == close);
+  CHECK_ITERABLE_APPROX(initializer_list_constructed, close);
 
   CHECK(
       initializer_list_constructed !=
```

**Review by wthrowe — APPROVED** [review]

**Review by nilsvu — APPROVED** [review]
