### PR TITLE
Increase FConstraint tolerance

### LINKED ISSUE #1458: Test failure Unit.Evolution.Systems.GeneralizedHarmonic.FConstraint
# Bug reports:

The test `Unit.Evolution.Systems.GeneralizedHarmonic.FConstraint` fails with:
```
  CHECK( a == appx(b) )
with expansion:
  35.1548398018 == Approx( 35.1548397973 )
with messages:
  seed: 3602119563
  function: f_constraint
  /work/spectre/tests/Unit/Pypp/CheckWithRandomValues.hpp:223: result == pypp::
  call<ResultType>( module_name, function_name, std::get<ArgumentIs>(args)...,
  forward_to_pypp<ResultType>(std::get<MemberArgsIs>(member_args),
  used_for_size)...)
  a: T(0)=3.515483980177322110e+01
  T(1)=-1.231729384453743842e+05
  T(2)=9.059970598160572990e+04
  T(3)=-1.884125886912320566e+05
  b: T(0)=3.515483979730174724e+01
  T(1)=-1.231729384453615930e+05
  T(2)=9.059970598160296504e+04
  T(3)=-1.884125886912363057e+05
  a: 3.515483980177322110e+01
  b: 3.515483979730174724e+01
```

### Environment:

TravisCI

### PR DESCRIPTION
**Pull request by geoffrey4444**
## Proposed changes
Fixes #1458 by increasing the tolerance. The F constraint has many terms, each of which is a summation of several factors. Because there are so many terms, roundoff error accumulates.

I ran the python test (which uses `np.einsum`), printing out the value of each of the 26 terms as well as the constraint. I also printed each term and the total after shifting each input by 1.0e-15 (roundoff). Then, I subtracted the value of each term with and without the roundoff shift. For the seed I tried (801541510), I found that the roundoff error increases with the number of spatial dimensions, which makes sense, since higher dimensions means more terms in the summations. I found for 3 spatial dimensions for this seed, roundoff error is O(1e-8) for the F constraint. 

Term 6/25 has the largest roundoff error, but many other terms have roundoff errors almost as large. I don’t see any obvious way to simplify this term (but I welcome suggestions!). 

Based on these observations, I recommend setting the tolerance to 1.0e-7. This PR does that.

### Types of changes:

- [x] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [x] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [x] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [x] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by nilsdeppe — DISMISSED** [review]

File: tests/Unit/Evolution/Systems/GeneralizedHarmonic/Test_Constraints.cpp [hunk 1]
```diff
@@ -401,7 +401,7 @@ void test_f_constraint_random(const DataType& used_for_size) noexcept {
           const tnsr::iaa<DataType, SpatialDim, Frame>&)>(
           &GeneralizedHarmonic::f_constraint<SpatialDim, Frame, DataType>),
       "TestFunctions", "f_constraint", {{{-10.0, 10.0}}}, used_for_size,
-      1.0e-9);  // Loosen tolerance to avoid occasional failures of this test
+      1.0e-7);  // Loosen tolerance to avoid occasional failures of this test
```
Comment (kidder) [inline tests/Unit/Evolution/Systems/GeneralizedHarmonic/Test_Constraints.cpp]: would reducing the size of the random values from 10 to 1, enable us to use a tighter tolerance?

**Comment by geoffrey4444** [comment]
Yes! It turns out that for every case I've looked at, lowering the random number range to +/- 1.0 instead of +/- 10.0 reduces the roundoff error from O(1.0e-8) to O(1.0e-14). So I think instead, I should be able to actually tighten the tolerance back to the default while just reducing the range of the random numbers.

I'm just waiting for the test to run 10k times with this change, to make sure I don't get any failures, before pushing this.

**Review by kidder — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]
