### PR TITLE
fix LinearSolve test random fail

### LINKED ISSUE #1781: random failure in Unit.Evolution.Systems.Cce.LinearSolve
# Bug reports:

### Expected behavior:

test passes with no failure

### Current behavior:

419/1027 Test #413: Unit.Evolution.Systems.Cce.LinearSolve ......................................***Exception: Child aborted  2.82 sec
Charm++: standalone mode (not using charmrun)
Charm++> Running in Multicore mode:  1 threads
Converse/Charm++ Commit ID: v6.8.0-0-ga36028edb
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (2-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.
SpECTRE Build Information:
Version:                      0.0.0
Compiled on host:             e0459d3b4713
Compiled in directory:        /work/build_Debug_gcc-8
Source directory is:          /work/spectre
Compiled on git branch:       HEAD
Compiled with git hash:       23b494a6a49fb89722db020567e2d3fede9a3e57
Linked on:                    Sat Nov  9 16:43:31 2019
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"Debug.Unit.Evolution.Systems.Cce.LinearSolve" is a Catch v2.2.1 host application.
Run with -? for options
-------------------------------------------------------------------------------
Unit.Evolution.Systems.Cce.LinearSolve
-------------------------------------------------------------------------------
/work/spectre/tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp:428
...............................................................................
/work/spectre/tests/Unit/TestingFramework.hpp:162: FAILED:
  CHECK( a == appx(b) )
with expansion:
  15.4608404114 == Approx( 15.4608404166 )
with messages:
  Seed is: 2935843205 from /work/spectre/tests/Unit/Evolution/Systems/Cce/
  Test_LinearSolve.cpp:429
<!--
describe the current behavior and how to reproduce
-->

### Environment:
travis build
https://travis-ci.org/sxs-collaboration/spectre/jobs/609368506?utm_medium=notification&utm_source=github_status

### LINKED ISSUE #1847: Random failure in Unit.Evolution.Systems.Cce.LinearSolve
# Bug reports:

```
2019-12-09T02:47:29.1581741Z -------------------------------------------------------------------------------
2019-12-09T02:47:29.1581850Z Unit.Evolution.Systems.Cce.LinearSolve
2019-12-09T02:47:29.1582132Z -------------------------------------------------------------------------------
2019-12-09T02:47:29.1582418Z /__w/spectre/spectre/tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp:428
2019-12-09T02:47:29.1583223Z ...............................................................................
2019-12-09T02:47:29.1583564Z 
2019-12-09T02:47:29.1583674Z /__w/spectre/spectre/tests/Unit/TestingFramework.hpp:162: FAILED:
2019-12-09T02:47:29.1583777Z   CHECK( a == appx(b) )
2019-12-09T02:47:29.1583871Z with expansion:
2019-12-09T02:47:29.1583964Z   30.2594421284 == Approx( 30.2594421389 )
2019-12-09T02:47:29.1584226Z with messages:
2019-12-09T02:47:29.1584306Z   Seed is: 3891814485 from /__w/spectre/spectre/tests/Unit/Evolution/Systems/
2019-12-09T02:47:29.1584417Z   Cce/Test_LinearSolve.cpp:429
2019-12-09T02:47:29.1584696Z   /__w/spectre/spectre/tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp:
```

### PR DESCRIPTION
**Pull request by moxcodes**
## Proposed changes
resolves #1781 
resolves #1847 

Makes the linear solve test closer to the realistic situation by generating angular modes rather than angular points and insisting that the linear factor is only a small (~.1) deviation from the leading asymptotic behavior.

Before, failed within 500 attempts, after this change it runs 10^5 iterations without fail.

### Types of changes:

- [x] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

File: tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp [hunk 1]
```diff
@@ -426,7 +432,7 @@ void test_pole_integration_with_linear_operator(
 
 SPECTRE_TEST_CASE("Unit.Evolution.Systems.Cce.LinearSolve",
                   "[Unit][Evolution]") {
-  MAKE_GENERATOR(gen);
+  MAKE_GENERATOR(gen, 3891814485);
```
Comment (fmahebert) [inline tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp]: Is this intentionally included with this PR?

Comment (moxcodes) [reply tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp]: definitely not, removing...

**Comment by moxcodes** [comment]
.. and now it succeeds 10^5 cases even when the seed isn't hard-coded...

File: tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp [hunk 2]
```diff
@@ -294,7 +294,8 @@ template <typename BondiValueTag, typename Generator>
 void test_pole_integration_with_linear_operator(
     const gsl::not_null<Generator*> gen, size_t number_of_radial_grid_points,
     size_t l_max) noexcept {
-  UniformCustomDistribution<double> dist(0.1, 5.0);
+  // the relevant linear solves usually involve fairly small wave amplitudes
```
Comment (fmahebert) [inline tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp]: As a non CCE expert, I'm not sure what you mean by "relevant". I suggest (assuming I correctly understood) something like "The linear solves used in CCE usually involve...", or any improved version of this that you like.

File: tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp [hunk 3]
```diff
@@ -306,6 +307,25 @@ void test_pole_integration_with_linear_operator(
       tmpl::list<BondiValueTag, Tags::PoleOfIntegrand<BondiValueTag>,
                  Tags::LinearFactor<BondiValueTag>,
                  Tags::LinearFactorForConjugate<BondiValueTag>>{});
+  // it is a more realistic linear solve if the linear factors have the right
+  // leading behavior
```
Comment (fmahebert) [inline tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp]: I'm not quite sure what you mean by "realistic" here. Do you mean that this more closely resembles the linear solves done in the CCE code? or just that it is mathematically better matching some assumptions? I think if you could clarify this and also where "the right leading behavior" comes from, the comment would be more helpful.

File: tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp [hunk 4]
```diff
@@ -319,9 +339,27 @@ void test_pole_integration_with_linear_operator(
                                           Spectral::Quadrature::GaussLobatto>(
                  number_of_radial_grid_points));
 
-  const auto random_angular_data = make_with_random_values<ComplexDataVector>(
+  auto random_angular_data = make_with_random_values<ComplexDataVector>(
```
Comment (fmahebert) [inline tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp:349]: I found this new code block a little unclear, and thought it could benefit from a comment. I think it could be helpful to say (in a sentence or two) why you are generating random data to go into a filter buffer, and also what the significance is of truncating the random modes below.

**Review by fmahebert — COMMENTED** [review]
The code changes look OK to me. Here are some optional suggestions on documentation from the perspective of a non-expert. Feel free to implement these or not; if you do implement, then please squash directly.

**Comment by moxcodes** [comment]
@fmahebert additional comments squashed in.
Cheers!

File: tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp [hunk 5]
```diff
@@ -294,7 +294,9 @@ template <typename BondiValueTag, typename Generator>
 void test_pole_integration_with_linear_operator(
     const gsl::not_null<Generator*> gen, size_t number_of_radial_grid_points,
     size_t l_max) noexcept {
-  UniformCustomDistribution<double> dist(0.1, 5.0);
+  // The typical linear solve performed during realistic CCE evolution involve
```
Comment (fmahebert) [inline tests/Unit/Evolution/Systems/Cce/Test_LinearSolve.cpp]: typo: involve -> involves

**Review by fmahebert — COMMENTED** [review]
Thanks, I think these comments are much more helpful now! I've found a typo (squash directly); aside from this I am happy :)

**Comment by moxcodes** [comment]
Done.
Cheers!

**Review by fmahebert — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]
