### PR TITLE
Remove function of time names from options

### LINKED ISSUE #3489: How are function-of-time names chosen?
# Bug reports:

I don't understand how the names of functions-of-time are chosen, or what determines them. Input files require I set those names in `TimeDependence` sections -- can I just write any name, and if so, why does the choice exist at all? I looked (briefly) through `DomainCreator.hpp`, `TimeDependence.hpp` and `FunctionOfTime.hpp` but didn't find relevant docs. If they exist, I suggest we refer to them better from these files, and if they don't, I suggest we add some. If the input-file options for these names should remain, I suggest we add instructions for the user how the names should be chosen. In particular, I find help strings like `"FunctionOfTimeName: Names of the functions of time."` very unhelpful.

### PR DESCRIPTION
**Pull request by knelli2**
## Proposed changes

This PR removes the options for both the function of time names and initial expiration times. The name of a function of time is only needed internally in the code and shouldn't be specifiable by the user. Once control systems are in, the names will need to match between control systems and the functions of time they control, so this aims to eliminate any user error that comes with allowing the names to be specified as options.

Additionally, if there are control systems, initial expiration times are set automatically based on the damping timescale of the control system. ~It is not clear at the moment what *exactly* to set the initial expiration time as, because it is unclear how often we will be doing measurements. Thus, for now~ I have just chosen a convention that seems reasonable: According to [arXiv 1211.6079](https://arxiv.org/abs/1211.6079), in SpEC the time between updates is specified as a fraction of the damping timescale of the control system. In SpECTRE, the initial expiration time (and in the future, subsequent expiration times) will be set to this update timescale, because we want to update the function of time when it expires. As a safeguard against unreasonable inputs for GTS, if this update timescale is less than the initial time step, the initial expiration time is just set to a time step. This can be changed in the future to accommodate LTS.
If there aren't control systems, the initial expiration time of all functions of time is set to `std::numeric_limits<double>::infinity()` because functions of time without control systems should never expire (there's nothing to update them).

In order to make these changes, a few additional changes had to be made concurrently:
~1. OptionHolder for a control system is now templated on the control system itself and also stores its name.
2. `domain::Tags::FunctionsOfTime` now loops over the `component_list` type alias in the metavariables. If any `ControlComponent`s are present in `component_list`, then initial expiration times are calculated for those functions of time and are passed to the domain creator.~
3. For most of the existing `TimeDepenence`s, we'll want at most one of each in a simulation at a time. This doesn't cause an issue with unique names. The exception to this is a `UniformTranslation` because it is simple and very useful for testing. To distinguish `UniformTranslation`s in both the factory and in their names for functions of time, an additional template parameter `Index` was added which is defaulted to `0`. If `Index==0`, the uniform translation is the same as it is before, name and everything. If, for example, `Index==1`, everything is still the same except the name of the function of time is `Translation1` and the name for creating by options is `UniformTranslation1`.

#### Notes:
- ~I realize this is a somewhat long and complicated PR. The first two commits, are from #3601. I tried to break the rest up into a few things that were necessary but could stand on their own. The last commit contains the bulk of the changes. While I think it technically would have been possible to first remove the function of time names in one PR,  then the expiration times in a second one (honestly I'm not sure though), I would have basically been editing the exact same lines. Also, these two changes are very closely tied together because the new "hard coded" names are used when setting the expiration times. So for those reasons both changes are done at once.~
- I had to pick default names for all the existing `TimeDependence`s and `DomainCreator`s that construct their functions of time themselves. If there are better names for the defaults, please leave a comment and we can discuss.

Fixes #3489 

### Upgrade instructions

Remove all `FunctionOfTimeName:` and `InitialExpirationDeltaT:` options from input files

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### Dependencies
- [x] PR #3601

### CODE REVIEW

File: src/ControlSystem/Actions/Initialization.hpp [hunk 1]
```diff
@@ -71,7 +72,7 @@ struct Initialize {
         db::get<control_system::Tags::ControlSystemInputs<ControlSystem>>(box);
     ::Initialization::mutate_assign<tags_to_be_initialized>(
         make_not_null(&box), option_holder.averager, option_holder.controller,
-        option_holder.tuner);
+        option_holder.tuner, option_holder.name);
```
Comment (wthrowe) [inline src/ControlSystem/Actions/Initialization.hpp]: Can you use `ControlSystem::name()` here?  Seems weird to have something in the option holder that isn't an option.

File: src/Domain/Creators/BinaryCompactObject.cpp [hunk 2]
```diff
@@ -655,17 +646,27 @@ Domain<3> BinaryCompactObject::create_domain() const {
...
                      std::unique_ptr<domain::FunctionsOfTime::FunctionOfTime>>
       result{};
   if (not enable_time_dependence_) {
     return result;
   }
 
-  const double initial_expiration_time =
-      initial_expiration_delta_t_ ? initial_time_ + *initial_expiration_delta_t_
-                                  : std::numeric_limits<double>::infinity();
+  if (not initial_expiration_times.empty()) {
```
Comment (wthrowe) [inline src/Domain/Creators/BinaryCompactObject.cpp]: Some domain creators (like BinaryCompactObject) don't seem useful to evolve with time-dependence without control systems.  Should those require `initial_expiration_times` to be set?

File: src/Domain/Creators/BinaryCompactObject.hpp [hunk 3]
```diff
@@ -771,7 +721,19 @@ class BinaryCompactObject : public DomainCreator<3> {
   std::array<double, 2> initial_size_map_accelerations_{
       std::numeric_limits<double>::signaling_NaN(),
       std::numeric_limits<double>::signaling_NaN()};
-  std::array<std::string, 2> size_map_function_of_time_names_;
+  std::array<std::string, 2> size_map_function_of_time_names_{
+      {"SizeA", "SizeB"}};
+  // mutable because the expiration times can potentially be changed in the
+  // const member `functions_of_time` if there are control systems
```
Comment (wthrowe) [inline src/Domain/Creators/BinaryCompactObject.hpp]: This does not seem like a good use of `mutable`.  If this is observable state it shouldn't be changed by a const method.  If it is not observable state do you need the variable?

File: src/Domain/Creators/CylindricalBinaryCompactObject.cpp [hunk 4]
```diff
@@ -682,11 +682,14 @@ CylindricalBinaryCompactObject::initial_refinement_levels() const {
 
 std::unordered_map<std::string,
                    std::unique_ptr<domain::FunctionsOfTime::FunctionOfTime>>
-CylindricalBinaryCompactObject::functions_of_time() const {
+CylindricalBinaryCompactObject::functions_of_time(
+    const std::unordered_map<std::string, double>& initial_expiration_times)
+    const {
   if (time_dependence_->is_none()) {
+    (void)(initial_expiration_times);
```
Comment (wthrowe) [inline src/Domain/Creators/CylindricalBinaryCompactObject.cpp]: Should only need things like this with constexpr if.

File: src/Domain/Creators/TimeDependence/CubicScale.hpp [hunk 5]
```diff
@@ -137,24 +123,32 @@ class CubicScale final : public TimeDependence<MeshDim> {
...
+                             initial_expiration_times = {}) const
+      -> std::unordered_map<
+          std::string,
+          std::unique_ptr<domain::FunctionsOfTime::FunctionOfTime>> override;
 
   /// Returns the map for each block to be used in a composition of
   /// `TimeDependence`s.
   MapForComposition map_for_composition() const;
 
+  static std::string name() { return pretty_type::short_name<CubicScale>(); }
```
Comment (wthrowe) [inline src/Domain/Creators/TimeDependence/CubicScale.hpp]: What needs this?

File: src/Domain/FunctionsOfTime/Tags.hpp [hunk 6]
```diff
@@ -37,26 +41,44 @@ struct OptionList {
       tmpl::list<domain::OptionTags::DomainCreator<Metavariables::volume_dim>,
                  domain::FunctionsOfTime::OptionTags::FunctionOfTimeFile,
                  domain::FunctionsOfTime::OptionTags::FunctionOfTimeNameMap>,
-      tmpl::list<domain::OptionTags::DomainCreator<Metavariables::volume_dim>>>;
+      tmpl::flatten<tmpl::list<
```
Comment (wthrowe) [inline src/Domain/FunctionsOfTime/Tags.hpp]: I think this is the same as the list below, so how about `typename OptionList<Metavariables, false>::type`?

File: src/Domain/FunctionsOfTime/Tags.hpp [hunk 7]
```diff
@@ -140,11 +162,28 @@ struct FunctionsOfTime : db::SimpleTag {
...
   }
 
-  template <typename Metavariables>
+  template <typename Metavariables, typename... OptionHolders>
   static type create_from_options(
       const std::unique_ptr<::DomainCreator<Metavariables::volume_dim>>&
-          domain_creator) {
-    return domain_creator->functions_of_time();
+          domain_creator,
+      const double initial_time_step, const OptionHolders&&... option_holders) {
```
Comment (wthrowe) [inline src/Domain/FunctionsOfTime/Tags.hpp]: `&&` -> `&`

File: src/Domain/FunctionsOfTime/Tags.hpp [hunk 8]
```diff
@@ -140,11 +162,28 @@ struct FunctionsOfTime : db::SimpleTag {
...
+      const auto controller = option_holder.controller;
+      const std::string name = option_holder.name;
+      const auto tuner = option_holder.tuner;
+
+      const double update_fraction = controller.get_update_fraction();
+      const double curr_timescale = min(tuner.current_timescale());
+      const double initial_expiration_time = update_fraction * curr_timescale;
+      initial_expiration_times[name] =
+          initial_expiration_time < initial_time_step ? initial_time_step
+                                                      : initial_expiration_time;
```
Comment (wthrowe) [inline src/Domain/FunctionsOfTime/Tags.hpp]: `std::max`

**Review by wthrowe — CHANGES_REQUESTED** [review]
I haven't gotten through everything.

My comments on domain creators also apply to the other creators where similar things appear.

File: src/Domain/Creators/BinaryCompactObject.hpp (hunk 3 above)
Comment (nilsvu) [reply src/Domain/Creators/BinaryCompactObject.hpp]: I believe the domain creator only exists during option parsing, so it doesn't seem like a place to store any state that is changed by control systems

File: src/Domain/Creators/BinaryCompactObject.cpp (hunk 2 above)
Comment (nilsvu) [reply src/Domain/Creators/BinaryCompactObject.cpp]: If I understand correctly, the control flow goes like this: The domain creator decides which FoT are around to control the domain. Then control systems can jump in to update those FoT. So it seems to me the domain creator doesn't need to know anything about control systems, but only the reverse: Control systems are set up with a name, and that name must exist as a FoT in the domain. Therefore, it seems to me the initial expiration time shouldn't be set by the domain creator, but the control system should jump in after the FoT were created to set the expiration time (essentially saying "I'm going to take control of this FoT from now on, here's when I'm going to update it"). I think my suggestion is to set the initial expiration time where you initialize the control systems.

Indeed I think you are currently in danger of running into a cyclic dependency: Control systems will depend on Domain/TimeDep in some way or another (no way around that, right?), so Domain/TimeDep can't depend on ControlSystems. Please make sure you are keeping this dependency graph in mind. An easy rule is: don't `include` control-system headers in `Domain/` (you currently do in `Domain/TimeDep/Tags.hpp` for instance).

Comment (wthrowe) [reply src/Domain/Creators/BinaryCompactObject.cpp]: Good point, but I'm not sure how to deal with it.  It might make sense to move most of this logic from the domain creators to the FoT initialization code, but that's still in Domain so that doesn't help.  We can't run initialization actions on the global cache.  We can't handle it entirely from the control system chares, because something has to handle the FoTs that aren't being controlled.

Comment (nilsvu) [reply src/Domain/Creators/BinaryCompactObject.cpp]: Ok. My suggestions for now are:

- Don't include ControlSystem things in `Domain/` unless you absolutely have to for now.
- Remove the `initial_expiration_times` argument from the domain creators. Instead, set it after retrieving the FoT from the domain creator. That's currently in `Domain/FoT/Tags.hpp` and I suppose it's ok to leave it there for now, but we'll have to think where we can move it to avoid a cyclic dependency.

Comment (knelli2) [reply src/Domain/Creators/BinaryCompactObject.cpp]: My issue with this, then, is what do you set the initial expiration times as in the DomainCreator? Because that's where the functions of time are constructed with all their initial data. Functions of time need to be constructed with an initial expiration time as well.

I could conceivably set the "expiration time" in the DomainCreator to the initial time as a sort of fake expiration time, then reset the initial expiration time to the actual initial expiration time in `Domain/FoT/Tags/hpp`. However, I don't like resetting an expiration time without any update actually happening.

Comment (nilsvu) [reply src/Domain/Creators/BinaryCompactObject.cpp]: Can the initial expiration time be max, inf, nan or std::nullopt, signaling the FoT is "uncontrolled", and then the control system takes over and gives it an expiration time? Then there can also be a check somewhere that all FoTs that require a control system have one.

Comment (knelli2) [reply src/Domain/Creators/BinaryCompactObject.cpp]: Currently, expiration times must be increasing from call to call. The initial expiration time could be -inf or -max, then when the control system sets the actual expiration times, if there is a function not being controlled, its expiration time could be set to +inf then.

Comment (wthrowe) [reply src/Domain/Creators/BinaryCompactObject.cpp]: Maybe we could have each type (C++ sense) of FoT either always be controlled or always be uncontrolled.  An uncontrolled piecewise polynomial always struck me as somewhat questionable, except for the linear case.  Then, I think the setup could be done by the control components during initialization.  (Although I don't know where a sanity check for missing control systems would go.)

Comment (nilsvu) [reply src/Domain/Creators/BinaryCompactObject.cpp]: All this sounds good. My suggestion would be to construct FoTs without an expiration time, then have the control system update it. Each FoT decides internally how to handle initial state and expirations. A piecewise polynomial would construct in an exp_time=nullopt/nan/-inf state and complain if it doesn't get updated. A `FixedSpeedCubic` doesn't care about exp times at all.

**Comment by knelli2** [comment]
@wthrowe @nilsleiffischer This is now ready to be looked at again.

File: src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp [hunk 9]
```diff
@@ -54,18 +56,36 @@ struct FunctionsOfTimeInitialize : domain::Tags::FunctionsOfTime,
...
-    // changed.
-    auto functions_of_time = domain_creator->functions_of_time();
-    for (auto& [name, expr_time] : initial_expiration_times) {
-      const double curr_expr_time =
-          functions_of_time.at(name)->time_bounds()[1];
-      functions_of_time.at(name)->reset_expiration_time(
-          std::max(curr_expr_time, expr_time));
+
+    type functions_of_time{
+        std::move(domain_creator->functions_of_time(initial_expiration_times))};
```
Comment (nilsvu) [inline src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp]: why not just `auto functions_of_time = domain_creator->functions_of_time(...)`

File: src/Domain/Creators/BinaryCompactObject.cpp [hunk 10]
```diff
@@ -656,17 +647,35 @@ Domain<3> BinaryCompactObject::create_domain() const {
...
+       std::numeric_limits<double>::infinity()},
+      {size_map_function_of_time_names_[0],
+       std::numeric_limits<double>::infinity()},
+      {size_map_function_of_time_names_[1],
+       std::numeric_limits<double>::infinity()}};
+
+  // If we have control systems, overwrite these expiration times with the ones
+  // supplied by the control system
+  for (auto& [name, expr_time] : initial_expiration_times) {
+    if (expiration_times.count(name) == 1) {
```
Comment (nilsvu) [inline src/Domain/Creators/BinaryCompactObject.cpp]: just delete this `if`? Inconsistencies should be caught by the checks in the initialization right

File: src/Domain/Creators/BinaryCompactObject.hpp [hunk 11]
```diff
@@ -783,7 +735,8 @@ class BinaryCompactObject : public DomainCreator<3> {
   std::array<double, 2> initial_size_map_accelerations_{
       std::numeric_limits<double>::signaling_NaN(),
       std::numeric_limits<double>::signaling_NaN()};
-  std::array<std::string, 2> size_map_function_of_time_names_;
+  std::array<std::string, 2> size_map_function_of_time_names_{
```
Comment (nilsvu) [inline src/Domain/Creators/BinaryCompactObject.hpp]: I think these added members can be `const`, maybe even `static`? Not sure which is better. @wthrowe?

File: src/Domain/Creators/TimeDependence/CubicScale.hpp (hunk 5 above)
Comment (nilsvu) [reply src/Domain/Creators/TimeDependence/CubicScale.hpp]: ping on this (I think it can be deleted)

**Review by nilsvu — CHANGES_REQUESTED** [review]

File: tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml [hunk 12]
```diff
@@ -100,7 +96,7 @@ EvolutionSystem:
           Amplitude: 0.75            # 0.75 / (m_A + m_B)
           Width: 38.415              # 2.5 * (x_B - x_A)
           Center: [0.0, 0.0, 0.0]
-        FunctionOfTimeForScaling: ExpansionFactor
+        FunctionOfTimeForScaling: Expansion
```
Comment (knelli2) [inline tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml]: Self change request: Take this out of options and just hard code the name because I believe this can only be used with a binary compact object domain (i.e. with an expansion map) but I'm not sure.

File: src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp [hunk 13]
```diff
@@ -54,18 +56,36 @@ struct FunctionsOfTimeInitialize : domain::Tags::FunctionsOfTime,
...
+
+    // Check that all control systems are actually controlling a function of
+    // time, and that the expiration times have been set appropriately. If there
```
Comment (wthrowe) [inline src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp:64]: Do we want to do this?  I thought we decided we didn't.

File: src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp [hunk 14]
```diff
@@ -54,18 +56,36 @@ struct FunctionsOfTimeInitialize : domain::Tags::FunctionsOfTime,
...
+            << keys_of(functions_of_time));
+      }
+
+      if (functions_of_time.at(name)->time_bounds()[1] != expr_time) {
+        ERROR("The expiration time for the function of time '"
+              << name << "' has been set improperly. It is supposed to be "
+              << expr_time << " but is currently set to "
+              << functions_of_time.at(name)->time_bounds()[1]
+              << ". Is the DomainCreator you are using compatible with control "
+                 "systems?");
```
Comment (wthrowe) [inline src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp]: Avoid putting suggestions in the form of questions.  If the person reading the error isn't familiar with what is going on, it is not clear whether the answer is supposed to be yes or whether an answer of yes is a possible cause of the problem.

File: src/Domain/Creators/BinaryCompactObject.hpp (hunk 11 above)
Comment (wthrowe) [reply src/Domain/Creators/BinaryCompactObject.hpp]: `static const` would be good, yes.  (I prefer to avoid `const` non-static member variables because they prevent the class from being assigned to.)

I guess the same thing goes for most of the domain creators, although some of them can modify their lists.  Depending on how widely they are used making the values local to a function or something might be better.

Comment (knelli2) [reply src/Domain/Creators/BinaryCompactObject.hpp]: Probably `static`, but I'll wait for @wthrowe's opinion first before I change those.

File: src/Domain/Creators/TimeDependence/CubicScale.hpp (hunk 5 above)
Comment (knelli2) [reply src/Domain/Creators/TimeDependence/CubicScale.hpp]: This is used by `TimeDependenceCompositionTag` in `Domain/Creators/TimeDependence/Composition.hpp` to get the name of the time dependence used in a composition for options. Hence why I only have a `name()` member for `UniformTranslation`, `UniformRotationAboutZAxis`, and `CubicScale` because those are the only three time dependences used in compositions at the moment.

Comment (nilsvu) [reply src/Domain/Creators/TimeDependence/CubicScale.hpp]: I would suggest to replace the code that calls this function with `Options::name<Type>()`, which will use the name of the class unless a `name()` function exists. Then you can just implement a `name()` function for classes where you want to override the default name (if any).

Comment (knelli2) [reply src/Domain/Creators/TimeDependence/CubicScale.hpp]: I was unaware of this feature, that would be perfect here because currently only `UniformTranslation` needs a custom name. The others can just be the name of the class.

**Review by wthrowe — CHANGES_REQUESTED** [review]
Sorry for the delay, I got distracted halfway through and forgot I hadn't finished.

File: src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp (hunk 13 above)
Comment (knelli2) [reply src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp:64]: The check if the control systems have been set up properly? I'm not recalling why we decided not to do this. Could you remind me?

Comment (wthrowe) [reply src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp:64]: My thought was that this effectively chooses the domain at compile time, which is unpleasant for proliferation of exeutables, but maybe that's unavoidable here.  OK, leave this as-is.

Comment (knelli2) [reply src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp:64]: Yes because certain control systems can only be used with certain domains (the functions of time have to actually be used in the domain for them to be controlled). I remember we considered the idea of a factory system to specify which DomainCreators could be used with certain executables moving forward.

Comment (wthrowe) [reply src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp:64]: The (domain, control systems) pairs are fixed, but we could include several of them in one executable by letting users choose the domain and ignoring control systems not used by that choice.

Comment (knelli2) [reply src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp:64]: Good point. But I think that can be included at a later time after we actually have control systems in

File: src/Domain/Creators/TimeDependence/CubicScale.cpp [hunk 15]
```diff
@@ -69,32 +72,42 @@ CubicScale<MeshDim>::block_maps(const size_t number_of_blocks) const {
...
+  // Functions of time don't expire by default
+  std::unordered_map<std::string, double> expiration_times{};
+  for (auto& cubic_name : functions_of_time_names_) {
+    expiration_times[cubic_name] = std::numeric_limits<double>::infinity();
+  }
+
+  // If we have control systems, overwrite these expiration times with the ones
+  // supplied by the control system
+  for (auto& [name, expr_time] : initial_expiration_times) {
+    if (expiration_times.count(name) == 1) {
```
Comment (nilsvu) [inline src/Domain/Creators/TimeDependence/CubicScale.cpp:91]: Since you deleted this `if` in the domain creator, also carry it through here

File: tests/Unit/Domain/Creators/Test_BinaryCompactObject.cpp [hunk 16]
```diff
@@ -46,6 +46,7 @@ class FunctionOfTime;
 namespace {
 using BoundaryCondVector = std::vector<DirectionMap<
     3, std::unique_ptr<domain::BoundaryConditions::BoundaryCondition>>>;
+using ExprTimeMap = std::unordered_map<std::string, double>;
```
Comment (nilsvu) [inline tests/Unit/Domain/Creators/Test_BinaryCompactObject.cpp]: Please spell out `ExpirationTimeMap`

File: tests/Unit/Domain/Creators/Test_CylindricalBinaryCompactObject.cpp [hunk 17]
```diff
@@ -42,6 +42,7 @@ using Translation = domain::CoordinateMaps::TimeDependent::Translation<1>;
 using Translation3D = domain::CoordinateMaps::TimeDependent::Translation<3>;
 using BoundaryCondVector = std::vector<DirectionMap<
     3, std::unique_ptr<domain::BoundaryConditions::BoundaryCondition>>>;
+using ExprTimeMap = std::unordered_map<std::string, double>;
```
Comment (nilsvu) [inline tests/Unit/Domain/Creators/Test_CylindricalBinaryCompactObject.cpp]: also spell it out here

File: tests/Unit/Domain/Creators/TimeDependence/Test_CubicScale.cpp [hunk 18]
```diff
@@ -149,78 +178,68 @@ void test_impl(
 }
 
 template <size_t MeshDim>
-void test() {
+void test(bool use_linear_scaling) {
```
Comment (nilsvu) [inline tests/Unit/Domain/Creators/TimeDependence/Test_CubicScale.cpp]: const

File: src/Evolution/Systems/GeneralizedHarmonic/ConstraintDamping/TimeDependentTripleGaussian.hpp [hunk 19]
```diff
@@ -176,7 +169,7 @@ class TimeDependentTripleGaussian : public DampingFunction<3, Frame::Grid> {
   double amplitude_3_ = std::numeric_limits<double>::signaling_NaN();
   double inverse_width_3_ = std::numeric_limits<double>::signaling_NaN();
   std::array<double, 3> center_3_{};
-  std::string function_of_time_for_scaling_;
+  std::string function_of_time_for_scaling_{"Expansion"};
```
Comment (nilsvu) [inline src/Evolution/Systems/GeneralizedHarmonic/ConstraintDamping/TimeDependentTripleGaussian.hpp]: static

**Review by nilsvu — CHANGES_REQUESTED** [review]
LGTM, please squash everything

File: src/Domain/Creators/TimeDependence/CubicScale.cpp (hunk 15 above)
Comment (knelli2) [reply src/Domain/Creators/TimeDependence/CubicScale.cpp:91]: For the BinaryCompactObjectDomain, it made sense to get rid of this `if` because it is the final stop for all expiration times. However, in the time dependences it isn't.

Consider a composition between cubic scale and rotation where only rotation is controlled. `initial_expiration_times` would only contain "Rotation". However, if I remove this `if`, CubicScale would still try to look for its names in `initial_expiration_times` (and fail) because it expects them to be there. Thus, I think this `if` should remain in all the TimeDependences

**Comment by knelli2** [comment]
Squashed all changes and rebased on latest develop

File: src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp (hunk 13 above)
Comment (wthrowe) [reply src/ControlSystem/Tags/FunctionsOfTimeInitialize.hpp:64]: I think we're talking past one another.  I'm trying to describe the current state of develop, not suggesting a feature.

That said, I'm no longer convinced that what develop is doing is what we want, so we shouldn't block this on making them agree.

**Review by wthrowe — APPROVED** [review]

**Review by nilsvu — APPROVED** [review]
