### PR TITLE
Fix reported link time

### LINKED ISSUE #6558: Build information "Linked on" date is wrong
An executable I just rebuilt prints a date almost a year in the past.  The other information appears to be correct.
```
SpECTRE Build Information:
Version:                      2025.03.17
Compiled on host:             ungoliant
Compiled in directory:        /home/wthrowe/spectre-work
Source directory is:          /home/wthrowe/spectre
Compiled on git branch:       variable_order
Compiled on git revision:     22ab093ff
Linked on:                    Mon Jun 10 16:06:57 2024
Build type:                   Debug
```

### PR DESCRIPTION
**Pull request by wthrowe**
__TIMESTAMP__ is the modification date of the file, not the current date.  That probably worked back when we made a separate copy of the file for each executable, but we stopped doing that a while ago.

Fixes #6558 

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

File: tools/WrapExecutableLinker.sh [hunk 1]
```diff
@@ -41,11 +41,12 @@ if [ -f @CMAKE_BINARY_DIR@/tmp/Formaline.sh ]; then
...
     "$@" -DGIT_DESCRIPTION=$git_description -DGIT_BRANCH=$git_branch \
-         ${InfoAtLink_flags} "${InfoAtLink_file}" "${formaline_output}" \
-         ${formaline_object_output}
+         -DLINK_TIME="$(LC_ALL=C date -u)" ${InfoAtLink_flags} \
+         "${InfoAtLink_file}" "${formaline_output}" ${formaline_object_output}
 else
     "$@" -DGIT_DESCRIPTION=$git_description -DGIT_BRANCH=$git_branch \
-         ${InfoAtLink_flags} "${InfoAtLink_file}"
+         -DLINK_TIME="$(LC_ALL=C date -u)" ${InfoAtLink_flags} \
+         "${InfoAtLink_file}"
```
Comment (duetosymmetry) [inline tools/WrapExecutableLinker.sh]: Can we use ISO 8601 for simpler parsing? (Then the locale won't matter). `date -Iseconds` works with both the gnu and BSD (e.g. apple) `date` command.

Comment (wthrowe) [reply tools/WrapExecutableLinker.sh]: Sure.  Changed.

**Review by nilsvu — APPROVED** [review]
