### PR TITLE
Fix memory issue 1018 in DomainHelpers

### LINKED ISSUE #1018: Heap buffer overflow in DomainHelpers
# Bug reports:

### Expected behavior:

No heap buffer overflows. This should be fixed ASAP.

### Current behavior:

Compiled with Clang 6.0.1 with `-D ASAN=ON` passed to CMake.

```
$ ./bin/RunTests Unit.Domain.DomainHelpers.SetCartesianPeriodicBoundaries1
Charm++: standalone mode (not using charmrun)
Charm++> Running in Multicore mode:  1 threads
Converse/Charm++ Commit ID: v6.8.0-0-ga36028edb
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (8-way SMP).
Charm++> cpu topology info is gathered in 0.001 seconds.
SpECTRE Build Information:
Version:                      0.0.0
Compiled on host:             NilsMBP
Compiled in directory:        /home/nils/SpECTRE/spectre/build_clang
Source directory is:          /home/nils/SpECTRE/spectre
Compiled on git branch:       develop
Compiled with git hash:       d9b17f202ac3c271bd3ee87d83f1198ee74bff4e
Linked on:                    Tue Oct  2 10:35:22 2018
=================================================================
==16235==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x617000003458 at pc 0x55981164b32f bp 0x7fff49304610 sp 0x7fff49304608
READ of size 4 at 0x617000003458 thread T0
    #0 0x55981164b32e in Direction<3ul>::dimension() const /home/nils/SpECTRE/spectre/build_clang/../src/Domain/Direction.hpp:40:66
    #1 0x55981164e9f8 in bool operator==<3ul>(Direction<3ul> const&, Direction<3ul> const&) /home/nils/SpECTRE/spectre/build_clang/../src/Domain/Direction.hpp:178:14
    #2 0x559811651d4e in bool std::__equal<false>::equal<Direction<3ul> const*, Direction<3ul> const*>(Direction<3ul> const*, Direction<3ul> const*, Direction<3ul> const*) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/bits/stl_algobase.h:800:22
    #3 0x559811651cd5 in bool std::__equal_aux<Direction<3ul> const*, Direction<3ul> const*>(Direction<3ul> const*, Direction<3ul> const*, Direction<3ul> const*) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/bits/stl_algobase.h:831:14
    #4 0x559811651c46 in bool std::equal<Direction<3ul> const*, Direction<3ul> const*>(Direction<3ul> const*, Direction<3ul> const*, Direction<3ul> const*) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/bits/stl_algobase.h:1049:14
    #5 0x559811651bf2 in bool std::operator==<Direction<3ul>, 3ul>(std::array<Direction<3ul>, 3ul> const&, std::array<Direction<3ul>, 3ul> const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/array:253:14
    #6 0x55981159a00c in operator==(OrientationMap<3ul> const&, OrientationMap<3ul> const&) /home/nils/SpECTRE/spectre/build_clang/../src/Domain/OrientationMap.hpp:88:36
    #7 0x5598174e2740 in std::unique_ptr<CoordinateMapBase<Frame::Logical, Frame::Inertial, 3ul>, std::default_delete<CoordinateMapBase<Frame::Logical, Frame::Inertial, 3ul> > > product_of_1d_maps<Frame::Inertial, CoordinateMaps::Affine>(std::array<CoordinateMaps::Affine, 3ul>&, OrientationMap<3ul> const&) /home/nils/SpECTRE/spectre/build_clang/../src/Domain/DomainHelpers.cpp:794:16
    #8 0x5598174e0b7a in std::vector<std::unique_ptr<CoordinateMapBase<Frame::Logical, Frame::Inertial, 3ul>, std::default_delete<CoordinateMapBase<Frame::Logical, Frame::Inertial, 3ul> > >, std::allocator<std::unique_ptr<CoordinateMapBase<Frame::Logical, Frame::Inertial, 3ul>, std::default_delete<CoordinateMapBase<Frame::Logical, Frame::Inertial, 3ul> > > > > maps_for_rectilinear_domains<Frame::Inertial, 3ul>(Index<3ul> const&, std::array<std::vector<double, std::allocator<double> >, 3ul> const&, std::vector<Index<3ul>, std::allocator<Index<3ul> > > const&, std::vector<OrientationMap<3ul>, std::allocator<OrientationMap<3ul> > > const&, bool) /home/nils/SpECTRE/spectre/build_clang/../src/Domain/DomainHelpers.cpp:842:26
    #9 0x5598174e39f1 in Domain<3ul, Frame::Inertial> rectilinear_domain<3ul, Frame::Inertial>(Index<3ul> const&, std::array<std::vector<double, std::allocator<double> >, 3ul> const&, std::vector<Index<3ul>, std::allocator<Index<3ul> > > const&, std::vector<OrientationMap<3ul>, std::allocator<OrientationMap<3ul> > > const&, std::array<bool, 3ul> const&, std::vector<PairOfFaces, std::allocator<PairOfFaces> > const&, bool) /home/nils/SpECTRE/spectre/build_clang/../src/Domain/DomainHelpers.cpp:925:15
    #10 0x55981219cded in ____C_A_T_C_H____T_E_S_T____69() /home/nils/SpECTRE/spectre/build_clang/../tests/Unit/Domain/Test_DomainHelpers.cpp:1273:23
    #11 0x5598104417aa in Catch::TestInvokerAsFunction::invoke() const /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:9870:9
    #12 0x559810432f45 in Catch::TestCase::invoke() const /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:9771:15
    #13 0x559810432d74 in Catch::RunContext::invokeActiveTestCase() /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:8655:27
    #14 0x55981042eb82 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:8630:17
    #15 0x55981042c4fe in Catch::RunContext::runTest(Catch::TestCase const&) /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:8419:13
    #16 0x5598104395f2 in Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:8967:39
    #17 0x559810437e1d in Catch::Session::runInternal() /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:9151:63
    #18 0x559810437854 in Catch::Session::run() /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:9108:24
    #19 0x55981043776b in Catch::Session::run(int, char**) /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:9076:26
    #20 0x55981046c4f2 in RunTests::RunTests(CkArgMsg*) /home/nils/SpECTRE/spectre/build_clang/../tests/Unit/RunTests.cpp:30:39
    #21 0x55981046cd10 in CkIndex_RunTests::_call_RunTests_CkArgMsg(void*, void*) /home/nils/SpECTRE/spectre/build_clang/./tests/Unit/RunTests.def.h:51:23
    #22 0x55981776511a in _initCharm(int, char**) (/home/nils/SpECTRE/spectre/build_clang/bin/RunTests+0xb99611a)
    #23 0x559817822a50 in ConverseRunPE (/home/nils/SpECTRE/spectre/build_clang/bin/RunTests+0xba53a50)
    #24 0x559817821393 in ConverseInit (/home/nils/SpECTRE/spectre/build_clang/bin/RunTests+0xba52393)
    #25 0x559817761ef8 in main (/home/nils/SpECTRE/spectre/build_clang/bin/RunTests+0xb992ef8)
    #26 0x7fd251f68222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)
    #27 0x55981030a02d in _start (/home/nils/SpECTRE/spectre/build_clang/bin/RunTests+0x453b02d)

0x617000003458 is located 0 bytes to the right of 728-byte region [0x617000003180,0x617000003458)
allocated by thread T0 here:
    #0 0x559810406991 in operator new(unsigned long) (/home/nils/SpECTRE/spectre/build_clang/bin/RunTests+0x4637991)
    #1 0x55981216d445 in __gnu_cxx::new_allocator<OrientationMap<3ul> >::allocate(unsigned long, void const*) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/ext/new_allocator.h:111:27
    #2 0x55981216d3eb in std::allocator_traits<std::allocator<OrientationMap<3ul> > >::allocate(std::allocator<OrientationMap<3ul> >&, unsigned long) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/bits/alloc_traits.h:436:20
    #3 0x55981216d322 in std::_Vector_base<OrientationMap<3ul>, std::allocator<OrientationMap<3ul> > >::_M_allocate(unsigned long) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/bits/stl_vector.h:296:20
    #4 0x5598175ebb5e in std::_Vector_base<OrientationMap<3ul>, std::allocator<OrientationMap<3ul> > >::_M_create_storage(unsigned long) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/bits/stl_vector.h:311:33
    #5 0x5598175eb7e4 in std::_Vector_base<OrientationMap<3ul>, std::allocator<OrientationMap<3ul> > >::_Vector_base(unsigned long, std::allocator<OrientationMap<3ul> > const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/bits/stl_vector.h:260:9
    #6 0x5598174d9b3f in std::vector<OrientationMap<3ul>, std::allocator<OrientationMap<3ul> > >::vector(unsigned long, OrientationMap<3ul> const&, std::allocator<OrientationMap<3ul> > const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../include/c++/8.2.1/bits/stl_vector.h:429:9
    #7 0x5598174e38de in Domain<3ul, Frame::Inertial> rectilinear_domain<3ul, Frame::Inertial>(Index<3ul> const&, std::array<std::vector<double, std::allocator<double> >, 3ul> const&, std::vector<Index<3ul>, std::allocator<Index<3ul> > > const&, std::vector<OrientationMap<3ul>, std::allocator<OrientationMap<3ul> > > const&, std::array<bool, 3ul> const&, std::vector<PairOfFaces, std::allocator<PairOfFaces> > const&, bool) /home/nils/SpECTRE/spectre/build_clang/../src/Domain/DomainHelpers.cpp:922:31
    #8 0x55981219cded in ____C_A_T_C_H____T_E_S_T____69() /home/nils/SpECTRE/spectre/build_clang/../tests/Unit/Domain/Test_DomainHelpers.cpp:1273:23
    #9 0x5598104417aa in Catch::TestInvokerAsFunction::invoke() const /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:9870:9
    #10 0x559810432f45 in Catch::TestCase::invoke() const /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:9771:15
    #11 0x559810432d74 in Catch::RunContext::invokeActiveTestCase() /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:8655:27
    #12 0x55981042eb82 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:8630:17
    #13 0x55981042c4fe in Catch::RunContext::runTest(Catch::TestCase const&) /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:8419:13
    #14 0x5598104395f2 in Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:8967:39
    #15 0x559810437e1d in Catch::Session::runInternal() /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:9151:63
    #16 0x559810437854 in Catch::Session::run() /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:9108:24
    #17 0x55981043776b in Catch::Session::run(int, char**) /home/nils/Research/spack/opt/spack/linux-archrolling-x86_64/gcc-7.3.0/catch-2.1.0-do5wfi3pmnb6rehs6q44jewsdwqxvnpp/include/catch.hpp:9076:26
    #18 0x55981046c4f2 in RunTests::RunTests(CkArgMsg*) /home/nils/SpECTRE/spectre/build_clang/../tests/Unit/RunTests.cpp:30:39
    #19 0x55981046cd10 in CkIndex_RunTests::_call_RunTests_CkArgMsg(void*, void*) /home/nils/SpECTRE/spectre/build_clang/./tests/Unit/RunTests.def.h:51:23
    #20 0x55981776511a in _initCharm(int, char**) (/home/nils/SpECTRE/spectre/build_clang/bin/RunTests+0xb99611a)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/nils/SpECTRE/spectre/build_clang/../src/Domain/Direction.hpp:40:66 in Direction<3ul>::dimension() const
Shadow bytes around the buggy address:
  0x0c2e7fff8630: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff8640: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff8650: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff8660: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff8670: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c2e7fff8680: 00 00 00 00 00 00 00 00 00 00 00[fa]fa fa fa fa
  0x0c2e7fff8690: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2e7fff86a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2e7fff86b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2e7fff86c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2e7fff86d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==16235==ABORTING
```

### PR DESCRIPTION
**Pull request by mar-celine**
## Proposed changes
Closes #1018 
Running with ASAN finds a heap overflow in DomainHelpers. This is caused by an indexing error in `maps_for_rectilinear_domain`. An ASSERT is added such that if an invalid OrientationMap is encountered, the ASSERT is triggered. A test is also added such that the test fails as expected when the mistake is present. Running with ASAN on with this fix results in no heap overflow in DomainHelpers.

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

File: src/Domain/CoordinateMaps/DiscreteRotation.cpp [hunk 1]
```diff
@@ -16,7 +16,20 @@ namespace CoordinateMaps {
 template <size_t VolumeDim>
 DiscreteRotation<VolumeDim>::DiscreteRotation(
     OrientationMap<VolumeDim> orientation) noexcept
-    : orientation_(std::move(orientation)) {}
+    : orientation_(std::move(orientation)) {
+  ASSERT(
+      [&orientation]() {
+        std::set<size_t> set_of_dims;
```
Comment (nilsdeppe) [inline src/Domain/CoordinateMaps/DiscreteRotation.cpp]: You're missing an include for `std::set`

File: src/Domain/CoordinateMaps/DiscreteRotation.cpp [hunk 2]
```diff
@@ -16,7 +16,20 @@ namespace CoordinateMaps {
...
+        for (size_t j = 0; j < VolumeDim; j++) {
+          set_of_dims.insert(
+              orientation(gsl::at(Direction<VolumeDim>::all_directions(), j))
+                  .dimension());
+        }
+        return set_of_dims.size() == VolumeDim;
+      }(),
+      "OrientationMap is invalid! "
+      "You might be indexing into a vector of OrientationMaps incorrectly.");
```
Comment (nilsdeppe) [inline src/Domain/CoordinateMaps/DiscreteRotation.cpp]: Could you print some info for the user to be able to external diagnose the issue without having to add more print statements in here?

File: src/Domain/DomainHelpers.cpp [hunk 3]
```diff
@@ -874,6 +874,12 @@ maps_for_rectilinear_domains(
   std::vector<std::unique_ptr<
       CoordinateMapBase<Frame::Logical, TargetFrame, VolumeDim>>>
       maps{};
+  // Tracks the value of the collapsed index of the IndexIterator ii,
```
Comment (nilsdeppe) [inline src/Domain/DomainHelpers.cpp]: I found the use of the word `Tracks` confusing. Maybe start with something like "almost_collapsed_index is equal to IndexIterator.collapsed_index() except in the case where...."

**Review by nilsdeppe — CHANGES_REQUESTED** [review]

**Comment by fmahebert** [comment]
Question for my own understanding: why are you adding the sanity check ASSERTs to the code that uses the OrientationMap, instead of in OrientationMap itself? Would it not be better to disallow constructing OrientationMaps that don't correspond to reasonable orientations?

**Comment by nilsdeppe** [comment]
I *think* no constructor is called if you read off the end of an array, the memory is just interpreted incorrectly. If that is true then a check in a constructor doesn't help you.

File: src/Domain/OrientationMap.hpp [hunk 4]
```diff
@@ -140,6 +140,18 @@ std::array<tt::remove_cvref_wrap_t<T>, VolumeDim> discrete_rotation(
...
   std::array<ReturnType, VolumeDim> new_coords{};
+  ASSERT(
+      [&rotation]() {
+        std::set<size_t> set_of_dims;
+        for (size_t j = 0; j < VolumeDim; j++) {
+          set_of_dims.insert(
+              rotation(gsl::at(Direction<VolumeDim>::all_directions(), j))
+                  .dimension());
+        }
+        return set_of_dims.size() == VolumeDim;
```
Comment (wthrowe) [inline src/Domain/OrientationMap.hpp]: There are now three (near) copies of this block throughout the code.  Put it in a method or something.

File: src/Domain/OrientationMap.hpp [hunk 5]
```diff
@@ -140,6 +140,18 @@ std::array<tt::remove_cvref_wrap_t<T>, VolumeDim> discrete_rotation(
     std::array<T, VolumeDim> source_coords) noexcept {
   using ReturnType = tt::remove_cvref_wrap_t<T>;
   std::array<ReturnType, VolumeDim> new_coords{};
+  ASSERT(
+      [&rotation]() {
+        std::set<size_t> set_of_dims;
+        for (size_t j = 0; j < VolumeDim; j++) {
+          set_of_dims.insert(
+              rotation(gsl::at(Direction<VolumeDim>::all_directions(), j))
```
Comment (wthrowe) [inline src/Domain/OrientationMap.hpp]: Use a range-based loop.

**Review by wthrowe — CHANGES_REQUESTED** [review]
As a higher level comment, I agree with @fmahebert that this isn't checking things in the right place.  (Although a check in the constructor won't work, as @nilsdeppe said.)  If any of these checks triggers you've already done an invalid read and hit undefined behavior.  You should check that you're not reading garbage rather than having unrelated functions try to guess whether they've been passed invalid memory.

**Comment by fmahebert** [comment]
Don't we use `gsl::at` to check bounds in debug builds? perhaps a combination of sanity checks in the OrientationMap constructor (because it's a good idea in general), and a `gsl::at` when reading from the vector (to catch this bug) is the way to go?

File: src/Domain/DomainHelpers.cpp [hunk 6]
```diff
@@ -874,6 +874,12 @@ maps_for_rectilinear_domains(
...
+  // except in the case where block_indices_to_exclude.size() != 0,
+  // in which case almost_collapsed_index does not get incremented
+  // (ii.collapsed_index() would be incremented, and would lead to
+  // out-of-bounds indexing into the orientations_of_all_blocks array.
+  size_t almost_collapsed_index = 0;
```
Comment (moxcodes) [inline src/Domain/DomainHelpers.cpp]: The intent would be clearer if the variable name was `orientation_index`.

File: src/Domain/DomainHelpers.cpp [hunk 7]
```diff
@@ -874,6 +874,12 @@ maps_for_rectilinear_domains(
   std::vector<std::unique_ptr<
       CoordinateMapBase<Frame::Logical, TargetFrame, VolumeDim>>>
       maps{};
+  // Tracks the value of the collapsed index of the IndexIterator ii,
+  // except in the case where block_indices_to_exclude.size() != 0,
```
Comment (moxcodes) [inline src/Domain/DomainHelpers.cpp]: The comment could be updated with the variable name to say something along the lines of `orientation_index is the index into orientations_of_all_blocks, and does not get incremented if a block is excluded.`

File: src/Domain/DomainHelpers.cpp (hunk 3 above)
Comment (kidder) [reply src/Domain/DomainHelpers.cpp]: I think `almost_collapsed_index` should just be renamed `block_id` or `block_index` as that is what it corresponds to.

File: src/Domain/OrientationMap.hpp (hunk 4 above)
Comment (kidder) [reply src/Domain/OrientationMap.hpp]: called something like `is_valid_rotation` or `is_valid_orientation_map`?

**Review by kidder — CHANGES_REQUESTED** [review]

File: tests/Unit/Domain/Test_DomainHelpers.cpp [hunk 8]
```diff
@@ -1404,10 +1404,20 @@ SPECTRE_TEST_CASE("Unit.Domain.DomainHelpers.SetCartesianPeriodicBoundaries1",
           {{Direction<3>::upper_zeta(), Direction<3>::upper_eta()}},
           {{Direction<3>::upper_zeta(), Direction<3>::upper_eta()}},
           {{Direction<3>::upper_zeta(), Direction<3>::upper_eta()}}};
+  const std::vector<
```
Comment (moxcodes) [inline tests/Unit/Domain/Test_DomainHelpers.cpp:1421]: If this test would fail in the case of the out-of-bounds index, there should be a comment describing the bug it finds and some short description of how.

**Comment by kidder** [comment]
I also agree with @wthrowe and @fmahebert .  I don't think `ASSERT`s should be added unless it is somehow possible to construct an invalid OrientationMap within one of its constructors (and if so, the ASSERT should be in that constructor).  We shouldn't be adding `ASSERT`s to check for side effects from undefined behavior.  If removing your `ASSERT`s causes the modified test to still pass with the bug, then you need to modify the test...

**Review by moxcodes — CHANGES_REQUESTED** [review]
group code review with @fmahebert and @markscheel

**Comment by kidder** [comment]
I am happy with the fixups.  Please wait for @wthrowe @nilsdeppe @moxcodes to confirm before squashing

**Comment by moxcodes** [comment]
I'm happy with it.

**Review by nilsdeppe — COMMENTED** [review]
LGTM :+1:

**Comment by wthrowe** [comment]
Looks good.  Squash.

**Review by nilsdeppe — APPROVED** [review]
@kidder @moxcodes @wthrowe could you please give feedback now that this has been squashed? Thanks!

**Review by wthrowe — APPROVED** [review]

**Review by moxcodes — APPROVED** [review]

**Review by fmahebert — APPROVED** [review]

**Review by kidder — APPROVED** [review]

**Comment by kidder** [comment]
Travis failure is #1031
