### PR TITLE
Prevent implicit conversion of double to Rational

### LINKED ISSUE #2209: Disable Rational and TimeDelta math with doubles
# Bug reports:

### Expected behavior:

Math operations between `Rational` and `TimeDelta` should result in a compiler error. This can be achieved by explicitly deleting them:
```cpp
TimeDelta operator*(TimeDelta a, double b) noexcept = delete;
TimeDelta operator*(double a, TimeDelta b) noexcept = delete;
```

### Current behavior:

Currently if we multiply `TimeDelta` or `Rational` by a `double` the `double` is silently converted to an integer (not a rational) which results in incorrect values. For example, in the `DormandPrince5` stepper we have
```cpp
gsl::at(_c, step) * time_step
```
where `_c` is an array of `double`s and `time_step` is a `TimeDelta`. All the `_c`s are less than 1 and so the result is always zero.

### PR DESCRIPTION
**Pull request by wthrowe**
Fixes #2209

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by fmahebert — DISMISSED** [review]

File: src/Utilities/Rational.hpp [hunk 1]
```diff
@@ -23,10 +26,15 @@ class er;
...
-           std::int32_t denominator = 1) noexcept;
+  Rational() = default;
+  Rational(std::int32_t numerator, std::int32_t denominator) noexcept;
+
+  // Allow implicit conversion of integers to Rationals, but don't
+  // allow doubles to implicitly convert to an integer and then to a
+  // Rational.
+  template <typename T, Requires<tt::is_integer_v<T>> = nullptr>
+  // NOLINTNEXTLINE(google-explicit-constructor)
+  Rational(const T integral_value) : Rational(integral_value, 1) {}
```
Comment (nilsdeppe) [inline src/Utilities/Rational.hpp:37]: clang-tidy also seems to think this is a declaration, not a definition. Do you want to `NOLINT` that as well?

**Review by nilsdeppe — DISMISSED** [review]

File: src/Utilities/Rational.hpp (hunk 1 above)
Comment (wthrowe) [reply src/Utilities/Rational.hpp:37]: Adding that const was literally the only change I made after running clang-tidy locally.

Comment (nilsdeppe) [reply src/Utilities/Rational.hpp:37]: Of course that's the thing that hits a clang-tidy bug :(

**Review by nilsdeppe — APPROVED** [review]

**Review by fmahebert — APPROVED** [review]
