### PR TITLE
Remove dependence on timing for checkpoint-restart

### LINKED ISSUE #6472: InputFiles.ScalarWave.PlaneWave2D.yaml.execute - failure with no error
Seen on Mac CI for a PR with no relevant changes.  Likely related to #5585.  Possibly relevant that the second run appears to have never entered the Evolve phase.

This is probably two bugs: one that the test failed and one that there is no error message.

```
2025-02-04T17:27:41.2421880Z   95/1636 Test   #94: InputFiles.ScalarWave.PlaneWave2D.yaml.execute .....................................***Failed   12.37 sec
2025-02-04T17:27:41.3340490Z The following options differ from their suggested values:
2025-02-04T17:27:41.3488330Z Charm++> No provisioning arguments specified. Running with a single PE.
2025-02-04T17:27:41.3538950Z          Use +auto-provision to fully subscribe resources or +p1 to silence this message.
2025-02-04T17:27:41.3879540Z Charm++: standalone mode (not using charmrun)
2025-02-04T17:27:41.4186920Z Charm++> Running in Multicore mode: 1 threads (PEs)
2025-02-04T17:27:41.4204670Z Converse/Charm++ Commit ID: v70000
2025-02-04T17:27:41.4372240Z CharmLB> Load balancer assumes all CPUs are same.
2025-02-04T17:27:41.4710720Z Charm++> Running on 1 hosts (1 sockets x 4 cores x 1 PUs = 4-way SMP)
2025-02-04T17:27:41.4735400Z Charm++> cpu topology info is gathered in 0.000 seconds.
2025-02-04T17:27:41.4774800Z 
2025-02-04T17:27:41.4798950Z Executing 'EvolveScalarWave2D' using 1 processors.
2025-02-04T17:27:41.4914510Z Launch command line: /Users/runner/work/spectre/spectre/build/bin/EvolveScalarWave2D --input-file /Users/runner/work/spectre/spectre/tests/InputFiles/ScalarWave/PlaneWave2D.yaml
2025-02-04T17:27:41.4959450Z Charm++ startup time in seconds: 0.042780
2025-02-04T17:27:41.4964700Z Date and time at startup: Tue Feb  4 17:27:34 2025
2025-02-04T17:27:41.5037260Z 
2025-02-04T17:27:41.5432250Z SpECTRE Build Information:
2025-02-04T17:27:41.5851890Z Version:                      2025.01.30
2025-02-04T17:27:41.5898880Z Compiled on host:             Mac-1738687453950.local
2025-02-04T17:27:41.5936860Z Compiled in directory:        /Users/runner/work/spectre/spectre/build
2025-02-04T17:27:41.6005020Z Source directory is:          /Users/runner/work/spectre/spectre
2025-02-04T17:27:41.6293390Z Compiled on git branch:       HEAD
2025-02-04T17:27:41.6945450Z Compiled on git revision:     66e7d40
2025-02-04T17:27:41.6998920Z Linked on:                    Tue Feb  4 16:50:15 2025
2025-02-04T17:27:41.7010680Z Build type:                   Debug
2025-02-04T17:27:41.7440220Z 
2025-02-04T17:27:41.7518580Z 
2025-02-04T17:27:41.8227550Z Option parsing completed.
2025-02-04T17:27:41.8446890Z 
2025-02-04T17:27:41.8669130Z Allocating Singletons:
2025-02-04T17:27:41.9151790Z Component on node 0, global proc 0, exclusive = false
2025-02-04T17:27:41.9491530Z 
2025-02-04T17:27:41.9495820Z 
2025-02-04T17:27:41.9498450Z Parallel components:
2025-02-04T17:27:41.9793000Z   Component (Singleton) has a DataBox with 22 items.
2025-02-04T17:27:42.0083800Z   Observer (Group) has a DataBox with 32 items.
2025-02-04T17:27:42.0174530Z   ObserverWriter (Nodegroup) has a DataBox with 38 items.
2025-02-04T17:27:42.0464780Z   DgElementArray (Array) has a DataBox with 83 items.
2025-02-04T17:27:42.0500060Z 
2025-02-04T17:27:42.0547690Z 
2025-02-04T17:27:42.0913130Z ----- Domain Info -----
2025-02-04T17:27:42.1313360Z Total blocks: 1
2025-02-04T17:27:42.1584290Z Total elements: 16
2025-02-04T17:27:42.2207140Z Total grid points: 256
2025-02-04T17:27:42.2380010Z Number of cores: 1
2025-02-04T17:27:42.2440770Z Number of nodes: 1
2025-02-04T17:27:42.2445010Z Elements per core: (16)
2025-02-04T17:27:42.2561810Z Elements per node: (16)
2025-02-04T17:27:42.2676540Z Grid points per core: (256)
2025-02-04T17:27:42.2894620Z Grid points per node: (256)
2025-02-04T17:27:42.2927570Z -----------------------
2025-02-04T17:27:42.3224170Z 
2025-02-04T17:27:42.3360920Z Entering phase: InitializeTimeStepperHistory at time 00:00:00
2025-02-04T17:27:42.3381200Z Entering phase: Register at time 00:00:00
2025-02-04T17:27:42.3476110Z Entering phase: CheckDomain at time 00:00:00
2025-02-04T17:27:42.3849490Z Number of elements: 16
2025-02-04T17:27:42.4053330Z Number of grid points: 256
2025-02-04T17:27:42.4178010Z Average refinement levels: (2,2)
2025-02-04T17:27:42.4445890Z Average grid points: (4,4)
2025-02-04T17:27:42.4571110Z 
2025-02-04T17:27:42.4595880Z Entering phase: Evolve at time 00:00:00
2025-02-04T17:27:42.4808060Z Entering phase from phase control: WriteCheckpoint at time 00:00:00
2025-02-04T17:27:42.4844850Z [0] Checkpoint starting in Checkpoints/Checkpoint_0000
2025-02-04T17:27:42.4867450Z Checkpoint to disk finished in 0.173588s, sending out the cb...
2025-02-04T17:27:42.4870820Z Entering phase from phase control: Exit at time 00:00:00
2025-02-04T17:27:42.4874140Z 
2025-02-04T17:27:42.5050840Z Done!
2025-02-04T17:27:42.5131880Z Wall time: 00:00:00
2025-02-04T17:27:42.5156440Z Date and time at completion: Tue Feb  4 17:27:35 2025
2025-02-04T17:27:42.5631110Z 
2025-02-04T17:27:42.5734260Z [Partition 0][Node 0] End of program
2025-02-04T17:27:42.5736950Z The following options differ from their suggested values:
2025-02-04T17:27:42.5739120Z Charm++> No provisioning arguments specified. Running with a single PE.
2025-02-04T17:27:42.5741530Z          Use +auto-provision to fully subscribe resources or +p1 to silence this message.
2025-02-04T17:27:42.5744310Z Charm++: standalone mode (not using charmrun)
2025-02-04T17:27:42.5746740Z Charm++> Running in Multicore mode: 1 threads (PEs)
2025-02-04T17:27:42.5750580Z Converse/Charm++ Commit ID: v70000
2025-02-04T17:27:42.6001220Z CharmLB> Load balancer assumes all CPUs are same.
2025-02-04T17:27:42.6010530Z Charm++> Running on 1 hosts (1 sockets x 4 cores x 1 PUs = 4-way SMP)
2025-02-04T17:27:42.6120920Z Charm++> cpu topology info is gathered in 0.000 seconds.
2025-02-04T17:27:42.6166110Z [0]CkRestartMain done. sending out callback.
2025-02-04T17:27:42.6327190Z Restarting from checkpoint. Date and time: 2025-02-04 17:27:41 UTC
2025-02-04T17:27:42.6693400Z Entering phase from phase control: UpdateOptionsAtRestartFromCheckpoint at time 00:00:00
2025-02-04T17:27:42.6764210Z Attempting to overlay input file: /Users/runner/work/spectre/spectre/tests/InputFiles/ScalarWave/PlaneWave2D.overlay_0000.yaml
2025-02-04T17:27:42.6767560Z ... success!
2025-02-04T17:27:42.6772060Z Entering phase from phase control: Exit at time 00:00:00
2025-02-04T17:27:42.6840960Z 
2025-02-04T17:27:42.6843460Z Done!
2025-02-04T17:27:42.6844570Z Wall time: 00:00:00
2025-02-04T17:27:42.6845650Z Date and time at completion: Tue Feb  4 17:27:41 2025
2025-02-04T17:27:42.6846390Z 
2025-02-04T17:27:42.6846590Z [Partition 0][Node 0] End of program
2025-02-04T17:27:42.6847390Z 
```

### PR DESCRIPTION
**Pull request by wthrowe**
Fixes #6472.

That issue was caused by checkpoint-restart determining whether it was terminating or restarting based on wall-clock time.  That could fail in a test where the time at checkpoint was very small, so it is replaced by an internal non-checkpointed flag.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsvu — DISMISSED** [review]

File: src/Parallel/PhaseControl/CheckpointAndExitAfterWallclock.hpp [hunk 1]
```diff
@@ -174,15 +157,17 @@ struct CheckpointAndExitAfterWallclock : public PhaseChange {
 
  private:
   std::optional<double> wallclock_hours_for_checkpoint_and_exit_ = std::nullopt;
+  // Phase arbitration is only run from Main, so there are no
+  // threading issues here.
+  // NOLINTNEXTLINE(spectre-mutable)
+  mutable bool halting_ = false;
```
Comment (nilsvu) [inline src/Parallel/PhaseControl/CheckpointAndExitAfterWallclock.hpp:168]: What makes sure that this flag is not checkpointed? Is it that it doesn't participate in pup? Would be good to add a comment about this logic I think

Comment (wthrowe) [reply src/Parallel/PhaseControl/CheckpointAndExitAfterWallclock.hpp:168]: I added some text about how the flag is used, and modified the test so that it will fail if someone adds the field to the pup function.

**Review by nilsvu — APPROVED** [review]
