### PR TITLE
Make YlmSpherepack threadsafe

### LINKED ISSUE #3929: Make YlmSpherepack threadsafe
# Bug reports:

[Note that this problem exists for other classes in addition to YlmSpherepack (basically everything that has mutable member variables and that will live on a NodeGroup)].

### Expected behavior:

YlmSpherepack should be threadsafe, so if you put a YlmSpherepack in a NodeGroup, nothing bad will happen.

### Current behavior:

Currently, YlmSpherpack has mutable member variables, so if stored in a NodeGroup there can be race conditions and undefined behavior if different threads call different member functions simultaneously.

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Detailed discussion:

There are three different classes of storage that are used in YlmSpherepack, which are all currently inside `mutable` member variables.
1. Things like `quadrature_weights_` that are allocated/computed in the `YlmSpherepack` constructor and used by various member functions.  These can be made non-`mutable` and still be computed in the constructor since they never need to change.
2. Temporary storage used in the `YlmSpherepack` constructor. These can now be allocated in the constructor and thrown away after use.
3. There are some quantities that are stored and returned by member functions but not re-used elsewhere.  These can be passed by `gsl::not_null` in those member functions instead of being stored internally.
4. Temporary storage that is needed in various `YlmSpherepack` member functions and is immediately thrown away after use, such as buffers that get passed into the Spherepack fortran routines.  For these, each such member function can take an extra buffer argument as suggested by @nilsdeppe and can also have its own buffer_size function so that anything calling it can determine the size of the buffer it needs to pass.
```
size_t spec_to_phys_buffer_size() const {...} // generally depends on l_max, m_max
void spec_to_phys(const gsl::not_null<gsl::span<double>*> buffer,other_args) const {
   const size_t buffer_size = spec_to_phys_buffer_size();
   DataVector local_buffer{};
   if (buffer->size() == 0 ) {
      local_buffer = DataVector(buffer_size);
      *buffer = gsl::make_span(local_buffer.data(),local_buffer.size());
  } else if (UNLIKELY(buffer->size() != buffer_size)) {
      ERROR("Buffer has wrong size, you should do X"....);
  }
  // ... rest of member function same as before except it uses buffer  ...
}
```

Note that for 4. above, some member functions call other member functions.  Suppose A calls B.  Then we can do things like
```
void A_buffer_size() const {return B_buffer_size() + whatever_size_A_needs_in_addition_to_what_B_needs;}
void A(const gsl::not_null<gsl::span<double>*> buffer,other_args) const {
  // ... do stuff ...

  // Now need to call B
  gsl::span<double> B_buffer = gsl::make_span(buffer->data()+A_buffer_size()-B_buffer_size(),B_buffer_size());
  B(make_not_null(&B_buffer), ...);
}
```

### PR DESCRIPTION
**Pull request by markscheel**
## Proposed changes

Uses thread_local storage to make YlmSpherepack threadsafe.  Fixes #3929

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by nilsdeppe — COMMENTED** [review]
LGTM, I think this should fix the issue :)

File: src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepack.hpp [hunk 1]
```diff
@@ -437,13 +448,14 @@ class YlmSpherepack {
...
-  void fill_vector_work_arrays() const;
+  void calculate_collocation_points();
+  void calculate_interpolation_data();
+  void fill_scalar_work_arrays();
+  void fill_vector_work_arrays();
   size_t l_max_, m_max_, n_theta_, n_phi_;
   size_t spectral_size_;
-  mutable YlmSpherepack_detail::MemoryPool memory_pool_;
-  mutable YlmSpherepack_detail::Storage storage_;
+  static thread_local YlmSpherepack_detail::MemoryPool memory_pool_;
```
Comment (nilsvu) [inline src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepack.hpp:463]: What happens when multiple YlmSpherepack objects are around? Won't they all use the same memory pool since it's static?

Can these scenarios be unit-tested?

Also, I think some more code comments and/or dox explaining the design choices here would be helpful.

**Comment by markscheel** [comment]
Added code comments addressing @nilsvu 's concern.

Also removed the destructor.  I realized that having the destructor as it was would just increase the number of memory allocations but (probably) would not save much memory.

**Review by nilsdeppe — DISMISSED** [review]

**Comment by markscheel** [comment]
Rebased on develop.

File: src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepackHelper.cpp [hunk 2]
```diff
@@ -167,4 +167,13 @@ void MemoryPool::free(const gsl::not_null<double*> to_be_freed) {
   ERROR("Attempt to free temp that was never allocated.");
 }
 
+void MemoryPool::clear() {
+  for (auto& elem : memory_pool_) {
+    if(elem.currently_in_use) {
```
Comment (nilsdeppe) [inline src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepackHelper.cpp:172]: Is this `clear()` function really not being tested? If so, could you add (or extend) the tests to cover it?

**Review by nilsdeppe — COMMENTED** [review]
Overall LGTM, just one question

File: src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepackHelper.cpp (hunk 2 above)
Comment (markscheel) [reply src/NumericalAlgorithms/SphericalHarmonics/YlmSpherepackHelper.cpp:172]: Ok, I did that and even more.   My new commit changes all the error tests in Test_YlmSpherepack into CHECK_THROWS_WITH.

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsvu** [comment]
@markscheel since you mentioned this at the meeting today, I don't have the time to review this at the moment, so please don't wait for my review here. Maybe @wthrowe or @nikwit could provide the second review.

**Comment by wthrowe** [comment]
Looks good, and I think your change addresses @nilsvu's request.  Squash.

**Review by nilsdeppe — APPROVED** [review]

**Review by wthrowe — APPROVED** [review]
