### PR TITLE
Fix circular dependency for Parallel/PhaseControl

### LINKED ISSUE #3163: Cyclic dependency between EventsAndTriggers and Parallel/PhaseControl
This came up in this thread: https://github.com/sxs-collaboration/spectre/pull/3141#discussion_r628316172

### PR DESCRIPTION
**Pull request by moxcodes**
## Proposed changes

Fixes #3163 by creating a new library for the `PhaseControl` directory, and moving the tags to `Parallel`

### Upgrade instructions

Includes will need to be updated to `Parallel/PhaseControlTags.hpp`, and anything that uses the `PhaseControl` features likely needs to link the `PhaseControl` library.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

File: src/Parallel/Main.hpp [hunk 1]
```diff
@@ -19,7 +19,7 @@
 #include "Parallel/CreateFromOptions.hpp"
 #include "Parallel/GlobalCache.hpp"
 #include "Parallel/ParallelComponentHelpers.hpp"
-#include "Parallel/PhaseControl/PhaseControlTags.hpp"
+#include "Parallel/PhaseControlTags.hpp"
```
Comment (nilsvu) [inline src/Parallel/Main.hpp]: I believe `Main` doesn't actually depend on the tags, but only needs the metafunctions `PhaseControl::TaggedTupleCombine`, `PhaseControl::TaggedTupleMainCombine` and `PhaseControl::reduction_data`. And those actually seem quite independent of any of the `PhaseControl` code. Furthermore, AFAICT those metafunctions are _not_ used in the `PhaseControl` code at all. Can you just move those to `Parallel`? That seems to decouple the libraries.

File: src/Parallel/PhaseControl/CMakeLists.txt [hunk 2]
```diff
@@ -1,12 +1,24 @@
...
   VisitAndReturn.hpp
   )
+
+target_link_libraries(
+  ${LIBRARY}
+  INTERFACE
+  DataStructures
+  EventsAndTriggers
+  Options
+  Utilities
```
Comment (nilsvu) [inline src/Parallel/PhaseControl/CMakeLists.txt:25]: This list is missing `Parallel`.

File: src/Parallel/PhaseControlTags.hpp [hunk 3]
```diff
@@ -9,14 +9,18 @@
...
 #include "Parallel/Serialize.hpp"
-#include "ParallelAlgorithms/EventsAndTriggers/Trigger.hpp"
 #include "Utilities/Registration.hpp"
 #include "Utilities/TMPL.hpp"
 #include "Utilities/TaggedTuple.hpp"
 
+/// \cond
+class Trigger;
+template <typename PhaseChangeRegistrars>
+struct PhaseChange;
```
Comment (nilsvu) [inline src/Parallel/PhaseControlTags.hpp]: When you only move the metafunctions to `Parallel` and keep this file in `PhaseControl` you can keep the dependency of `PhaseControl` on `EventsAndTriggers`. It might be appropriate to move `PhaseControl` to `ParallelAlgorithms/` at that point, but there's no need to do that in this PR. Just something for you to consider.

**Review by nilsvu — CHANGES_REQUESTED** [review]

**Comment by moxcodes** [comment]
Squashed in the fixups, because the diff was largely rewritten for the suggested changes.
Cheers!

File: tests/Unit/Parallel/Test_PhaseChangeMain.cpp [hunk 4]
```diff
@@ -20,6 +20,7 @@
 #include "Parallel/Main.hpp"
 #include "Parallel/ParallelComponentHelpers.hpp"
 #include "Parallel/PhaseControl/PhaseControlTags.hpp"
+#include "Parallel/PhaseControlReductionHelpers.hpp"
```
Comment (nilsvu) [inline tests/Unit/Parallel/Test_PhaseChangeMain.cpp:23]: The two algorithm tests `Test_AlgorithmPhaseControl.cpp` and `Test_PhaseChangeMain.cpp` probably need to link `PhaseControl`.

**Review by nilsvu — DISMISSED** [review]
LGTM, please squash when fixing the CI error and this one comment. There's no need for me to approve again.

**Review by kidder — APPROVED** [review]

**Review by nilsvu — APPROVED** [review]
