### PR TITLE
Fix Git hooks and have Travis check formatting

### LINKED ISSUE #63: Git hooks can go wrong after some git operations.
This ticket is to document an issue I encountered, but am not sure how to reproduce:

**Bad git operations can leave the git hooks in a state that prevents normal work in the repository**

Here's what I know:

I (somehow) messed up an interactive rebase, and attempted to reset to a pre-rebase state with `git reset --hard HEAD@{N}`. The tracked files were restored as expected.

However, I was then unable to run most git commands (e.g. `git commit --amend`) due to two files triggering the pre-commit hook for having lines over 80 chars. These files are:
```
build/CMakeFiles/3.8.0/CompilerIdCxx/CmakeCXXCompilerId.cpp
tests/Unit/Numerical/Spectral/Test_DefiniteIntegral.cpp
```
It is true that both of these files have lines over 80 chars (*). But as I had no local changes to these files, I would not expect the git hooks to prevent me from committing other changes. Ultimately I resolved the problem by `rm -r .git/hooks`. I suspect a cached file in this directory ended up in a bad state during the broken rebase/reset process.

If anyone else encounters this problem, please comment with any further information!

---

(*) The CMake file is not tracked by the repo, but the test is. This brings up two secondary issues:
1. The git hook should probably not trigger on a CMake-generated file.
2. How did our test get past the 80-char git hooks??

### PR DESCRIPTION
**Pull request by nilsdeppe**
- Git hooks are no longer run erroneously on all files if no files were modified or added.
- Travis checks basic formatting on the entire repository.

fix #63

### CODE REVIEW

File: tools/Hooks/pre-commit.sh [hunk 1]
```diff
@@ -22,6 +22,13 @@ do
     fi
 done
 
+# If no files were added or modified we do not run any of the hooks. If we did
+# then rewording commits, and making empty commits would result in the hooks
+# searching the entire repository, which is not what we want in general.
+if [ -z "$commit_files" ]; then
```
Comment (wthrowe) [inline tools/Hooks/pre-commit.sh:28]: There's another check for this later in the script, which can now be removed.

**Review by wthrowe — CHANGES_REQUESTED** [review]

File: tools/Hooks/pre-commit.sh (hunk 1 above)
Comment (nilsdeppe) [reply tools/Hooks/pre-commit.sh:28]: Okay, removed!

**Review by fmahebert — APPROVED** [review]

**Review by osheamonn — APPROVED** [review]
