### PR TITLE
Fix gcc8 issues

### LINKED ISSUE #1026: Fix SPHEREPACK warnings with GCC8
# Bug reports:

### Expected behavior:

SPHEREPACK compiles without warnings.

I have both a lack of fortran knowledge and a lack of SPHEREPACK knowledge to be able to determine whether these warnings are legit and what should be done about them.

### Current behavior:

```
../external/SPHEREPACK/alf.f:658:22:

../external/SPHEREPACK/alf.f:654:72:

       do  60 kp1=2,kdo
                                                                        2
../external/SPHEREPACK/alf.f:658:22:

          sum = sum+cp(kp1)*ct
                      1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/alf.f:504:39:

../external/SPHEREPACK/alf.f:500:72:

       do 15 np1=2,nmp1
                                                                        2
../external/SPHEREPACK/alf.f:504:39:

       call lfpt(nh,0,theta(i),cp,phz(i,np1))
                                       1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/alf.f:508:39:

../external/SPHEREPACK/alf.f:500:72:

       do 15 np1=2,nmp1
                                                                        2
../external/SPHEREPACK/alf.f:508:39:

       call lfpt(nh,1,theta(i),cp,ph1(i,np1))
                                       1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/alf.f:524:11:

../external/SPHEREPACK/alf.f:522:72:

    30 do 50 np1=2,nmp1
                                                                        2
../external/SPHEREPACK/alf.f:524:11:

       p3(i,np1) = ph1(i,np1)
           1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/alf.f:524:24:

../external/SPHEREPACK/alf.f:522:72:

    30 do 50 np1=2,nmp1
                                                                        2
../external/SPHEREPACK/alf.f:524:24:

       p3(i,np1) = ph1(i,np1)
                        1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/alf.f:525:11:

../external/SPHEREPACK/alf.f:522:72:

    30 do 50 np1=2,nmp1
                                                                        2
../external/SPHEREPACK/alf.f:525:11:

       p2(i,np1) = ph1(i,np1)
           1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/alf.f:525:24:

../external/SPHEREPACK/alf.f:522:72:

    30 do 50 np1=2,nmp1
                                                                        2
../external/SPHEREPACK/alf.f:525:24:

       p2(i,np1) = ph1(i,np1)
                        1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
[5:30/599-10.185]Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/sphcom.f.o
../external/SPHEREPACK/sphcom.f:214:24:

../external/SPHEREPACK/sphcom.f:212:72:

       do 170 k=1,kdo
                                                                        2
../external/SPHEREPACK/sphcom.f:214:24:

       pb = pb-2.d0*k*cp(k+1)*sth
                        1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:563:17:

../external/SPHEREPACK/sphcom.f:561:72:

       do 201 k=2,lq
                                                                        2
../external/SPHEREPACK/sphcom.f:563:17:

       zh = zh+cz(k)*cth
                 1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:576:17:

../external/SPHEREPACK/sphcom.f:574:72:

       do 202 k=1,ls
                                                                        2
../external/SPHEREPACK/sphcom.f:576:17:

       zh = zh+cz(k+1)*sth
                 1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:603:17:

../external/SPHEREPACK/sphcom.f:601:72:

       do 204 k=1,lq
                                                                        2
../external/SPHEREPACK/sphcom.f:603:17:

       zh = zh+cz(k+1)*sth
                 1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:621:17:

../external/SPHEREPACK/sphcom.f:619:72:

       do 50 k=2,lc
                                                                        2
../external/SPHEREPACK/sphcom.f:621:17:

       zh = zh+cz(k)*cth
                 1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:634:17:

../external/SPHEREPACK/sphcom.f:632:72:

       do 70 k=1,lq
                                                                        2
../external/SPHEREPACK/sphcom.f:634:17:

       zh = zh+cz(k+1)*sth
                 1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:662:17:

../external/SPHEREPACK/sphcom.f:660:72:

       do 120 k=1,lq
                                                                        2
../external/SPHEREPACK/sphcom.f:662:17:

       zh = zh+cz(k+1)*sth
                 1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1745:23:

../external/SPHEREPACK/sphcom.f:1743:72:

       do 55 l=1,ncv
                                                                        2
../external/SPHEREPACK/sphcom.f:1745:23:

       cv(l) = -fk*work(l+1)/srnp1
                       1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1411:20:

       do 10 k=1,ls
                                                                        2
       zvh = zvh+czv(k+1)*sth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1422:20:

       do 20 k=2,lq
                                                                        2
       zvh = zvh+czv(k)*cth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1434:20:

       do 30 k=1,lq
                                                                        2
       zvh = zvh+czv(k+1)*sth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1458:20:

       do 55 k=1,lq
                                                                        2
       zvh = zvh+czv(k+1)*sth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1469:20:

       do 57 k=2,lc
                                                                        2
       zvh = zvh+czv(k)*cth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1480:20:

       do 58 k=1,lq
                                                                        2
       zvh = zvh+czv(k+1)*sth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1635:20:

       do 30 k=1,lq
                                                                        2
       zwh = zwh+czw(k+1)*sth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1658:20:

       do 10 k=1,ls
                                                                        2
       zwh = zwh+czw(k+1)*sth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1669:20:

       do 20 k=2,lq
                                                                        2
       zwh = zwh+czw(k)*cth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1682:20:

       do 55 k=1,lq
                                                                        2
       zwh = zwh+czw(k+1)*sth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1706:20:

       do 65 k=1,lq
                                                                        2
       zwh = zwh+czw(k+1)*sth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1717:20:

       do 70 k=2,lc
                                                                        2
       zwh = zwh+czw(k)*cth
                    1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1949:17:

       do 25 k=2,ncw
                                                                        2
       wh = wh+cw(k)*cth
                 1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1184:27:

../external/SPHEREPACK/sphcom.f:1182:72:

    30 do 50 np1=2,nlat
                                                                        2
../external/SPHEREPACK/sphcom.f:1184:27:

       vb(i,np1,i3) = vb1(i,np1)
                           1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1243:27:

../external/SPHEREPACK/sphcom.f:1241:72:

       do 45 np1=2,nlat
                                                                        2
../external/SPHEREPACK/sphcom.f:1243:27:

       wb(i,np1,i3) = wb1(i,np1)
                           1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:1248:27:

../external/SPHEREPACK/sphcom.f:1246:72:

    30 do 50 np1=3,nlat
                                                                        2
../external/SPHEREPACK/sphcom.f:1248:27:

       wb(i,np1,i3) = wb2(i,np1)
                           1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/sphcom.f:2463:17:

       do 25 k=2,ncw
                                                                        2
       wh = wh+cw(k)*sth
                 1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
[5:31/599-10.190]Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/vhags.f.o
../external/SPHEREPACK/vhags.f:481:41:

       do 15 np1=2,ndo2,2
                                                                        2
       br(1,1,np1,k) = br(1,1,np1,k)+vb(i,np1)*ve(i,1,k)
                                         1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:482:47:

../external/SPHEREPACK/vhags.f:480:72:

       do 15 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vhags.f:482:47:

       cr(ncbc,1,np1,k) = cr(ncbc,1,np1,k)-vb(i,np1)*we(i,1,k)
                                               1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:487:41:

       do 16 np1=3,ndo1,2
                                                                        2
       br(1,1,np1,k) = br(1,1,np1,k)+vb(i,np1)*vo(i,1,k)
                                         1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:488:47:

../external/SPHEREPACK/vhags.f:486:72:

       do 16 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vhags.f:488:47:

       cr(ncbc,1,np1,k) = cr(ncbc,1,np1,k)-vb(i,np1)*wo(i,1,k)
                                               1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:562:41:

       do 115 np1=2,ndo2,2
                                                                        2
       br(1,1,np1,k) = br(1,1,np1,k)+vb(i,np1)*ve(i,1,k)
                                         1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:567:41:

       do 116 np1=3,ndo1,2
                                                                        2
       br(1,1,np1,k) = br(1,1,np1,k)+vb(i,np1)*vo(i,1,k)
                                         1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:621:47:

       do 215 np1=2,ndo2,2
                                                                        2
       cr(ncbc,1,np1,k) = cr(ncbc,1,np1,k)-vb(i,np1)*we(i,1,k)
                                               1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:626:47:

       do 216 np1=3,ndo1,2
                                                                        2
       cr(ncbc,1,np1,k) = cr(ncbc,1,np1,k)-vb(i,np1)*wo(i,1,k)
                                               1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:684:41:

       do 315 np1=2,ndo2,2
                                                                        2
       br(1,1,np1,k) = br(1,1,np1,k)+vb(i,np1)*ve(i,1,k)
                                         1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:689:47:

       do 316 np1=3,ndo1,2
                                                                        2
       cr(ncbc,1,np1,k) = cr(ncbc,1,np1,k)-vb(i,np1)*wo(i,1,k)
                                               1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:745:41:

       do 415 np1=2,ndo2,2
                                                                        2
       br(1,1,np1,k) = br(1,1,np1,k)+vb(i,np1)*ve(i,1,k)
                                         1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:782:47:

       do 516 np1=3,ndo1,2
                                                                        2
       cr(ncbc,1,np1,k) = cr(ncbc,1,np1,k)-vb(i,np1)*wo(i,1,k)
                                               1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:821:47:

       do 615 np1=2,ndo2,2
                                                                        2
       cr(ncbc,1,np1,k) = cr(ncbc,1,np1,k)-vb(i,np1)*we(i,1,k)
                                               1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:826:41:

       do 616 np1=3,ndo1,2
                                                                        2
       br(1,1,np1,k) = br(1,1,np1,k)+vb(i,np1)*vo(i,1,k)
                                         1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:882:41:

       do 716 np1=3,ndo1,2
                                                                        2
       br(1,1,np1,k) = br(1,1,np1,k)+vb(i,np1)*vo(i,1,k)
                                         1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhags.f:919:47:

       do 815 np1=2,ndo2,2
                                                                        2
       cr(ncbc,1,np1,k) = cr(ncbc,1,np1,k)-vb(i,np1)*we(i,1,k)
                                               1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
[5:32/599-10.195]Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/vhsgs.f.o
../external/SPHEREPACK/vhsgs.f:562:54:

../external/SPHEREPACK/vhsgs.f:558:72:

       do 15 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:562:54:

       ve(ig,i,1,k)=ve(ig,i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:563:54:

../external/SPHEREPACK/vhsgs.f:558:72:

       do 15 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:563:54:

       we(ig,i,1,k)=we(ig,i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:570:54:

../external/SPHEREPACK/vhsgs.f:566:72:

       do 16 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:570:54:

       vo(ig,i,1,k)=vo(ig,i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:571:54:

../external/SPHEREPACK/vhsgs.f:566:72:

       do 16 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:571:54:

       wo(ig,i,1,k)=wo(ig,i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:655:54:

../external/SPHEREPACK/vhsgs.f:651:72:

       do 115 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:655:54:

       ve(ig,i,1,k)=ve(ig,i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:662:54:

../external/SPHEREPACK/vhsgs.f:658:72:

       do 116 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:662:54:

       vo(ig,i,1,k)=vo(ig,i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:729:54:

../external/SPHEREPACK/vhsgs.f:725:72:

       do 215 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:729:54:

       we(ig,i,1,k)=we(ig,i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:736:54:

../external/SPHEREPACK/vhsgs.f:732:72:

       do 216 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:736:54:

       wo(ig,i,1,k)=wo(ig,i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:804:54:

../external/SPHEREPACK/vhsgs.f:800:72:

       do 315 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:804:54:

       ve(ig,i,1,k)=ve(ig,i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:811:54:

../external/SPHEREPACK/vhsgs.f:807:72:

       do 316 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:811:54:

       wo(ig,i,1,k)=wo(ig,i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:878:54:

../external/SPHEREPACK/vhsgs.f:874:72:

       do 415 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:878:54:

       ve(ig,i,1,k)=ve(ig,i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:923:54:

../external/SPHEREPACK/vhsgs.f:919:72:

       do 516 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:923:54:

       wo(ig,i,1,k)=wo(ig,i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:968:54:

../external/SPHEREPACK/vhsgs.f:964:72:

       do 615 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:968:54:

       we(ig,i,1,k)=we(ig,i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:975:54:

../external/SPHEREPACK/vhsgs.f:971:72:

       do 616 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:975:54:

       vo(ig,i,1,k)=vo(ig,i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:1042:54:

../external/SPHEREPACK/vhsgs.f:1038:72:

       do 716 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:1042:54:

       vo(ig,i,1,k)=vo(ig,i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vhsgs.f:1087:54:

../external/SPHEREPACK/vhsgs.f:1083:72:

       do 815 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vhsgs.f:1087:54:

       we(ig,i,1,k)=we(ig,i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                      1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
[5:34/599-10.205]Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/vtsgs.f.o
../external/SPHEREPACK/vtsgs.f:462:50:

../external/SPHEREPACK/vtsgs.f:460:72:

       do 15 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:462:50:

       vto(i,1,k)=vto(i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:463:50:

../external/SPHEREPACK/vtsgs.f:460:72:

       do 15 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:463:50:

       wto(i,1,k)=wto(i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:468:50:

../external/SPHEREPACK/vtsgs.f:466:72:

       do 16 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:468:50:

       vte(i,1,k)=vte(i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:469:50:

../external/SPHEREPACK/vtsgs.f:466:72:

       do 16 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:469:50:

       wte(i,1,k)=wte(i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:555:50:

../external/SPHEREPACK/vtsgs.f:553:72:

       do 115 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:555:50:

       vto(i,1,k)=vto(i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:560:50:

../external/SPHEREPACK/vtsgs.f:558:72:

       do 116 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:560:50:

       vte(i,1,k)=vte(i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:622:50:

../external/SPHEREPACK/vtsgs.f:620:72:

       do 215 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:622:50:

       wto(i,1,k)=wto(i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:627:50:

../external/SPHEREPACK/vtsgs.f:625:72:

       do 216 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:627:50:

       wte(i,1,k)=wte(i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:689:50:

../external/SPHEREPACK/vtsgs.f:687:72:

       do 315 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:689:50:

       vto(i,1,k)=vto(i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:694:50:

../external/SPHEREPACK/vtsgs.f:692:72:

       do 316 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:694:50:

       wte(i,1,k)=wte(i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:756:50:

../external/SPHEREPACK/vtsgs.f:754:72:

       do 415 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:756:50:

       vto(i,1,k)=vto(i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:797:50:

../external/SPHEREPACK/vtsgs.f:795:72:

       do 516 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:797:50:

       wte(i,1,k)=wte(i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:838:50:

../external/SPHEREPACK/vtsgs.f:836:72:

       do 615 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:838:50:

       wto(i,1,k)=wto(i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:843:50:

../external/SPHEREPACK/vtsgs.f:841:72:

       do 616 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:843:50:

       vte(i,1,k)=vte(i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:905:50:

../external/SPHEREPACK/vtsgs.f:903:72:

       do 716 np1=3,ndo1,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:905:50:

       vte(i,1,k)=vte(i,1,k)+br(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (3 > 1) in loop beginning at (2)
../external/SPHEREPACK/vtsgs.f:946:50:

../external/SPHEREPACK/vtsgs.f:944:72:

       do 815 np1=2,ndo2,2
                                                                        2
../external/SPHEREPACK/vtsgs.f:946:50:

       wto(i,1,k)=wto(i,1,k)-cr(ncbc,1,np1,k)*vb(i,np1)
                                                  1
Warning: Array reference at (1) out of bounds (2 > 1) in loop beginning at (2)
```

### Environment:

GCC8

### PR DESCRIPTION
**Pull request by fmahebert**
Work around a `g++` issue, and silence `gfortran` warnings

Edit by @nilsdeppe:
closes #1026

### Types of changes:

- [ ] Bugfix
- [ ] New feature

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests, `clang-tidy` and `IWYU`. For
  instructions on how to perform the CI checks locally refer to the [Dev guide
  on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run `make doc`
  to generate the documentation locally into `BUILD_DIR/docs/html`. Then open
  `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

File: src/Utilities/Gsl.hpp [hunk 1]
```diff
@@ -844,11 +844,13 @@ constexpr ElementType& at(span<ElementType, Extent> s,
   return s[i];
 }
 
-template <class ElementType, std::ptrdiff_t Extent>
-constexpr ElementType& at(span<ElementType, Extent> s, size_t i) {
-  // No bounds checking here because it is done in span::operator[] called below
-  return s[i];
-}
+// Disabled because gcc8 gets confused and can't identify which `at` to use:
```
Comment (nilsdeppe) [inline src/Utilities/Gsl.hpp]: You can just delete this. It would only be needed if we had kept `index_type` as `ptr_diff_t` :)

**Review by nilsdeppe — COMMENTED** [review]
I'm happy for you to squash :)

**Review by wthrowe — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]

**Comment by nilsdeppe** [comment]
I vote we ignore the GCC6 release timeout during building of the executables

**Review by kidder — APPROVED** [review]

**Comment by kidder** [comment]
ignoring test that times out
