### PR TITLE
Fix failure in CylindricalSide

### LINKED ISSUE #3169: Random failure in Unit.Domain.CoordinateMaps.CylindricalSide
Just prints "Called terminate. Aborting...".  Seen locally and in CI.

I don't have good statistics, but incidence seem to be around 1e-4.

### PR DESCRIPTION
**Pull request by markscheel**
## Proposed changes

Two commits: one fixes #3169 (I ran 20,000 times on my machine without a failure)
The other allows more information to get printed on test failures where inverse maps
return invalid std::optionals.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `major new feature` if appropriate.

### CODE REVIEW

File: tests/Unit/Helpers/Domain/CoordinateMaps/TestMapHelpers.hpp [hunk 1]
```diff
@@ -410,7 +410,9 @@ void test_inverse_map(const Map& map,
                       const std::array<T, Map::dim>& test_point) noexcept {
   INFO("Test inverse map");
   CAPTURE(test_point);
-  CHECK_ITERABLE_APPROX(test_point, map.inverse(map(test_point)).value());
+  const auto expected_test_point = map.inverse(map(test_point));
+  CHECK(expected_test_point.has_value());
```
Comment (nilsvu) [inline tests/Unit/Helpers/Domain/CoordinateMaps/TestMapHelpers.hpp]: better to replace `CHECK` -> `REQUIRE` here (there's no point continuing the test when this check fails). Same for the test below

**Review by nilsvu — CHANGES_REQUESTED** [review]
squash directly

**Review by geoffrey4444 — DISMISSED** [review]
But please fix test failure

**Comment by markscheel** [comment]
Made changes and squashed.  The failing test was a timeout in `InputFiles.Xcts.Schwarzschild.yaml.execute_check_output` which has nothing to do with the changes in this PR.

**Comment by nilsdeppe** [comment]
@nilsleiffischer @geoffrey4444 please take a look at the updated version

**Review by nilsvu — APPROVED** [review]

**Review by kidder — APPROVED** [review]
