### PR TITLE
Fix BoundaryMessage on macOS

### LINKED ISSUE #4610: Malloc error in BoundaryMessage
I'm getting this error when running `Test_BoundaryMessage.cpp` (#4563)  in `RunSingleTest` on macOS:

```
RunSingleTest(2898,0x7ff846d9d8c0) malloc: Incorrect checksum for freed object 0x10792d640: probably modified after being freed.
Corrupt value: 0x3fd3faf5a6b7185c
```

Here's the backtrace when breaking at `malloc_error_break`:

```
  * frame #0: 0x00007ff8032db78d libsystem_malloc.dylib`malloc_error_break
    frame #1: 0x00007ff8032cc5b8 libsystem_malloc.dylib`malloc_vreport + 761
    frame #2: 0x00007ff8032e1897 libsystem_malloc.dylib`malloc_zone_error + 178
    frame #3: 0x00007ff8032e15be libsystem_malloc.dylib`_tiny_check_and_zero_inline_meta_from_freelist + 239
    frame #4: 0x00007ff8032c1f1c libsystem_malloc.dylib`tiny_malloc_from_free_list + 1503
    frame #5: 0x00007ff8032c130b libsystem_malloc.dylib`tiny_malloc_should_clear + 357
    frame #6: 0x00007ff8032bff80 libsystem_malloc.dylib`szone_malloc_should_clear + 66
    frame #7: 0x000000010389c816 libconverse.dylib`CmiAlloc + 22
    frame #8: 0x00000001067be736 libck.dylib`CkAllocBuffer + 70
    frame #9: 0x00000001000ee6f3 RunSingleTest`evolution::dg::BoundaryMessage<1ul>::pack(in_msg=0x000000010792c470) at BoundaryMessage.cpp:70:7
    frame #10: 0x00000001000e6fda RunSingleTest`void evolution::dg::(anonymous namespace)::test_boundary_message<1ul, std::__1::mersenne_twister_engine<unsigned int, 32ul, 624ul, 397ul, 31ul, 2567483615u, 11ul, 4294967295u, 7ul, 2636928640u, 15ul, 4022730752u, 18ul, 1812433253u> >(generator=const gsl::not_null<std::__1::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253> *> @ 0x00007ff7bfefd020, subcell_size=0, dg_size=0) at Test_BoundaryMessage.cpp:81:26
    frame #11: 0x00000001000e6068 RunSingleTest`auto evolution::dg::(anonymous namespace)::____C_A_T_C_H____T_E_S_T____27(this=0x00007ff7bfefd210, dim_t=type_<brigand::integral_constant<unsigned long, 1> > @ 0x00007ff7bfefd138)::$_0::operator()<brigand::type_<brigand::integral_constant<unsigned long, 1ul> > >(brigand::type_<brigand::integral_constant<unsigned long, 1ul> >) const at Test_BoundaryMessage.cpp:179:9
```

And here's another failure mode:

```
  * frame #0: 0x00007ff8032db78d libsystem_malloc.dylib`malloc_error_break
    frame #1: 0x00007ff8032cc5b8 libsystem_malloc.dylib`malloc_vreport + 761
    frame #2: 0x00007ff8032e1897 libsystem_malloc.dylib`malloc_zone_error + 178
    frame #3: 0x00007ff8032e15be libsystem_malloc.dylib`_tiny_check_and_zero_inline_meta_from_freelist + 239
    frame #4: 0x00007ff8032c1f1c libsystem_malloc.dylib`tiny_malloc_from_free_list + 1503
    frame #5: 0x00007ff8032c130b libsystem_malloc.dylib`tiny_malloc_should_clear + 357
    frame #6: 0x00007ff8032bff80 libsystem_malloc.dylib`szone_malloc_should_clear + 66
    frame #7: 0x00000001000e476d RunSingleTest`cpp20::detail::unique_type<double []>::array cpp20::make_unique_for_overwrite<double []>(num=10) at MemoryHelpers.hpp:34:29
    frame #8: 0x00000001000e99cf RunSingleTest`VectorImpl<double, DataVector, 0ul>::VectorImpl(VectorImpl<double, DataVector, 0ul> const&) [inlined] VectorImpl<double, DataVector, 0ul>::heap_alloc_if_necessary(this=0x00007ff7bfefd048, set_size=10) at VectorImpl.hpp:329:18
    frame #9: 0x00000001000e99b4 RunSingleTest`VectorImpl<double, DataVector, 0ul>::VectorImpl(this=0x00007ff7bfefd048, rhs=0x00007ff7bfefd098) at VectorImpl.hpp:338:34
    frame #10: 0x00000001000e993d RunSingleTest`DataVector::DataVector(this=0x00007ff7bfefd048, (null)=0x00007ff7bfefd098) at DataVector.hpp:51:3
    frame #11: 0x00000001000e792d RunSingleTest`DataVector::DataVector(this=0x00007ff7bfefd048, (null)=0x00007ff7bfefd098) at DataVector.hpp:51:41
    frame #12: 0x00000001000ece44 RunSingleTest`void evolution::dg::(anonymous namespace)::test_boundary_message<3ul, std::__1::mersenne_twister_engine<unsigned int, 32ul, 624ul, 397ul, 31ul, 2567483615u, 11ul, 4294967295u, 7ul, 2636928640u, 15ul, 4022730752u, 18ul, 1812433253u> >(generator=const gsl::not_null<std::__1::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253> *> @ 0x00007ff7bfefd040, subcell_size=0, dg_size=10) at Test_BoundaryMessage.cpp:65:31
    frame #13: 0x00000001000ec5ae RunSingleTest`auto evolution::dg::(anonymous namespace)::____C_A_T_C_H____T_E_S_T____27(this=0x00007ff7bfefd200, dim_t=type_<brigand::integral_constant<unsigned long, 3> > @ 0x00007ff7bfefd128)::$_0::operator()<brigand::type_<brigand::integral_constant<unsigned long, 3ul> > >(brigand::type_<brigand::integral_constant<unsigned long, 3ul> >) const at Test_BoundaryMessage.cpp:171:9
```

And another one:

```
  * frame #0: 0x00007ff8032db78d libsystem_malloc.dylib`malloc_error_break
    frame #1: 0x00007ff8032cc5b8 libsystem_malloc.dylib`malloc_vreport + 761
    frame #2: 0x00007ff8032e1897 libsystem_malloc.dylib`malloc_zone_error + 178
    frame #3: 0x00007ff8032e15be libsystem_malloc.dylib`_tiny_check_and_zero_inline_meta_from_freelist + 239
    frame #4: 0x00007ff8032c1f1c libsystem_malloc.dylib`tiny_malloc_from_free_list + 1503
    frame #5: 0x00007ff8032c130b libsystem_malloc.dylib`tiny_malloc_should_clear + 357
    frame #6: 0x00007ff8032bff80 libsystem_malloc.dylib`szone_malloc_should_clear + 66
    frame #7: 0x0000000103898816 libconverse.dylib`CmiAlloc + 22
    frame #8: 0x00000001067ba6b1 libck.dylib`CkAllocMsg + 49
    frame #9: 0x00000001000e61f0 RunSingleTest`evolution::dg::CMessage_BoundaryMessage<1ul>::alloc(msgnum=0, sz=264, sizes=0x0000000000000000, pb=0, groupDepNum=(groupDepNum = 0)) at BoundaryMessage.def.h:35:10
    frame #10: 0x00000001000e2e41 RunSingleTest`evolution::dg::CMessage_BoundaryMessage<1ul>::operator new(s=264) at BoundaryMessage.def.h:16:10
    frame #11: 0x00000001000e1ea2 RunSingleTest`void evolution::dg::(anonymous namespace)::test_boundary_message<1ul, std::__1::mersenne_twister_engine<unsigned int, 32ul, 624ul, 397ul, 31ul, 2567483615u, 11ul, 4294967295u, 7ul, 2636928640u, 15ul, 4022730752u, 18ul, 1812433253u> >(generator=const gsl::not_null<std::__1::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253> *> @ 0x00007ff7bfefd010, subcell_size=4, dg_size=6) at Test_BoundaryMessage.cpp:72:51
    frame #12: 0x00000001000e1498 RunSingleTest`auto evolution::dg::(anonymous namespace)::____C_A_T_C_H____T_E_S_T____27(this=0x00007ff7bfefd200, dim_t=type_<brigand::integral_constant<unsigned long, 1> > @ 0x00007ff7bfefd128)::$_0::operator()<brigand::type_<brigand::integral_constant<unsigned long, 1ul> > >(brigand::type_<brigand::integral_constant<unsigned long, 1ul> >) const at Test_BoundaryMessage.cpp:174:9
```

These errors seem to occur in all four test cases with a high probability, but not always.

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

For some reason sizeof(BoundaryMessage) is different on macOS than on
Linux. Just use sizeof instead of trying to
compute the size manually.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Review by knelli2 — APPROVED** [review]

File: tests/Unit/Evolution/DiscontinuousGalerkin/Messages/Test_BoundaryMessage.cpp [hunk 1]
```diff
@@ -78,10 +74,10 @@ void test_boundary_message(const gsl::not_null<Generator*> generator,
...
 
-  void* packed_message = boundary_message->pack(boundary_message);
+  void* packed_message = BoundaryMessage<Dim>::pack(boundary_message);
 
   BoundaryMessage<Dim>* unpacked_message =
-      boundary_message->unpack(packed_message);
+      BoundaryMessage<Dim>::unpack(packed_message);
 
   CHECK(*copied_boundary_message == *unpacked_message);
   CHECK_FALSE(*copied_boundary_message != *unpacked_message);
```
Comment (knelli2) [inline tests/Unit/Evolution/DiscontinuousGalerkin/Messages/Test_BoundaryMessage.cpp:83]: Github comments can't reach it, but you forgot to get rid of the `test_offset` function down below since you got rid of `detail::offset` in the hpp file.

**Review by knelli2 — CHANGES_REQUESTED** [review]

**Review by knelli2 — APPROVED** [review]

**Review by nilsdeppe — APPROVED** [review]
