### PR TITLE
Split up bulky tensor expression test into two test files

### LINKED ISSUE #3614: Random failures in CI for gcc-10, Debug, ON
I've noticed this twice now on two separate CI runs in two separate PRs. 
1. https://github.com/sxs-collaboration/spectre/actions/runs/1356323620
```
make[2]: *** [CMakeFiles/Makefile2:20256: tests/Unit/DataStructures/Tensor/Expressions/CMakeFiles/Test_Expressions.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 13%] Linking CXX shared library ../../../../../lib/libGeneralRelativityHelpers.so
[ 13%] Built target GeneralRelativityHelpers
make[1]: *** [CMakeFiles/Makefile2:9472: CMakeFiles/unit-tests.dir/rule] Error 2
make: *** [Makefile:161: unit-tests] Error 2
Error: Process completed with exit code 2.
```
2. https://github.com/sxs-collaboration/spectre/actions/runs/1365248969
```
make[2]: *** [CMakeFiles/Makefile2:20317: tests/Unit/DataStructures/Tensor/Expressions/CMakeFiles/Test_Expressions.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 13%] Building CXX object tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeFiles/Test_GeneralRelativity.dir/Test_ComputeSpacetimeQuantities.cpp.o
[ 13%] Building CXX object tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeFiles/Test_GeneralRelativity.dir/Test_IndexManipulation.cpp.o
[ 13%] Building CXX object tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeFiles/Test_GeneralRelativity.dir/Test_InterfaceNullNormal.cpp.o
[ 13%] Building CXX object tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeFiles/Test_GeneralRelativity.dir/Test_KerrSchildCoords.cpp.o
[ 13%] Building CXX object tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeFiles/Test_GeneralRelativity.dir/Test_ProjectionOperators.cpp.o
[ 13%] Building CXX object tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeFiles/Test_GeneralRelativity.dir/Test_Ricci.cpp.o
[ 13%] Building CXX object tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeFiles/Test_GeneralRelativity.dir/Test_Tags.cpp.o
[ 13%] Building CXX object tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeFiles/Test_GeneralRelativity.dir/Test_Transform.cpp.o
[ 13%] Building CXX object tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeFiles/Test_GeneralRelativity.dir/Test_WeylElectric.cpp.o
[ 13%] Building CXX object tests/Unit/PointwiseFunctions/GeneralRelativity/CMakeFiles/Test_GeneralRelativity.dir/Test_WeylPropagating.cpp.o
[ 13%] Linking CXX shared library ../../../../lib/libTest_GeneralRelativity.so
[ 13%] Built target Test_GeneralRelativity
make[1]: *** [CMakeFiles/Makefile2:9531: CMakeFiles/unit-tests.dir/rule] Error 2
make: *** [Makefile:161: unit-tests] Error 2
Error: Process completed with exit code 2.
```

Both failures appear to start with `make[2]: *** [CMakeFiles/Makefile2:20317: tests/Unit/DataStructures/Tensor/Expressions/CMakeFiles/Test_Expressions.dir/all] Error 2`. Unsure if that's a coincidence or not.

### PR DESCRIPTION
**Pull request by macedo22**
## Proposed changes

Fixes https://github.com/sxs-collaboration/spectre/issues/3614

This PR splits a bulky `TensorExpressions` test into two separate cpp files to reduce the amount of memory consumed per cpp file. This is meant to address CI builds that have been killed (see [here](https://github.com/sxs-collaboration/spectre/issues/3614)) when building the `Test_Expressions` target.

Here are the comparisons for compiling these test cases with gcc-10 debug before and after splitting the original file into two new files:

**Compiling `Test_EvaluateRank3` before**
- peak RAM usage: ~4.6 GB
- time: ~2 min 25 sec

**Compiling `Test_EvaluateRank3Symmetric.cpp` and `Test_EvaluateRank3NonSymmetric.cpp` together after this PR**
- peak RAM usage: ~2.6 GB
- time: ~1 min 3 sec

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

File: tests/Unit/DataStructures/Tensor/Expressions/Test_EvaluateRank3NonSymmetric.cpp [hunk 1]
```diff
@@ -0,0 +1,23 @@
+// Distributed under the MIT License.
+// See LICENSE.txt for details.
+
+#include "Framework/TestingFramework.hpp"
```
Comment (nilsvu) [inline tests/Unit/DataStructures/Tensor/Expressions/Test_EvaluateRank3NonSymmetric.cpp:8]: Could you add a brief comment here please, so we remember why this file is split? Squash it in directly

**Review by nilsvu — CHANGES_REQUESTED** [review]

**Review by nilsdeppe — COMMENTED** [review]
I have no additional comments. You can merge this once @nilsleiffischer is happy :)

**Comment by knelli2** [comment]
Could you link the issue as well so that it's closed when this PR is closed?

**Comment by macedo22** [comment]
@knelli2 Thanks for the suggestion! I don't think I have the permissions to link an issue to a PR, so maybe someone with permissions can do it, instead. If not, I'll be sure to close the issue after this is merged.

**Comment by macedo22** [comment]
@nilsleiffischer Comments have been added and squashed in

**Comment by kidder** [comment]
Hi Alex, you should have the correct permissions to link to an issue.  Just add a comment to the Proposed Changes above that says `Fixes #3614`

**Comment by macedo22** [comment]
Thanks @kidder ! I didn't know about this. I was attempting to add it using the sidebar on the right, which I can't do. I'll link it with the method you provided.

**Review by nilsvu — APPROVED** [review]
