### PR TITLE
Prevent events used in control system from being factory creatable

### LINKED ISSUE #5762: Control system events show up in available events in input file
# Bug reports:

### Expected behavior:

The control system events shouldn't be available for a user to choose from the input file.

### Current behavior:

Currently they are. I believe this is from #5682. The control system Event wasn't constructible from options, but when I removed it and just used regular events, those *are* constructible from options and I didn't add a way to specify that they *not* be constructible from options.

### PR DESCRIPTION
**Pull request by knelli2**
## Proposed changes

Fixes #5762

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

**Comment by wthrowe** [comment]
Possible alternate design that could be handled completely within the control system code:
```c++
template <typename CreatableEvent>
struct NonCreatableWrapper : CreatableEvent {
  static constexpr bool factory_creatable = false;
  using CreatableEvent::CreatableEvent;
  // pup stuff...
};
```
Thoughts?

**Comment by knelli2** [comment]
Yeah I like that, and I think it'll fit well with the other interpolation changes I'm working on. Do you think the `NonCreatableWrapper` should be generally available next to the `Event` base class, or specifically in the control system? Currently only the control system has events that shouldn't be factory creatable, but I can't think of any other scenario where we'd have events that aren't factory creatable.

**Comment by wthrowe** [comment]
Let's keep it in the control system for now.  Easy enough to move it later.  With the template parameter renamed, it could even move to `Options`, since there's nothing specific to Events there, but let's only do that if we have a use.

We may need other non-creatable stuff occasionally, but it should be rare that we need to transform a creatable class to a non-creatable one.

**Comment by knelli2** [comment]
@wthrowe Good suggestion. This was a lot more self-contained.

File: src/ControlSystem/Measurements/BothHorizons.hpp [hunk 1]
```diff
@@ -6,7 +6,9 @@
 #include <cstddef>
 #include <string>
 
+#include "ControlSystem/Measurements/NonFactoryCreatable.hpp"
 #include "ControlSystem/Protocols/Measurement.hpp"
+
```
Comment (wthrowe) [inline src/ControlSystem/Measurements/BothHorizons.hpp]: Remove blank line.

File: src/ControlSystem/Measurements/NonFactoryCreatable.hpp [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+ * It does this by defining and setting a static constexpr bool
+ * `factory_creatable = false`.
+ *
+ * \tparam FactoryCreatableClass Any class that is already factory creatable.
+ */
+template <typename FactoryCreatableClass>
+struct NonFactoryCreatableWrapper : public FactoryCreatableClass {
+  static constexpr bool factory_creatable = false;
+  using FactoryCreatableClass::FactoryCreatableClass;
+};
```
Comment (wthrowe) [inline src/ControlSystem/Measurements/NonFactoryCreatable.hpp:31]: I think you need `WRAPPED_PUPable_decl_template(NonFactoryCreatableWrapper)` for serialization to work properly.

**Review by wthrowe — CHANGES_REQUESTED** [review]
Squash directly.

File: src/ControlSystem/Measurements/NonFactoryCreatable.hpp (hunk 2 above)
Comment (knelli2) [reply src/ControlSystem/Measurements/NonFactoryCreatable.hpp:31]: Currently, these events don't have member data or `pup` functions. I tried adding some member data and a `pup` function to test the serialization, and the serialized (and deserialized) class was the same. I wonder if it's because the `NonFactoryCreatableWrapper` doesn't hold any data, so it just inherits the pup stuff from the `FactoryCreatableClass` and that works ok.

Comment (wthrowe) [reply src/ControlSystem/Measurements/NonFactoryCreatable.hpp:31]: I think you run into trouble if both `T` and `NonFactoryCreatableWrapper<T>` are registered with charm.  The wrapper will inherit the pup stuff, but that will include the mapping of PUP_ID to class, so one of them will deserialize to the wrong type when serialized through a base-class pointer.

You don't need a `pup` function, since the inherited version of that is correct.

Comment (knelli2) [reply src/ControlSystem/Measurements/NonFactoryCreatable.hpp:31]: Have any thoughts about a good way to test this? Only thing I can think of is to register both `T` and `NonFactoryCreatableWrapper<T>` with charm and try to serialize both through a `unique_ptr<::Event>`.

Comment (wthrowe) [reply src/ControlSystem/Measurements/NonFactoryCreatable.hpp:31]: That is how I would do it.

**Comment by knelli2** [comment]
For some reason, the `Interpolate` event had all its members marked `private`, so I made things `public`

File: tests/Unit/ControlSystem/Test_Measurements.cpp [hunk 3]
```diff
@@ -100,6 +105,37 @@ static_assert(
...
+
+  // No equivalence operators so just check dynamic casting
+  CHECK(dynamic_cast<const non_factory_creatable_event*>(
+            non_factory_event.get()) != nullptr);
+  CHECK(dynamic_cast<const factory_creatable_event*>(factory_event.get()) !=
+        nullptr);
+  CHECK(dynamic_cast<const non_factory_creatable_event*>(factory_event.get()) ==
+        nullptr);
+  // Can't test the other way around because the non factory creatable class is
+  // derived from the factory creatable one.
```
Comment (wthrowe) [inline tests/Unit/ControlSystem/Test_Measurements.cpp]:
```c++
#include <typeinfo>
...
CHECK(typeid(*serialized_non_factory_event) == typeid(non_factory_creatable_event));
CHECK(typeid(*serialized_factory_event) == typeid(factory_creatable_event));
```
(Also you're currently checking the wrong variables.)

File: src/ParallelAlgorithms/Interpolation/Events/Interpolate.hpp [hunk 4]
```diff
@@ -50,6 +50,7 @@ template <size_t VolumeDim, typename InterpolationTargetTag,
           typename... InterpolatorSourceVarTags>
 class Interpolate<VolumeDim, InterpolationTargetTag,
                   tmpl::list<InterpolatorSourceVarTags...>> : public Event {
+ public:
```
Comment (wthrowe) [inline src/ParallelAlgorithms/Interpolation/Events/Interpolate.hpp:53]: Worked before because `WRAPPED_PUPable_decl_template` contains a `public:`, but we should definitely not be relying on that.

**Review by wthrowe — CHANGES_REQUESTED** [review]

**Comment by knelli2** [comment]
Ok squashed in the changes in. The test passes with the `PUP_ID` changes and fails without it, as expected

File: tests/Unit/ControlSystem/Test_Measurements.cpp [hunk 5]
```diff
@@ -18,70 +21,119 @@
...
+      serialize_and_deserialize(factory_event);
+
+  const auto get_typeid = [&](const EventPtr& event_ptr) {
+    const auto& event_ref = *event_ptr.get();
+    return typeid(event_ref).name();
+  };
+
+  CHECK(get_typeid(serialized_non_factory_event) ==
+        get_typeid(non_factory_event));
+  CHECK(get_typeid(serialized_factory_event) == get_typeid(factory_event));
```
Comment (wthrowe) [inline tests/Unit/ControlSystem/Test_Measurements.cpp]: Why did you do this instead of the thing I suggested?  I don't think this is guaranteed to work.

**Review by wthrowe — CHANGES_REQUESTED** [review]

File: tests/Unit/ControlSystem/Test_Measurements.cpp (hunk 5 above)
Comment (knelli2) [reply tests/Unit/ControlSystem/Test_Measurements.cpp]: When I did your suggestion I got a compilation warning from clang (which we have as an error):
```
error: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Werror,-Wpotentially-evaluated-expression]
```
I googled it and it's something related to actually calling `.get()` and dereferencing the pointer inside `typeid()`. However, I was not aware that `typeid().name()` wouldn't give unique results

Comment (wthrowe) [reply tests/Unit/ControlSystem/Test_Measurements.cpp]: Just silence the warning.  It's just clang being dumb.

Comment (wthrowe) [reply tests/Unit/ControlSystem/Test_Measurements.cpp]: For clarification, the thing I'm mostly worried about is that these are c strings, so you may end up with something like how the result of `"Hello" == "Hello"` is unspecified.  But since they give us an equality operator for the objects we should just use it anyway.

File: tests/Unit/ControlSystem/Test_Measurements.cpp [hunk 6]
```diff
@@ -18,70 +21,122 @@
...
+      serialize_and_deserialize(factory_event);
+
+#ifdef __clang__
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wpotentially-evaluated-expression"
+#endif  // __clang__
+  CHECK(typeid(*serialized_non_factory_event.get()) ==
+        typeid(*non_factory_event.get()));
+  CHECK(typeid(*serialized_factory_event.get()) ==
+        typeid(*factory_event.get()));
```
Comment (wthrowe) [inline tests/Unit/ControlSystem/Test_Measurements.cpp:135]: This is OK, but why all the redundant `.get()` calls?

**Review by wthrowe — APPROVED** [review]

File: tests/Unit/ControlSystem/Test_Measurements.cpp (hunk 6 above)
Comment (knelli2) [reply tests/Unit/ControlSystem/Test_Measurements.cpp:135]: 🤷🏻

Artifact of previous changes
