### PR TITLE
Adjust  scri+ interpolation manager test to avoid failures with random values

### LINKED ISSUE #2011: Random failure in Unit.Evolution.Systems.Cce.ScriPlusInterpolationManager
# Bug reports:

```
2020-02-22T00:39:36.7773906Z         Start 449: Unit.Evolution.Systems.Cce.ScriPlusInterpolationManager
2020-02-22T00:39:37.2820925Z 448/1104 Test #449: Unit.Evolution.Systems.Cce.ScriPlusInterpolationManager .....................***Exception: Child aborted  0.40 sec
2020-02-22T00:39:37.2830345Z Charm++: standalone mode (not using charmrun)
2020-02-22T00:39:37.2830551Z Charm++> Running in Multicore mode:  1 threads
2020-02-22T00:39:37.2831675Z Converse/Charm++ Commit ID: v6.8.0-0-ga36028edb
2020-02-22T00:39:37.2832549Z Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
2020-02-22T00:39:37.2832827Z CharmLB> Load balancer assumes all CPUs are same.
2020-02-22T00:39:37.2833391Z Charm++> Running on 1 unique compute nodes (2-way SMP).
2020-02-22T00:39:37.2833603Z Charm++> cpu topology info is gathered in 0.000 seconds.
2020-02-22T00:39:37.2833800Z SpECTRE Build Information:
2020-02-22T00:39:37.2833997Z Version:                      0.0.0
2020-02-22T00:39:37.2834173Z Compiled on host:             539e696af76a
2020-02-22T00:39:37.2834362Z Compiled in directory:        /work/build
2020-02-22T00:39:37.2834553Z Source directory is:          /__w/spectre/spectre
2020-02-22T00:39:37.2834741Z Compiled on git branch:       HEAD
2020-02-22T00:39:37.2834939Z Compiled with git hash:       9b972aa2eb2a16aea9de98db9d784f1af5524f1d
2020-02-22T00:39:37.2835148Z Linked on:                    Sat Feb 22 00:00:43 2020
2020-02-22T00:39:37.2835255Z 
2020-02-22T00:39:37.2835444Z ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-02-22T00:39:37.2835678Z "Debug.Unit.Evolution.Systems.Cce.ScriPlusInterpolationManager" is a Catch v2.2.1 host application.
2020-02-22T00:39:37.2836470Z Run with -? for options
2020-02-22T00:39:37.2836565Z 
2020-02-22T00:39:37.2837109Z -------------------------------------------------------------------------------
2020-02-22T00:39:37.2837333Z Unit.Evolution.Systems.Cce.ScriPlusInterpolationManager
2020-02-22T00:39:37.2837893Z -------------------------------------------------------------------------------
2020-02-22T00:39:37.2838125Z /__w/spectre/spectre/tests/Unit/Evolution/Systems/Cce/Test_ScriPlusInterpolationManager.cpp:209
2020-02-22T00:39:37.2838350Z ...............................................................................
2020-02-22T00:39:37.2838460Z 
2020-02-22T00:39:37.2838647Z /__w/spectre/spectre/tests/Unit/TestingFramework.hpp:162: FAILED:
2020-02-22T00:39:37.2838845Z   CHECK( a == appx(b) )
2020-02-22T00:39:37.2839095Z with expansion:
2020-02-22T00:39:37.2839196Z   47.978107905 == Approx( 47.9781079051 )
2020-02-22T00:39:37.2839295Z with messages:
2020-02-22T00:39:37.2839405Z   Seed is: 3173374452 from /__w/spectre/spectre/tests/Unit/Evolution/Systems/
2020-02-22T00:39:37.2839514Z   Cce/Test_ScriPlusInterpolationManager.cpp:18
2020-02-22T00:39:37.2839619Z   /__w/spectre/spectre/tests/Unit/Evolution/Systems/Cce/
2020-02-22T00:39:37.2839804Z   Test_ScriPlusInterpolationManager.cpp:135: comparison_lhs == comparison_rhs
2020-02-22T00:39:37.2840106Z   a: ((-3.253578809853681742e+04,-4.197994391910765262e+04),(-1.
2020-02-22T00:39:37.2840417Z   226936422119289346e+05,3.600244100035146112e+05),(-1.340414054755177640e+05,
2020-02-22T00:39:37.2840728Z   2.770859802193060750e+05),(-3.855693168161066715e+05,-8.397886239866960095e+
2020-02-22T00:39:37.2840844Z   05),(4.797810790495714173e+01,6.578891098303480539e+05))
2020-02-22T00:39:37.2841134Z   b: ((-3.253578809853683197e+04,-4.197994391910768172e+04),(-1.
2020-02-22T00:39:37.2841443Z   226936422119288618e+05,3.600244100035146694e+05),(-1.340414054755177931e+05,
2020-02-22T00:39:37.2841752Z   2.770859802193061332e+05),(-3.855693168161064386e+05,-8.397886239866958931e+
2020-02-22T00:39:37.2841857Z   05),(4.797810790510350643e+01,6.578891098303481704e+05))
2020-02-22T00:39:37.2841967Z   a: 4.797810790495714173e+01
2020-02-22T00:39:37.2842068Z   b: 4.797810790510350643e+01
2020-02-22T00:39:37.2842117Z 
2020-02-22T00:39:37.2842225Z /__w/spectre/spectre/tests/Unit/TestingFramework.hpp:162: FAILED:
2020-02-22T00:39:37.2842331Z   CHECK( a == appx(b) )
2020-02-22T00:39:37.2842431Z with expansion:
2020-02-22T00:39:37.2842530Z   130.0273528844 == Approx( 130.0273528839 )
2020-02-22T00:39:37.2842631Z with messages:
2020-02-22T00:39:37.2842720Z   Seed is: 3173374452 from /__w/spectre/spectre/tests/Unit/Evolution/Systems/
2020-02-22T00:39:37.2842831Z   Cce/Test_ScriPlusInterpolationManager.cpp:18
2020-02-22T00:39:37.2842935Z   /__w/spectre/spectre/tests/Unit/Evolution/Systems/Cce/
2020-02-22T00:39:37.2843046Z   Test_ScriPlusInterpolationManager.cpp:135: comparison_lhs == comparison_rhs
2020-02-22T00:39:37.2843338Z   a: ((-8.817651602291390009e+04,-1.137714932988112414e+05),(-3.
2020-02-22T00:39:37.2843650Z   325168542297074455e+05,9.757162808280860772e+05),(-3.632708727340594050e+05,
2020-02-22T00:39:37.2843958Z   7.509415877844134811e+05),(-1.044946535157337552e+06,-2.275944102984671015e+
2020-02-22T00:39:37.2844062Z   06),(1.300273528844118118e+02,1.782971091973183444e+06))
2020-02-22T00:39:37.2844355Z   b: ((-8.817651602291394374e+04,-1.137714932988112851e+05),(-3.
2020-02-22T00:39:37.2844659Z   325168542297072709e+05,9.757162808280857280e+05),(-3.632708727340594050e+05,
2020-02-22T00:39:37.2844966Z   7.509415877844132483e+05),(-1.044946535157337203e+06,-2.275944102984671015e+
2020-02-22T00:39:37.2845080Z   06),(1.300273528838757500e+02,1.782971091973182512e+06))
2020-02-22T00:39:37.2845184Z   a: 1.300273528844118118e+02
2020-02-22T00:39:37.2845283Z   b: 1.300273528838757500e+02
2020-02-22T00:39:37.2845332Z 
2020-02-22T00:39:37.2845434Z /__w/spectre/spectre/tests/Unit/TestingFramework.hpp:162: FAILED:
2020-02-22T00:39:37.2845540Z   CHECK( a == appx(b) )
2020-02-22T00:39:37.2845691Z with expansion:
2020-02-22T00:39:37.2845777Z   210.7146222629 == Approx( 210.7146222623 )
2020-02-22T00:39:37.2845877Z with messages:
2020-02-22T00:39:37.2845981Z   Seed is: 3173374452 from /__w/spectre/spectre/tests/Unit/Evolution/Systems/
2020-02-22T00:39:37.2846096Z   Cce/Test_ScriPlusInterpolationManager.cpp:18
2020-02-22T00:39:37.2846199Z   /__w/spectre/spectre/tests/Unit/Evolution/Systems/Cce/
2020-02-22T00:39:37.2846308Z   Test_ScriPlusInterpolationManager.cpp:135: comparison_lhs == comparison_rhs
2020-02-22T00:39:37.2846594Z   a: ((-1.428936362548988545e+05,-1.843713395910576219e+05),(-5.
2020-02-22T00:39:37.2851349Z   388571079920610646e+05,1.581187980758958729e+06),(-5.886952478023855947e+05,
2020-02-22T00:39:37.2851677Z   1.216931434052775148e+06),(-1.693378428126913030e+06,-3.688260133841773495e+
2020-02-22T00:39:37.2851794Z   06),(2.107146222628653049e+02,2.889377287295055576e+06))
2020-02-22T00:39:37.2852086Z   b: ((-1.428936362548989709e+05,-1.843713395910577965e+05),(-5.
2020-02-22T00:39:37.2852407Z   388571079920611810e+05,1.581187980758959660e+06),(-5.886952478023860604e+05,
2020-02-22T00:39:37.2852715Z   1.216931434052775847e+06),(-1.693378428126912797e+06,-3.688260133841773961e+
2020-02-22T00:39:37.2852936Z   06),(2.107146222623224219e+02,2.889377287295054179e+06))
2020-02-22T00:39:37.2853031Z   a: 2.107146222628653049e+02
2020-02-22T00:39:37.2853133Z   b: 2.107146222623224219e+02
2020-02-22T00:39:37.2853197Z 
2020-02-22T00:39:37.2853299Z /__w/spectre/spectre/tests/Unit/TestingFramework.hpp:162: FAILED:
2020-02-22T00:39:37.2853394Z   CHECK( a == appx(b) )
2020-02-22T00:39:37.2853492Z with expansion:
2020-02-22T00:39:37.2853592Z   368.4912785003 == Approx( 368.4912784994 )
2020-02-22T00:39:37.2853695Z with messages:
2020-02-22T00:39:37.2853801Z   Seed is: 3173374452 from /__w/spectre/spectre/tests/Unit/Evolution/Systems/
2020-02-22T00:39:37.2853913Z   Cce/Test_ScriPlusInterpolationManager.cpp:18
2020-02-22T00:39:37.2854005Z   /__w/spectre/spectre/tests/Unit/Evolution/Systems/Cce/
2020-02-22T00:39:37.2854122Z   Test_ScriPlusInterpolationManager.cpp:135: comparison_lhs == comparison_rhs
2020-02-22T00:39:37.2854428Z   a: ((-2.498880151157543878e+05,-3.224229524991361541e+05),(-9.
2020-02-22T00:39:37.2854736Z   423368085262470413e+05,2.765133118538005743e+06),(-1.029492221186106792e+06,
2020-02-22T00:39:37.2855047Z   2.128132424630570225e+06),(-2.961328337181028444e+06,-6.449916372988166288e+
2020-02-22T00:39:37.2855161Z   06),(3.684912785002961755e+02,5.052854515891364776e+06))
2020-02-22T00:39:37.2855451Z   b: ((-2.498880151157545333e+05,-3.224229524991363869e+05),(-9.
2020-02-22T00:39:37.2855918Z   423368085262473905e+05,2.765133118538006209e+06),(-1.029492221186106559e+06,
2020-02-22T00:39:37.2856583Z   2.128132424630570225e+06),(-2.961328337181027979e+06,-6.449916372988164425e+
2020-02-22T00:39:37.2856709Z   06),(3.684912784994125445e+02,5.052854515891364776e+06))
2020-02-22T00:39:37.2856821Z   a: 3.684912785002961755e+02
2020-02-22T00:39:37.2856930Z   b: 3.684912784994125445e+02
2020-02-22T00:39:37.2856989Z 
2020-02-22T00:39:37.2857099Z /__w/spectre/spectre/tests/Unit/TestingFramework.hpp:162: FAILED:
2020-02-22T00:39:37.2857213Z   CHECK( a == appx(b) )
2020-02-22T00:39:37.2857317Z with expansion:
2020-02-22T00:39:37.2857421Z   2970.1141509339
2020-02-22T00:39:37.2857513Z   ==
2020-02-22T00:39:37.2857618Z   Approx( 2970.1141509421 )
2020-02-22T00:39:37.2857724Z with messages:
2020-02-22T00:39:37.2857835Z   Seed is: 3173374452 from /__w/spectre/spectre/tests/Unit/Evolution/Systems/
2020-02-22T00:39:37.2857959Z   Cce/Test_ScriPlusInterpolationManager.cpp:18
2020-02-22T00:39:37.2858070Z   /__w/spectre/spectre/tests/Unit/Evolution/Systems/Cce/
2020-02-22T00:39:37.2858176Z   Test_ScriPlusInterpolationManager.cpp:135: comparison_lhs == comparison_rhs
2020-02-22T00:39:37.2858505Z   a: ((-2.014147886670592707e+06,-2.598794136202996597e+06),(-7.
2020-02-22T00:39:37.2858836Z   595425056883373298e+06,2.228753157483887300e+07),(-8.297915290916582569e+06,
2020-02-22T00:39:37.2859268Z   1.715317728879183531e+07),(-2.386890467439174280e+07,-5.198762904190647602e+
2020-02-22T00:39:37.2859389Z   07),(2.970114150933921337e+03,4.072702822551221400e+07))
2020-02-22T00:39:37.2859702Z   b: ((-2.014147886670593638e+06,-2.598794136202997062e+06),(-7.
2020-02-22T00:39:37.2860037Z   595425056883372366e+06,2.228753157483887300e+07),(-8.297915290916575119e+06,
2020-02-22T00:39:37.2860356Z   1.715317728879182786e+07),(-2.386890467439175397e+07,-5.198762904190650582e+
2020-02-22T00:39:37.2860477Z   07),(2.970114150942104061e+03,4.072702822551221400e+07))
2020-02-22T00:39:37.2860590Z   a: 2.970114150933921337e+03
2020-02-22T00:39:37.2860699Z   b: 2.970114150942104061e+03
2020-02-22T00:39:37.2860752Z 
2020-02-22T00:39:37.2860860Z 0.038 s: Unit.Evolution.Systems.Cce.ScriPlusInterpolationManager
```

### PR DESCRIPTION
**Pull request by moxcodes**
## Proposed changes

Tweak scri+ interpolation manager test to not occasionally fail. previously failed within 2 * 10^3 iterations, now succeeds 10^5 without failing.

fixes #2011 

### Types of changes:

- [x] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

File: tests/Unit/Evolution/Systems/Cce/Test_ScriPlusInterpolationManager.cpp [hunk 1]
```diff
@@ -44,22 +45,22 @@ void test_interpolate_quadratic() {
...
     const DataVector time_vector = make_with_random_values<DataVector>(
         make_not_null(&generator), make_not_null(&time_dist), vector_size);
     interpolation_manager.insert_data(
-        time_vector + i,
+        time_vector + i * 0.1,
         random_vector *
-            (1.0 + linear_coefficient * (static_cast<double>(i) + time_vector) +
-             quadratic_coefficient *
-                 square(static_cast<double>(i) + time_vector)));
+            (1.0 + linear_coefficient * (i * 0.1 + time_vector) +
```
Comment (fmahebert) [inline tests/Unit/Evolution/Systems/Cce/Test_ScriPlusInterpolationManager.cpp:58]: For my understanding: instead making adjustments to `linear/quadratic_coefficient`, `i`, and `time_vector` ... could you not add a single adjustment here in front of the whole `linear_coefficient` term and similar for the quadratic term?

Comment (moxcodes) [reply tests/Unit/Evolution/Systems/Cce/Test_ScriPlusInterpolationManager.cpp:58]: There's actually a couple of adjustments here that have the same prefactor - I'm making the random time points closer together (with the 0.1 on the line 58 commented on) and also making the function vary more slowly (with the 0.1 multiplying the coefficients previously)

**Review by kidder — APPROVED** [review]

**Comment by kidder** [comment]
@fmahebert are you okay with this PR?

**Review by fmahebert — APPROVED** [review]
