### PR TITLE
MutableCache callbacks now work in ActionTesting.

### LINKED ISSUE #3454: Parallel::PerformAlgorithmCallback fails to compile under mocking framework
Test case:
```c++
namespace TestMutableGlobalCache {
struct CacheTag : db::SimpleTag {
  using type = int;
};

template <typename Metavariables>
struct Component {
  using metavariables = Metavariables;
  using chare_type = ActionTesting::MockArrayChare;
  using array_index = int;

  using phase_dependent_action_list =
      tmpl::list<Parallel::PhaseActions<typename Metavariables::Phase,
                                        Metavariables::Phase::Initialization,
                                        tmpl::list<>>>;
};

struct Metavariables {
  using component_list = tmpl::list<Component<Metavariables>>;

  using mutable_global_cache_tags = tmpl::list<CacheTag>;

  enum class Phase { Initialization, Testing, Exit };
};

SPECTRE_TEST_CASE("Unit.ActionTesting.MutableGlobalCache", "[Unit]") {
  using metavars = Metavariables;
  using component = Component<metavars>;

  ActionTesting::MockRuntimeSystem<metavars> runner{{}, {0}};
  ActionTesting::emplace_array_component<component>(
      &runner, ActionTesting::NodeId{0}, ActionTesting::LocalCoreId{0}, 0);

  auto& cache = ActionTesting::cache<component>(runner, 0);
  const auto& element_proxy =
      ::Parallel::get_parallel_component<component>(cache)[0];

  CHECK(Parallel::mutable_cache_item_is_ready<CacheTag>(
      cache, [](const int /*value*/) noexcept {
        return std::unique_ptr<Parallel::Callback>{};
      }));

  CHECK(not Parallel::mutable_cache_item_is_ready<CacheTag>(
      cache, [&element_proxy](const int /*value*/) noexcept {
        return std::unique_ptr<Parallel::Callback>(
            new Parallel::PerformAlgorithmCallback(element_proxy));
      }));
}
}  // namespace TestMutableGlobalCache                                                                         
```
The last statement fails to compile with
```
/home/wthrowe/spectre/src/Parallel/Callback.hpp:80:46: error: invalid operands to binary expression ('PUP::er' and 'ActionTesting::ActionTesting_detail::MockDistributedObjectProxy<(anonymous namespace)::TestMutableGlobalCache::Component<(anonymous namespace)::TestMutableGlobalCache::Metavariables>, brigand::list<>>')
  void pup(PUP::er& p) noexcept override { p | proxy_; }
                                           ~ ^ ~~~~~~
```

### PR DESCRIPTION
**Pull request by markscheel**
## Proposed changes

Fixes #3454

Previously, callbacks worked when called on a collection of elements (i.e. a full chare) but not on a single element (i.e. a component of a chare).

Three things needed to be changed:
1. MockDistributedObjectProxy now has a pup function (the pup function errors and should not be used, but needs to be there to compile).  There already was a pup function in MockCollectionOfDistributedObjectsProxy, which is why callbacks worked on a collection of elements.
2. MockCollectionOfDistributedObjectsProxy::operator[] now returns a reference to a stored MockDistributedObjectProxy (previously it created a temporary MockDistributedObjectProxy and returned that temporary by value).  So now the mock proxies have the same interface as the non-mocked proxies (i.e. you can do `auto& proxy = mock_collection_of_distributed_objects_proxy[i];`).
3. Add a test, which is an expanded version of the test @wthrowe posted in #3454.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

File: tests/Unit/Framework/ActionTesting.hpp [hunk 1]
```diff
@@ -483,6 +483,16 @@ class MockDistributedObjectProxy {
                : nullptr;
   }
 
+  // clang-tidy: no non-const references
+  void pup(PUP::er& /*p*/) noexcept {  // NOLINT
```
Comment (wthrowe) [inline tests/Unit/Framework/ActionTesting.hpp]:
```
// NOLINTNEXTLINE(google-runtime-references)
void pup(PUP::er& /*p*/) noexcept {
```

**Review by wthrowe — CHANGES_REQUESTED** [review]
Making sure that I understand: Using `PerformAlgorithmCallback` currently has no observable effect in the mocking framework, correct?  I don't think this is a problem since it will still determine the return value of `mutable_cache_item_is_ready`, I just want to verify.

**Review by kidder — COMMENTED** [review]
I have no additional requested changes

**Comment by markscheel** [comment]
Made change (and made a similar change to the other pup function in that file, and squashed since the change was trivial).

Correct, `PerformAlgorithmCallback` has no ultimate effect in the ActionTesting framework: it calls `perform_algorithm` when the MutableCache item is mutated, but `perform_algorithm` itself is a no-op in the ActionTesting framework.   This is because in ActionTesting, all the iterable actions are meant to be called explicitly.

**Review by wthrowe — APPROVED** [review]
