### PR TITLE
Fix random roundoff cylindrical map errors

### LINKED ISSUE #3380: Approx error in Unit.Domain.CoordinateMaps.CylindricalFlatSide test
In CI test #7261 (https://github.com/sxs-collaboration/spectre/actions/runs/1053659727)

```
Filters: "Unit.Domain.CoordinateMaps.CylindricalFlatSide"

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"Release.Unit.Domain.CoordinateMaps.CylindricalFlatSide" is a Catch v2.11.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
Unit.Domain.CoordinateMaps.CylindricalFlatSide
-------------------------------------------------------------------------------
/__w/spectre/spectre/tests/Unit/Domain/CoordinateMaps/Test_CylindricalFlatSide.cpp:91
...............................................................................

/__w/spectre/spectre/tests/Unit/Framework/TestingFramework.hpp:147: FAILED:
  CHECK( a == appx(b) )
with expansion:
  -0.97451587442032472
  ==
  Approx( -0.9745158744203859 )
with messages:
  CylindricalFlatSide
  Seed is: 1044829110 from /__w/spectre/spectre/tests/Unit/Domain/
  CoordinateMaps/Test_CylindricalFlatSide.cpp:20
  center_two := { -0.76535466847668077, -0.85075479154646505, -0.
  9126563329133881 }
  radius_two := 0.62776611882835276
  center_one := { -0.59532728786461764, -0.54612010519825294, -2.
  14574583559335785 }
  proj_center := { -0.39516231691074355, -1.16902616959521755, -1.
  20081959438349295 }
  outer_radius := 0.06220574313362318
  inner_radius := 0.05283799303052518
  Seed is: 4076109290 from /__w/spectre/spectre/tests/Unit/Helpers/Domain/
  CoordinateMaps/TestMapHelpers.hpp:550
  height := 0.72846636943615373
  phi := 4.93863268679043887
  radius := 1.12072917569571717
  Test inverse map
  test_point := { 0.22431854694338099, -0.97451587442032472, 0.
  72846636943615373 }
  /__w/spectre/spectre/tests/Unit/Helpers/Domain/CoordinateMaps/TestMapHelpers.
  hpp:397: test_point == expected_test_point.value()
  a := { 0.22431854694338099, -0.97451587442032472, 0.72846636943615373 }
  b := { 0.22431854694339259, -0.9745158744203859, 0.72846636943615306 }

/__w/spectre/spectre/tests/Unit/Framework/TestingFramework.hpp:147: FAILED:
  CHECK( a == appx(b) )
with expansion:
  -0.97451587442032472
  ==
  Approx( -0.9745158744203859 )
with messages:
  CylindricalFlatSide
  Seed is: 1044829110 from /__w/spectre/spectre/tests/Unit/Domain/
  CoordinateMaps/Test_CylindricalFlatSide.cpp:20
  center_two := { -0.76535466847668077, -0.85075479154646505, -0.
  9126563329133881 }
  radius_two := 0.62776611882835276
  center_one := { -0.59532728786461764, -0.54612010519825294, -2.
  14574583559335785 }
  proj_center := { -0.39516231691074355, -1.16902616959521755, -1.
  20081959438349295 }
  outer_radius := 0.06220574313362318
  inner_radius := 0.05283799303052518
  Seed is: 4076109290 from /__w/spectre/spectre/tests/Unit/Helpers/Domain/
  CoordinateMaps/TestMapHelpers.hpp:550
  height := 0.72846636943615373
  phi := 4.93863268679043887
  radius := 1.12072917569571717
  Test inverse map
  test_point := { 0.22431854694338099, -0.97451587442032472, 0.
  72846636943615373 }
  /__w/spectre/spectre/tests/Unit/Helpers/Domain/CoordinateMaps/TestMapHelpers.
  hpp:397: test_point == expected_test_point.value()
  a := { 0.22431854694338099, -0.97451587442032472, 0.72846636943615373 }
  b := { 0.22431854694339259, -0.9745158744203859, 0.72846636943615306 }

0.014 s: Unit.Domain.CoordinateMaps.CylindricalFlatSide
===============================================================================
test cases:    1 |    0 passed | 1 failed
assertions: 4355 | 4353 passed | 2 failed

A catch test has failed.
```

### PR DESCRIPTION
**Pull request by markscheel**
## Proposed changes
Change allowed bounds in cylinder domains to fix occasional roundoff failures in tests.
Fixes #3380 

See detailed comments in commit messages.

### Code review checklist

- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).
- [ ] The PR lists upgrade instructions and is labeled `bugfix` or
  `new feature` if appropriate.

### CODE REVIEW

File: src/Domain/CoordinateMaps/FocallyLiftedMapHelpers.hpp [hunk 1]
```diff
@@ -125,7 +125,8 @@ std::optional<double> try_scale_factor(
     const std::array<double, 3>& src_point,
     const std::array<double, 3>& proj_center,
     const std::array<double, 3>& sphere_center, double radius,
-    bool pick_larger_root, bool pick_root_greater_than_one) noexcept;
+    bool pick_larger_root, bool pick_root_greater_than_one,
+    bool solve_for_root_minus_one = true) noexcept;
```
Comment (nilsvu) [inline src/Domain/CoordinateMaps/FocallyLiftedMapHelpers.hpp:137]: Could you add some docs for the added argument to the function-documentation?

**Review by nilsvu — CHANGES_REQUESTED** [review]

**Comment by nilsvu** [comment]
LGTM, please squash

**Comment by markscheel** [comment]
squashed

**Comment by nilsvu** [comment]
@kidder @wthrowe Would one of you take a brief look and merge this?

**Comment by wthrowe** [comment]
I'll take it, but you should submit an approval @nilsleiffischer.

**Review by nilsvu — APPROVED** [review]

**Review by wthrowe — APPROVED** [review]
