### PR TITLE
Scalar wave executable

### LINKED ISSUE #505: Variables compute items not updating correctly after mutate
The below test fails.  I believe it should pass.  I believe I have narrowed this down to a problem in DataBox rather than a problem in Variables, but I could be wrong on that.

```c++
namespace {
struct Tag1 : db::DataBoxTag {
  using type = Scalar<DataVector>;
  static constexpr db::DataBoxString label = "Tag1";
};
struct Tag2 : db::DataBoxTag {
  using type = Scalar<DataVector>;
  static constexpr db::DataBoxString label = "Tag2";
};
}

SPECTRE_TEST_CASE("Unit.DataStructures.DataBox.Variables2",
                  "[Unit][DataStructures]") {
  auto box = db::create<db::AddTags<Tags::Variables<tmpl::list<Tag1, Tag2>>>>(
      Variables<tmpl::list<Tag1, Tag2>>(1, 1.));

  db::mutate<Tags::Variables<tmpl::list<Tag1, Tag2>>>(
      box, [](auto& vars) {
        vars = Variables<tmpl::list<Tag1, Tag2>>(1, 2.);
      });
  CHECK(db::get<Tag1>(box) == Scalar<DataVector>(DataVector(1, 2.)));
}
```

### PR DESCRIPTION
**Pull request by nilsdeppe**
## Proposed changes

Note: Depends on #493 (which depends on #491). This means only the commits "Add tests for input files", "Add Parallel Compenent DgElementArray", and "Add 1D, 2D and 3D ScalarWave executables" are new.

- Close #505
- Adds testing infrastructure for input files. This should be flexible enough to allow easy extension of it in the future. Currently all input files are tested for parsing, this is not optional. It is possible to opt-in to having the executable run. Output is not checked, though.
- Add what is expected to be the core DgElementArray parallel component. I expect this to grow a bit as more features are added to the code, but this is enough for what we need right now.
- Add ScalarWave executables in 1D, 2D and 3D.

### Types of changes:

- [ ] Bugfix
- [x] New feature

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] Follows [code review guidelines](https://sxs-collaboration.github.io/spectre/code_review_guide.html)
- [ ] Code has documentation and unit tests
- [ ] Private member variables have a trailing underscore
- [ ] Do not use [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation), e.g. `double* pd_blah` is bad
- [ ] Header order:
  1. hpp corresponding to cpp (only in cpp files)
  2. Blank line (only in cpp files)
  3. STL and externals (in alphabetical order)
  4. Blank line
  5. SpECTRE includes (in alphabetical order)
- [ ] File lists in CMake are alphabetical
- [ ] Correct `noexcept` specification for functions (if unsure, mark `noexcept`)
- [ ] Mark objects `const` whenever possible
- [ ] Almost always `auto`, except with expression templates, i.e. `DataVector`
- [ ] All commits for performance changes provide quantitative evidence and the tests used to obtain said evidence.
- [ ] Make sure error messages are helpful, e.g. "The number of grid points in the matrix 'F' is not the same as the number of grid points in the determinant."
- [ ] Prefix commits addressing PR requests with `fixup`

### CODE REVIEW

File: src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+      Parallel::get_parallel_component<DgElementArray>(local_cache)
+          .perform_algorithm();
+    }
+  }
+};
+
+template <class Metavariables, class ActionList>
+void DgElementArray<Metavariables, ActionList>::initialize(
+    Parallel::CProxy_ConstGlobalCache<Metavariables>& global_cache,
+    std::unique_ptr<DomainCreator<volume_dim, Frame::Inertial>> domain_creator,
```
Comment (osheamonn) [inline src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp]: Can this be a const ref? Does it even matter for a `unique_ptr`?

File: src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+    double initial_time, double initial_dt) noexcept {
```
Comment (osheamonn) [inline src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp]: Should both these be const?

File: src/Evolution/Systems/ScalarWave/System.hpp [hunk 3]
```diff
@@ -1,4 +1,3 @@
-
```
Comment (osheamonn) [inline src/Evolution/Systems/ScalarWave/System.hpp:1]: Why the extra newline?

File: tests/InputFiles/ScalarWave/Input1DPeriodic.yaml [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+    UpperBound: [6.283185307179586]
+    IsPeriodicIn: [true]
+    InitialRefinement: [2]
+    InitialGridPoints: [7]
+
+TimeStepper:
+  AdamsBashforthN:
+    TargetOrder: 3
+
+NumericalFlux:
```
Comment (osheamonn) [inline tests/InputFiles/ScalarWave/Input1DPeriodic.yaml]: Why does this work? I would've thought no numerical flux being specified would be an error.

File: tests/InputFiles/ScalarWave/Input1DPeriodic.yaml [hunk 5]
```diff
@@ -0,0 +1,30 @@
+# Distributed under the MIT License.
+# See LICENSE.txt for details.
+# Executable: EvolveScalarWave1D
```
Comment (osheamonn) [inline tests/InputFiles/ScalarWave/Input1DPeriodic.yaml]: I don't feel particularly strongly about this, but I like the idea of there being a newline after the licence. I find it makes it easier to parse since I've gotten into the habit of ignoring the licence text.

File: src/Evolution/Systems/ScalarWave/System.hpp (hunk 3 above)
Comment (nilsdeppe) [reply src/Evolution/Systems/ScalarWave/System.hpp:1]: I removed the extra newline. Is that an issue?

Comment (osheamonn) [reply src/Evolution/Systems/ScalarWave/System.hpp:1]: I must've been tired and thought the newline was being added...

File: tests/InputFiles/ScalarWave/Input1DPeriodic.yaml (hunk 4 above)
Comment (kidder) [reply tests/InputFiles/ScalarWave/Input1DPeriodic.yaml]: NumericalFlux -> NumericalFluxParameters

File: cmake/AddInputFileTests.cmake [hunk 6]
```diff
@@ -0,0 +1,130 @@
+# Distributed under the MIT License.
+# See LICENSE.txt for details.
+
+function(add_single_input_file_test INPUT_FILE EXECUTABLE CHECK_TYPE TIMEOUT)
+  # Extract just the name of the input file
+  string(FIND "${INPUT_FILE}" "/" POSITION_OF_LAST_SLASH REVERSE)
```
Comment (kidder) [inline cmake/AddInputFileTests.cmake]: get_filename_component

File: cmake/AddInputFileTests.cmake [hunk 7]
```diff
@@ -0,0 +1,130 @@
...
+
+  string(SUBSTRING "${INPUT_FILE}" ${POSITION_OF_LAST_SLASH}
+    ${LENGTH_OF_INPUT_FILE_PATH}
+    INPUT_FILE_NAME)
+
+  # Extract the main subdirectory name
+  string(FIND "${INPUT_FILE}" "tests/InputFiles/" POSITION_OF_INPUT_FILE_DIR)
+  math(EXPR
+    POSITION_OF_INPUT_FILE_DIR
+    ${POSITION_OF_INPUT_FILE_DIR}+17
```
Comment (kidder) [inline cmake/AddInputFileTests.cmake:12]: comment magic number

File: cmake/AddInputFileTests.cmake [hunk 8]
```diff
@@ -0,0 +1,130 @@
...
+    )
+
+  math(EXPR
+    LENGTH_OF_EXECUTABLE_CLASS
+    ${POSITION_OF_LAST_SLASH}-${POSITION_OF_INPUT_FILE_DIR}-1
+    )
+
+  string(SUBSTRING "${INPUT_FILE}" ${POSITION_OF_INPUT_FILE_DIR}
+    ${LENGTH_OF_EXECUTABLE_CLASS}
```
Comment (kidder) [inline cmake/AddInputFileTests.cmake]: EXECUTABLE_CLASS -> EXECUTABLE_DIR_NAME

File: cmake/AddInputFileTests.cmake [hunk 9]
```diff
@@ -0,0 +1,130 @@
...
+    TIMEOUT ${TIMEOUT}
+    LABELS "${TAGS}"
+    ENVIRONMENT "ASAN_OPTIONS=detect_leaks=0")
+endfunction()
+
+# Searches the directory INPUT_FILE_DIR for .yaml files and adds a
+# test for each one. The input files must contain a line of the form:
+# '# Executable: EvolveScalarWave1D'
+# with the name of the executable that should be able to parse and run
+# using the input file, and a line one the form:
```
Comment (kidder) [inline cmake/AddInputFileTests.cmake]: of the form

File: cmake/AddInputFileTests.cmake [hunk 10]
```diff
@@ -0,0 +1,130 @@
...
+    # Extract executable name, and remove trailing white space
+    string(REGEX REPLACE "#[ ]*Executable:[ ]*" ""
+      INPUT_FILE_EXECUTABLE "${INPUT_FILE_EXECUTABLE}")
+    string(STRIP "${INPUT_FILE_EXECUTABLE}" INPUT_FILE_EXECUTABLE)
+
+    # Read what tests to do. Currently only "execute" is available
+    # "parse" is ignored because it's always run, empty is accepted.
+    string(REGEX MATCH "#[ ]*Check:[^\n]+"
+      INPUT_FILE_CHECKS "${INPUT_FILE_CONTENTS}")
+    # Extract executable name, and remove trailing white space
```
Comment (kidder) [inline cmake/AddInputFileTests.cmake]: please

File: cmake/AddInputFileTests.cmake [hunk 11]
```diff
@@ -0,0 +1,130 @@
...
+      INPUT_FILE_CHECKS "${INPUT_FILE_CHECKS}")
+    string(STRIP "${INPUT_FILE_CHECKS}" INPUT_FILE_CHECKS)
+
+    add_single_input_file_test(
+        ${INPUT_FILE}
+        ${INPUT_FILE_EXECUTABLE}
+        "parse"
+        ${TIMEOUT}
+        )
+    foreach(CHECK_TYPE ${INPUT_FILE_CHECKS})
```
Comment (kidder) [inline cmake/AddInputFileTests.cmake]: list removing duplicates

**Review by kidder — CHANGES_REQUESTED** [review]

File: src/NumericalAlgorithms/DiscontinuousGalerkin/Tags.hpp [hunk 12]
```diff
@@ -0,0 +1,19 @@
...
+
+namespace CacheTags {
+/*!
+ * \ingroup CacheTagsGroup
+ * \brief The global cache tag that retrieves the parameters for the numerical
+ * flux from the input file
+ */
+template <typename NumericalFluxType>
+struct NumericalFluxParams {
+  static constexpr OptionString help = "The type of the numerical flux";
```
Comment (kidder) [inline src/NumericalAlgorithms/DiscontinuousGalerkin/Tags.hpp]: The options for the numerical flux

File: src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp [hunk 13]
```diff
@@ -0,0 +1,92 @@
...
+#include "Domain/InitialElementIds.hpp"
+#include "Domain/Tags.hpp"
+#include "Evolution/DiscontinuousGalerkin/InitializeElement.hpp"
+#include "Parallel/Info.hpp"
+#include "Time/Tags.hpp"
+#include "Utilities/TMPL.hpp"
+
+template <class Metavariables, class ActionList>
+struct DgElementArray {
+  static constexpr const size_t volume_dim = Metavariables::system::volume_dim;
```
Comment (kidder) [inline src/Evolution/DiscontinuousGalerkin/DgElementArray.hpp]: no const

File: src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp [hunk 14]
```diff
@@ -0,0 +1,78 @@
...
+
+  using component_list = tmpl::list<DgElementArray<
+      EvolutionMetavars,
+      tmpl::list<Actions::ComputeVolumeDuDt<Dim>,
+                 dg::Actions::SendDataForFluxes,
+                 dg::Actions::ComputeBoundaryFlux<EvolutionMetavars>,
+                 Actions::UpdateU, Actions::AdvanceTime, Actions::FinalTime>>>;
+
+  static constexpr const char* const help{
+      "Evolve a Scalar Wave in 1 spatial dimension"};
```
Comment (kidder) [inline src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp]: 1 -> dim

Comment (kidder) [reply src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp]: describe metavariables

File: src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp [hunk 15]
```diff
@@ -0,0 +1,78 @@
...
+  using domain_creator_tag = OptionTags::DomainCreator<Dim, Frame::Inertial>;
+
+  using component_list = tmpl::list<DgElementArray<
+      EvolutionMetavars,
+      tmpl::list<Actions::ComputeVolumeDuDt<Dim>,
+                 dg::Actions::SendDataForFluxes,
+                 dg::Actions::ComputeBoundaryFlux<EvolutionMetavars>,
+                 Actions::UpdateU, Actions::AdvanceTime, Actions::FinalTime>>>;
+
+  static constexpr const char* const help{
```
Comment (kidder) [inline src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp]: OptionString

File: src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp [hunk 16]
```diff
@@ -0,0 +1,78 @@
...
+      "Evolve a Scalar Wave in 1 spatial dimension"};
+  static constexpr bool ignore_unrecognized_command_line_options = false;
```
Comment (kidder) [inline src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp]: remove

File: src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp [hunk 17]
```diff
@@ -0,0 +1,78 @@
...
+
+  enum class Phase {
+    Initialization,
+    PerformSingletonAlgorithm,
```
Comment (kidder) [inline src/Evolution/Executables/ScalarWave/EvolveScalarWave.hpp]: remove

**Review by kidder — CHANGES_REQUESTED** [review]

**Comment by nilsdeppe** [comment]
Okay, I've updated the PR addressing the comments and adding (as the new first commit) the fix to DataBox that is in #505, which is needed for SW to work

**Review by kidder — APPROVED** [review]
